Repository opencast/opencast, pull requests merged in 2018-11, with the labels that each got.

#492 MH-13169, Update bibliographic metadata when technical metadata changes
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/eventController.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/event-details.html
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/DublinCoreMetadataUtil.java
Labels: bug, enhancement

#537 MH-13206 Use correct mouse cursor in filters
  modules/admin-ui/src/main/webapp/styles/main.scss
Labels: bug

#538 MH-13201 Convert uploaded images to appropriate size and format
  etc/encoding/engage-images.properties
  etc/workflows/partial-preview.xml
  etc/workflows/partial-publish.xml
Labels: bug, enhancement

#550 MH-13216, Fix Documentation Pages
  .travis.yml
  docs/guides/admin/docs/modules/adaptivestreaming-wowza.md
  docs/guides/admin/docs/modules/searchindex.md
  docs/guides/admin/docs/modules/videoeditor.architecture.md
  docs/guides/admin/docs/workflowoperationhandlers/watermark-woh.md
  docs/guides/admin/mkdocs.yml
  docs/guides/developer/docs/modules/player/testing.md
  docs/guides/developer/mkdocs.yml
  docs/guides/user/mkdocs.yml
  docs/guides/user/site/css/highlight.css
  docs/guides/user/site/css/theme.css
  docs/guides/user/site/css/theme_extra.css
Labels: bug, documentation

#551 MH-13217, pom.xml housekeeping
  pom.xml
Labels: maintenance

#523 MH-13191 Improve performance of event deletion (1)
  modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/query/ADeleteQuery.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/ADeleteQueryDecorator.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/AbstractADeleteQuery.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/DeleteQueryContribution.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
Labels: enhancement

#535 MH-13200 Remove unused file acl-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/acl-modal.html
Labels: maintenance

#534 MH-13127: Make table headers non-interactive by default
  modules/admin-ui/src/main/webapp/scripts/modules/configuration/controllers/emailtemplatesController.js
  modules/admin-ui/src/main/webapp/scripts/modules/configuration/controllers/themesController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/eventsController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/seriesController.js
  modules/admin-ui/src/main/webapp/scripts/modules/recordings/controllers/locationblacklistsController.js
  modules/admin-ui/src/main/webapp/scripts/modules/recordings/controllers/recordingsController.js
  modules/admin-ui/src/main/webapp/scripts/modules/systems/controllers/jobsController.js
  modules/admin-ui/src/main/webapp/scripts/modules/systems/controllers/serversController.js
  modules/admin-ui/src/main/webapp/scripts/modules/systems/controllers/servicesController.js
  modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/aclsController.js
  modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/groupsController.js
  modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/userblacklistsController.js
  modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/usersController.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/table.html
  modules/admin-ui/src/main/webapp/scripts/shared/services/tableService.js
  modules/admin-ui/src/main/webapp/styles/components/_tables.scss
  modules/admin-ui/src/test/resources/test/unit/shared/services/tableServiceSpec.js
Labels: bug

#398 MH-13000: Group “Edit scheduled” events by weekday
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/util/BulkUpdateUtil.java
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-de_DE.json
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/editEventsController.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/edit-events-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/services/jsHelperService.js
  modules/admin-ui/src/main/webapp/styles/components/modals/_modal-base.scss
  modules/admin-ui/src/main/webapp/styles/views/modals/_edit-events.scss
  modules/admin-ui/src/test/java/org/opencastproject/adminui/util/BulkUpdateUtilTest.java
  modules/admin-ui/src/test/resources/bulkupdate/instructions.json
  modules/admin-ui/src/test/resources/test/unit/modules/events/controllers/editEventsControllerSpec.js
  modules/scheduler-api/src/main/java/org/opencastproject/scheduler/api/Util.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
  modules/scheduler-impl/src/test/java/org/opencastproject/scheduler/impl/SchedulerServiceImplTest.java
Labels: feature, needs_translation

#556 MH-13224, Drop commons-beanutils
  NOTICES
  assemblies/karaf-features/src/main/feature/feature.xml
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/endpoint/AbstractAssetManagerRestEndpoint.java
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/endpoint/ComposerRestService.java
  modules/inspection-service-ffmpeg/pom.xml
  modules/runtime-info/pom.xml
  modules/runtime-info/src/main/java/org/opencastproject/runtimeinfo/rest/RestDocData.java
  modules/runtime-info/src/main/java/org/opencastproject/runtimeinfo/rest/RestEndpointData.java
  modules/runtime-info/src/main/java/org/opencastproject/runtimeinfo/rest/RestParamData.java
  modules/runtime-info/src/main/java/org/opencastproject/runtimeinfo/rest/StatusData.java
  modules/runtime-info/src/test/java/org/opencastproject/runtimeinfo/rest/RestDocsAnnotationTest.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/endpoint/SearchRestService.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/endpoint/SeriesRestService.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/endpoint/WorkflowRestService.java
  modules/workflow-service-impl/src/main/resources/sample/audio.mp3
  modules/workflow-service-impl/src/main/resources/sample/camera.mpg
  modules/workflow-service-impl/src/main/resources/sample/captions.dfxp.xml
  modules/workflow-service-impl/src/main/resources/sample/captions_test_eng.srt
  modules/workflow-service-impl/src/main/resources/sample/captions_test_fra.srt
  modules/workflow-service-impl/src/main/resources/sample/compose-distribute-publish.xml
  modules/workflow-service-impl/src/main/resources/sample/dc-1.xml
  modules/workflow-service-impl/src/main/resources/sample/dc-2.xml
  modules/workflow-service-impl/src/main/resources/sample/image.jpg
  modules/workflow-service-impl/src/main/resources/sample/index.txt
  modules/workflow-service-impl/src/main/resources/sample/screen.mpg
  modules/workflow-service-impl/src/main/resources/sample/slidechanges.mov
  pom.xml
Labels: bug, documentation, maintenance

#529 MH-13198, Properly Display Multiple Presenters
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/eventsController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/seriesController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/eventsPresentersCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/seriesContributorsCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/seriesCreatorsCell.html
  modules/admin-ui/src/main/webapp/scripts/shared/resources/eventsResource.js
  modules/admin-ui/src/main/webapp/scripts/shared/resources/seriesResource.js
  modules/admin-ui/src/main/webapp/styles/extensions/components/_tables.scss
  modules/admin-ui/src/test/resources/test/unit/shared/resources/eventsResourceSpec.js
  modules/admin-ui/src/test/resources/test/unit/shared/resources/seriesResourceSpec.js
Labels: enhancement

#505 MH-13183 Add link to series details, out of the eventstable-view
  modules/admin-ui/src/main/webapp/img/more-series-icon.png
  modules/admin-ui/src/main/webapp/img/more-series-icon_2x.png
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/eventActionsCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/seriesActionsCell.html
  modules/admin-ui/src/main/webapp/styles/components/_tables.scss
Labels: feature

#576 MH-13237 Track previews do not work with stream security
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ToolsEndpoint.java
Labels: bug

#570 MH-13214, Fix HTTP Digest Authentication
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/InMemoryUserAndRoleProvider.java
  modules/userdirectory/src/main/resources/OSGI-INF/user-and-role-directory-service.xml
Labels: bug

#583 MH-13249, Invalid Group Endpoint Registration
  modules/userdirectory/src/main/resources/OSGI-INF/group-role-provider.xml
Labels: bug

#565 MH-13234, Workspace Deprecation Fixes
  modules/workspace-impl/src/main/java/org/opencastproject/workspace/impl/WorkspaceImpl.java
Labels: maintenance

#584 MH-13250 Thumbnail feature does not work for unprivileged users
  etc/security/mh_default_org.xml
Labels: bug

#590 MH-13255, Updated Deprecated Methods in Workspace Tests
  modules/workspace-impl/src/test/java/org/opencastproject/workspace/impl/WorkspaceImplTest.java
Labels: maintenance

#594 MH-13260, Simplify Runtime Info UI
  modules/runtime-info/pom.xml
  modules/runtime-info/src/main/java/org/opencastproject/runtimeinfo/ComponentsJsonParser.java
  modules/runtime-info/src/main/java/org/opencastproject/runtimeinfo/RuntimeInfo.java
Labels: maintenance

#578 MH-13242 Set disable_search_threshold for chosen globally
  modules/admin-ui/src/main/webapp/scripts/app.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/subresources/partials/tools.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/editableSingleValue.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/acl-details.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/delete-events-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/edit-events-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/event-details.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/retract-published-event-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/schedule-task-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/series-details.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/timeline.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/wizards/bulk-message.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/wizards/locationblacklist.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/wizards/new-acl.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/wizards/new-event.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/wizards/new-series.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/wizards/userblacklist.html
Labels: maintenance

#595 MH-13261, User Directory OSGI Service Definitions
  modules/userdirectory/pom.xml
  modules/userdirectory/src/main/resources/OSGI-INF/role-endpoint.xml
  modules/userdirectory/src/main/resources/OSGI-INF/user-and-role-directory-service.xml
  modules/userdirectory/src/main/resources/OSGI-INF/user-and-role-provider-inmemory.xml
  modules/userdirectory/src/main/resources/OSGI-INF/user-and-role-provider-jpa.xml
  modules/userdirectory/src/main/resources/OSGI-INF/user-endpoint.xml
  modules/userdirectory/src/main/resources/OSGI-INF/user-util-endpoint.xml
Labels: maintenance

#593 MH-13259, User/Role Directory Cleanup
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/UserAndRoleDirectoryServiceImpl.java
Labels: maintenance

#579 MH-12816 Make waveform size configurable in WOH
  docs/guides/admin/docs/workflowoperationhandlers/waveform-woh.md
  etc/org.opencastproject.waveform.ffmpeg.WaveformServiceImpl.cfg
  etc/workflows/partial-preview.xml
  modules/waveform-api/src/main/java/org/opencastproject/waveform/api/WaveformService.java
  modules/waveform-ffmpeg/src/main/java/org/opencastproject/waveform/endpoint/WaveformServiceEndpoint.java
  modules/waveform-ffmpeg/src/main/java/org/opencastproject/waveform/ffmpeg/WaveformServiceImpl.java
  modules/waveform-ffmpeg/src/test/java/org/opencastproject/waveform/ffmpeg/WaveformServiceImplTest.java
  modules/waveform-remote/src/main/java/org/opencastproject/waveform/remote/WaveformServiceRemote.java
  modules/waveform-workflowoperation/src/main/java/org/opencastproject/workflow/handler/waveform/WaveformWorkflowOperationHandler.java
  modules/waveform-workflowoperation/src/test/java/org/opencastproject/workflow/handler/waveform/WaveformWorkflowOperationHandlerTest.java
Labels: feature
