Repository opencast/opencast, pull requests merged in 2018-04, with the labels that each got.

#19 MH-10560 Live Scheduler Service
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/admin/docs/modules/index.md
  docs/guides/admin/docs/modules/liveschedule.md
  docs/guides/admin/mkdocs.yml
  docs/scripts/activemq/activemq.xml
  etc/listproviders/publication.channels.properties
  etc/org.opencastproject.liveschedule.impl.LiveScheduleServiceImpl.cfg
  etc/workflows/fast.xml
  etc/workflows/schedule-and-upload.xml
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/eventController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/publishedCell.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/event-details.html
  modules/admin-ui/src/main/webapp/scripts/shared/resources/eventsResource.js
  modules/admin-ui/src/main/webapp/styles/components/_popover.scss
  modules/admin-ui/src/test/resources/eventGeneral.json
  modules/common/src/main/java/org/opencastproject/mediapackage/Track.java
  modules/common/src/main/java/org/opencastproject/mediapackage/elementbuilder/TrackBuilderPlugin.java
  modules/common/src/main/java/org/opencastproject/mediapackage/track/TrackImpl.java
  modules/common/src/test/java/org/opencastproject/mediapackage/track/TrackTest.java
  modules/common/src/test/resources/publication-with-elements.xml
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js
  modules/engage-ui/src/main/resources/ui/language/en-GB.json
  modules/engage-ui/src/main/resources/ui/language/en-US.json
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventUtils.java
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/impl/IngestServiceImpl.java
  modules/live-schedule-api/pom.xml
  modules/live-schedule-api/src/main/java/org/opencastproject/liveschedule/api/LiveScheduleException.java
  modules/live-schedule-api/src/main/java/org/opencastproject/liveschedule/api/LiveScheduleService.java
  modules/live-schedule-impl/pom.xml
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImpl.java
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/message/AssetManagerUpdateHandler.java
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/message/LiveScheduleMessageReceiver.java
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/message/SchedulerUpdateHandler.java
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/message/UpdateHandler.java
  modules/live-schedule-impl/src/main/resources/OSGI-INF/asset-manager-update-handler.xml
  modules/live-schedule-impl/src/main/resources/OSGI-INF/live-schedule-message-receiver.xml
  modules/live-schedule-impl/src/main/resources/OSGI-INF/live-schedule-service.xml
  modules/live-schedule-impl/src/main/resources/OSGI-INF/scheduler-update-handler.xml
  modules/live-schedule-impl/src/test/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImplTest.java
  modules/live-schedule-impl/src/test/resources/assetmanager-mp-with-live.xml
  modules/live-schedule-impl/src/test/resources/assetmanager-mp.xml
  modules/live-schedule-impl/src/test/resources/episode.xml
  modules/live-schedule-impl/src/test/resources/live-mp.xml
  modules/live-schedule-impl/src/test/resources/search-result-empty.xml
  modules/live-schedule-impl/src/test/resources/search-result.xml
  modules/live-schedule-impl/src/test/resources/series.xml
  pom.xml
Labels: feature

#164 MH-12797, Explain UI Actions
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/main/webapp/index.html
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/eventActionsCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/eventsLocationCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/eventsSeriesCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/eventsStatusCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/eventsTechnicalDateCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/seriesActionsCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/seriesTitleCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/recordings/partials/recordingActionsCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/recordings/partials/recordingsNameCell.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/tableFilters.html
Labels: feature

#168 MH-12797 Explain UI actions (added missing tooltips)
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/main/webapp/scripts/modules/configuration/partials/themesActionsCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/users/partials/aclActionsCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/users/partials/groupActionsCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/users/partials/userActionsCell.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/event-details.html
Labels: feature, needs_translation

#89 MH-12703: Add userdirectory for Moodle
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/admin/docs/configuration/security.user.moodle.md
  docs/guides/admin/mkdocs.yml
  etc/org.opencastproject.userdirectory.moodle-default.cfg.template
  modules/userdirectory-moodle/pom.xml
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUser.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderFactory.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderInstance.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleWebService.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleWebServiceException.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleWebServiceImpl.java
  modules/userdirectory-moodle/src/main/resources/OSGI-INF/metatype/metatype.xml
  modules/userdirectory-moodle/src/main/resources/OSGI-INF/moodle-user-factory.xml
  modules/userdirectory-moodle/src/test/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderTest.java
  pom.xml
Labels: feature

#161 MH-12793, Collapse multiple, redundant composer process methods
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/EncoderEngine.java
Labels: feature

#150 MH-12091: Implement per-tenant digest user for capture agents
  etc/org.opencastproject.organization-mh_default_org.cfg
  etc/security/mh_default_org.xml
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerWithMessaging.java
  modules/common/src/main/java/org/opencastproject/security/api/SecurityConstants.java
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/impl/IngestServiceImpl.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/InMemoryUserAndRoleProvider.java
Labels: feature

#200 MH-12843, Fix “Add Event” Tab Index
  modules/admin-ui/src/main/webapp/scripts/shared/partials/wizards/new-event.html
Labels: bug

#205 MH-12856, Silencedetector test broken
  modules/matterhorn-silencedetection-impl/src/test/java/org/opencastproject/silencedetection/ffmpeg/SilenceDetectorTest.java
  modules/matterhorn-silencedetection-impl/src/test/resources/silent.mp4
Labels: bug
