Repository opencast/opencast, pull requests merged in 2018-08, with the labels that each got.

#348 MH-12829 Make admin-ui statistics configurable
  docs/guides/admin/docs/configuration/index.md
  docs/guides/admin/docs/configuration/ui.md
  docs/guides/user/docs/searchandfilter.md
  etc/listproviders/adminui.stats.properties
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/EndpointUtil.java
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/main/webapp/index.html
  modules/admin-ui/src/main/webapp/scripts/lib/moment-with-locales.js
  modules/admin-ui/src/main/webapp/scripts/lib/moment.min.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/eventsController.js
  modules/admin-ui/src/main/webapp/scripts/shared/directives/statsDirective.js
  modules/admin-ui/src/main/webapp/scripts/shared/resources/resourcesListResource.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/relativeDatesService.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/statsService.js
  modules/admin-ui/src/test/resources/app/GET/admin-ng/resources/STATS.json
  modules/admin-ui/src/test/resources/karma.conf.js
  modules/admin-ui/src/test/resources/test/unit/modules/events/controllers/eventsControllerSpec.js
  modules/admin-ui/src/test/resources/test/unit/shared/services/relativeDatesServiceSpec.js
Labels: feature

#312 MH-12966 Do not pre-select-from option in metadata property sheets
  modules/admin-ui/src/main/webapp/scripts/shared/partials/editableSingleSelect.html
Labels: bug

#353 MH-13006 Waveform operation cleanup creates problem with asynchronous NFS
  modules/scheduler-impl/src/test/java/org/opencastproject/scheduler/impl/UnitTestWorkspace.java
  modules/waveform-workflowoperation/src/main/java/org/opencastproject/workflow/handler/waveform/WaveformWorkflowOperationHandler.java
  modules/workspace-api/src/main/java/org/opencastproject/workspace/api/Workspace.java
  modules/workspace-impl/src/main/java/org/opencastproject/workspace/impl/WorkspaceImpl.java
Labels: bug

#360 MH-13014 Don't show stale search results
  modules/admin-ui/src/main/webapp/scripts/shared/resources/eventsResource.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/tableService.js
Labels: bug

#358 MH-13008 Prefill other input of startdate filter
  modules/admin-ui/src/main/webapp/scripts/shared/directives/tableFilterDirective.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/tableFilters.html
  modules/admin-ui/src/test/resources/test/unit/shared/directives/tableFilterDirectiveSpec.js
Labels: enhancement

#362 MH-13016, Workflow display order not working in editor screen
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ToolsEndpoint.java
  modules/admin-ui/src/main/webapp/scripts/modules/events/subresources/partials/tools.html
Labels: bug

#340 MH-12992: Trigger conflict check in “Edit scheduled” on “Next”
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-de_DE.json
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/editEventsController.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/edit-events-modal.html
Labels: maintenance

#352 MH-13003: Implement detection of already recorded (as opposed to yet to be recorded, scheduled) events by the index service
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/Event.java
  modules/index-service/src/test/java/org/opencastproject/index/service/impl/event/EventTest.java
Labels: bug

#335 MH-12987 Prohibit changing a scheduled event to be in the past
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/eventController.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/schedulingHelperService.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/new-event/source.js
Labels: maintenance

#346 MH-12998: Clear conflicts when closing “Edit Scheduled Events” modal
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/editEventsController.js
Labels: bug

#379 MH-12016: Scrolling role fetch
  modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/userController.js
  modules/admin-ui/src/main/webapp/scripts/shared/directives/loadingScrollerDirective.js
  modules/admin-ui/src/test/resources/test/unit/modules/users/controllers/userControllerSpec.js
Labels: bug

#357 MH-13012 The iterable metadata values should not be splitted by `,`
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/DublinCoreMetadataCollection.java
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/DublinCoreMetadataUtil.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventIndexUtils.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventUtils.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/series/SeriesIndexUtils.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/ContributorsListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/util/ListProviderUtil.java
Labels: bug

#236 MH-12889 Intuitive Merging of Video Segments
  modules/admin-ui/src/main/webapp/scripts/modules/events/subresources/controllers/video/editController.js
  modules/admin-ui/src/main/webapp/scripts/shared/directives/timelineDirective.js
  modules/admin-ui/src/test/resources/test/unit/shared/directives/timelineDirectiveSpec.js
Labels: feature

#338 MH-12989 Add missing roles for actions->edit scheduled
  etc/security/mh_default_org.xml
  etc/security/security_sample_ldap.xml-example
Labels: maintenance

#329 MH-12803 Fix for mp 'start' when event is created (affects live scheduler service)
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/events/CommonEventCatalogUIAdapter.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
  modules/index-service/src/test/java/org/opencastproject/index/service/impl/IndexServiceImplTest.java
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImpl.java
Labels: bug

#367 MH-13018 re-add recordings json to 5x (includes MH-12828 re-add conflicts.json)
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/endpoint/SchedulerRestService.java
  modules/scheduler-impl/src/test/java/org/opencastproject/scheduler/impl/SchedulerServiceImplTest.java
Labels: bug

#392 MH-12688: Add translations for comment filter values
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-de_DE.json
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/EventsListProvider.java
Labels: maintenance, needs_translation

#400 MH-13049: Fix video editor zoom dropdown showing wrong value
  modules/admin-ui/src/main/webapp/scripts/shared/partials/timeline.html
Labels: bug

#193 MH-12826: Make workflow processing settings persistent
  etc/security/mh_default_org.xml
  etc/workflows/publish-after-cutting.xml
  etc/workflows/publish.xml
  etc/workflows/schedule-and-upload.xml
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/TasksEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ToolsEndpoint.java
  modules/admin-ui/src/main/webapp/index.html
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/bulkDeleteController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/retractEventController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/scheduleTaskController.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/schedule-task-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/resources/eventWorkflowPropertiesResource.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/new-event/processing.js
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TasksEndpointTest.java
  modules/admin-ui/src/test/resources/test/unit/modules/events/controllers/scheduleTaskControllerSpec.js
  modules/admin-ui/src/test/resources/test/unit/shared/services/wizards/new-event/proccessingSpec.js
  modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/query/AQueryBuilder.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AQueryBuilderDecorator.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/AQueryBuilderImpl.java
  modules/asset-manager-util/src/main/java/org/opencastproject/assetmanager/util/WorkflowPropertiesUtil.java
  modules/common/src/main/java/org/opencastproject/systems/OpencastConstants.java
  modules/index-service/src/main/java/org/opencastproject/index/service/api/IndexService.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
  modules/index-service/src/test/java/org/opencastproject/index/service/impl/IndexServiceImplTest.java
  modules/workflow-service-impl/pom.xml
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
  modules/workflow-service-impl/src/main/resources/OSGI-INF/workflow-service.xml
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowServiceImplTest.java
Labels: feature

#404 MH-13067, Configuration panel does not work for default workflow
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/new-event/processing.js
Labels: bug
