Repository opencast/opencast, pull requests merged in 2018-09, with the labels that each got.

#405 MH-13068 workflow delete instance stability improvement
  modules/matterhorn-workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: bug

#410 MH-13074, Clean up asset manager REST endpoints
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/endpoint/AbstractAssetManagerRestEndpoint.java
Labels: maintenance

#383 MH-13034: Add lis_person_sourcedid back as LTI source field for the username
  modules/matterhorn-kernel/src/main/java/org/opencastproject/kernel/security/LtiLaunchAuthenticationHandler.java
Labels: bug

#403 MH-13022: Fix LTI highly trusted keys being discarded
  modules/matterhorn-kernel/src/main/java/org/opencastproject/kernel/security/LtiLaunchAuthenticationHandler.java
Labels: bug

#407 MH-13070, Update JS build and test libraries
  modules/admin-ui/package-lock.json
  modules/admin-ui/package.json
Labels: maintenance

#408 MH-13071, Update markdown linter
  docs/guides/package-lock.json
  docs/guides/package.json
Labels: maintenance

#409 MH-13072, Remove broken ltitool player
  modules/lti/src/main/resources/tools/player/css/oc.pager.css
  modules/lti/src/main/resources/tools/player/css/oc.search.browse.css
  modules/lti/src/main/resources/tools/player/episode-segments.xml
  modules/lti/src/main/resources/tools/player/episode.xml
  modules/lti/src/main/resources/tools/player/index.html
Labels: maintenance

#399 MH-13064, Encoding profile mimetypes are mostly ignored
  docs/guides/admin/docs/configuration/encoding.md
  docs/guides/admin/docs/workflowoperationhandlers/demux-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/imagetovideo-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/start-watson-transcription-woh.md
  etc/encoding/adaptive-streaming-movies.properties
  etc/encoding/engage-images.properties
  etc/encoding/engage-movies.properties
  etc/encoding/fast-movies.properties
  etc/encoding/feed-images.properties
  etc/encoding/opencast-images.properties
  etc/encoding/opencast-movies.properties
  etc/encoding/watson-audio.properties
  etc/encoding/webm.properties
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/EncodingProfileScanner.java
  modules/composer-ffmpeg/src/test/java/org/opencastproject/composer/impl/EncodingProfileTest.java
  modules/composer-ffmpeg/src/test/resources/encodingprofiles.properties
  modules/composer-ffmpeg/src/test/resources/encodingtestprofiles.properties
  modules/composer-service-api/src/main/java/org/opencastproject/composer/api/EncodingProfile.java
  modules/composer-service-api/src/main/java/org/opencastproject/composer/api/EncodingProfileImpl.java
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/ImageWorkflowOperationHandler.java
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/SegmentPreviewsWorkflowOperationHandler.java
  modules/composer-workflowoperation/src/test/java/org/opencastproject/workflow/handler/composer/ComposeWorkflowOperationHandlerTest.java
  modules/composer-workflowoperation/src/test/java/org/opencastproject/workflow/handler/composer/CompositeWorkflowOperationHandlerTest.java
  modules/composer-workflowoperation/src/test/java/org/opencastproject/workflow/handler/composer/ConcatWorkflowOperationHandlerTest.java
  modules/composer-workflowoperation/src/test/java/org/opencastproject/workflow/handler/composer/DemuxWorkflowOperationHandlerTest.java
  modules/composer-workflowoperation/src/test/java/org/opencastproject/workflow/handler/composer/ImageToVideoWorkflowOperationHandlerTest.java
  modules/composer-workflowoperation/src/test/java/org/opencastproject/workflow/handler/composer/MultiEncodeWorkflowOperationHandlerTest.java
  modules/composer-workflowoperation/src/test/java/org/opencastproject/workflow/handler/composer/ProcessSmilWorkflowOperationHandlerTest.java
Labels: bug, maintenance

#411 MH-13073 Don't split series metadata fields by ,
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/SeriesEndpoint.java
Labels: bug

#406 MH-13069, Update problematic admin interface libraries
  modules/admin-ui/package-lock.json
  modules/admin-ui/package.json
Labels: maintenance

#417 MH-13088, Update Several Dependencies
  assemblies/karaf-features/src/main/feature/feature.xml
  pom.xml
Labels: maintenance

#416 MH-13087, Update Runtime UI Libraries
  modules/runtime-info-ui/package-lock.json
  modules/runtime-info-ui/package.json
  modules/runtime-info-ui/pom.xml
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/login.html
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular-route/.bower.json
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular-route/README.md
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular-route/angular-route.js
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular-route/angular-route.min.js
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular-route/angular-route.min.js.map
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular-route/bower.json
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular-route/package.json
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular/.bower.json
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular/README.md
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular/angular-csp.css
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular/angular.js
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular/angular.min.js
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular/angular.min.js.gzip
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular/angular.min.js.map
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular/bower.json
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular/index.js
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/angular/package.json
  modules/runtime-info-ui/src/main/resources/ui/img/key-icon.png
  modules/runtime-info-ui/src/main/resources/ui/img/key-icon_2x.png
  modules/runtime-info-ui/src/main/resources/ui/img/user-input-icon.png
  modules/runtime-info-ui/src/main/resources/ui/img/user-input-icon_2x.png
Labels: maintenance

#252 MH-12904, Paella player 5.3 update
  etc/paella/mh_default_org/config.json
  modules/engage-paella-player/package-lock.json
  modules/engage-paella-player/package.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/mh_description.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsPlugin/mh_downloads.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.episodesFromSeries/mh_episodes_from_serie.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/01_prerequisites.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/02_accesscontrol.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/03_videoloader.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/04_datadelegates.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/05_initdelegate.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/05_loader.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/localization/en-US.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/localization/es-ES.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.logIn/log_in.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.searchPlugin/mh_search.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.transcriptionTabBarPlugin/mh_transcription.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.userTrackingSaverPlugIn/mh_usertracking_saver.js
  modules/engage-paella-player/src/main/paella-opencast/ui/auth.html
  modules/engage-paella-player/src/main/paella-opencast/ui/embed.html
  modules/engage-paella-player/src/main/paella-opencast/ui/watch.html
Labels: feature

#387 MH-12810 External API 1.1.0 - Add filters for new fields
  docs/guides/developer/docs/api/events-api.md
  docs/guides/developer/docs/api/series-api.md
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SeriesEndpoint.java
Labels: api_change, feature

#418 MH-13075: make ACL entries unique prior to running ACL comparisons
  modules/matterhorn-common/src/main/java/org/opencastproject/util/EqualsUtil.java
  modules/matterhorn-common/src/test/java/org/opencastproject/util/EqualUtilTest.java
  modules/matterhorn-series-service-impl/src/test/java/org/opencastproject/series/impl/SeriesServiceImplTest.java
Labels: bug

#167 [MH-12820] Mattermost-notification-workflowoperationhandler
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/admin/docs/workflowoperationhandlers/notification.md
  docs/guides/admin/mkdocs.yml
  modules/mattermost-notification-workflowoperation/pom.xml
  modules/mattermost-notification-workflowoperation/src/main/java/org/opencastproject/workflow/handler/mattermost/notification/MattermostNotificationWorkflowOperationHandler.java
  modules/mattermost-notification-workflowoperation/src/main/resources/OSGI-INF/operations/mattermost-notify.xml
  pom.xml
Labels: feature

#424 MH-13095, Add linter (checkstyle) for JavaScript
  modules/runtime-info-ui/.eslintrc.js
  modules/runtime-info-ui/package-lock.json
  modules/runtime-info-ui/package.json
  modules/runtime-info-ui/pom.xml
  modules/runtime-info-ui/src/main/resources/ui/admin-ng/scripts/app.js
Labels: enhancement

#421 MH-13091, Concat operation problem with FFMPEG 4.x
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
Labels: bug

#436 MH-13107, Update admin interface build dependencies
  modules/admin-ui/Gruntfile.js
  modules/admin-ui/package-lock.json
  modules/admin-ui/package.json
Labels: maintenance

#439 MH-13025: Fix workflow-definitions URL
  docs/guides/admin/docs/configuration/external-api.md
  etc/security/mh_default_org.xml
Labels: bug

#425 MH-13096: Set workflow variables with duplicated media package IDs
  docs/guides/admin/docs/workflowoperationhandlers/duplicate-event-woh.md
  modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/DuplicateEventWorkflowOperationHandler.java
Labels: feature

#435 MH-13106: Add Moodle groups to Moodle role provider
  docs/guides/admin/docs/configuration/security.user.moodle.md
  etc/org.opencastproject.userdirectory.moodle-default.cfg.template
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderFactory.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderInstance.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleWebService.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleWebServiceImpl.java
  modules/userdirectory-moodle/src/test/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderTest.java
Labels: feature

#441 MH-13113, Drop unused HTML page
  modules/admin-ui/src/main/webapp/scripts/modules/dashboard/partials/documentation.html
Labels: maintenance

#444 MH-13116, Fix typo in paella error message
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/05_loader.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/localization/en-US.json
Labels: bug

#443 MH-13115, Update Node, NPM and Libs
  modules/admin-ui/package-lock.json
  modules/admin-ui/package.json
  modules/admin-ui/pom.xml
  modules/engage-paella-player/package-lock.json
  modules/engage-paella-player/pom.xml
  modules/lti/package-lock.json
  modules/lti/package.json
  modules/lti/pom.xml
  modules/runtime-info-ui-ng/package-lock.json
  modules/runtime-info-ui-ng/pom.xml
  modules/runtime-info-ui/package-lock.json
  modules/runtime-info-ui/package.json
  modules/runtime-info-ui/pom.xml
  pom.xml
Labels: maintenance

#442 MH-13114, Fix broken REST docs
  modules/common/src/main/resources/ui/restdocs/template.xhtml
  modules/runtime-info-ui-ng/src/main/resources/ui/docs.css
  modules/runtime-info-ui-ng/src/main/resources/ui/docs.js
Labels: bug

#332 MH-12985 Fix incorrect warnings in event modals
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/editEventsController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/validators/taskStartableValidator.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/schedule-task-modal.html
  modules/admin-ui/src/test/resources/test/unit/modules/events/validators/taskStartableValidatorSpec.js
Labels: bug

#327 [MH-12930] Fill creator metadata field with actual user when new event
  etc/index/adminui/event-mapping.json
  etc/index/externalapi/event-mapping.json
  etc/org.opencastproject.ui.metadata.CatalogUIAdapterFactory-episode-common.cfg
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/index/AdminUISearchIndex.java
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/index-service/src/main/java/org/opencastproject/index/service/api/EventIndex.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/Event.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventIndexSchema.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventIndexUtils.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventQueryBuilder.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventSearchQuery.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventUtils.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/ContributorsListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/EventsListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/query/EventListQuery.java
Labels: feature

#448 MH-13123: Update paella player 6.0.2
  etc/paella/mh_default_org/config.json
  modules/engage-paella-player/package-lock.json
  modules/engage-paella-player/package.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/mh_description.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.episodesFromSeries/mh_episodes_from_serie.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.logIn/log_in.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.transcriptionTabBarPlugin/mh_transcription.js
Labels: maintenance
