Repository opencast/opencast, pull requests merged in 2018-12, with the labels that each got.

#544 MH-13209, Put CAS Feature In Distributions
  assemblies/pom.xml
Labels: bug

#588 MH-13253, External Elasticsearch
  docs/guides/admin/docs/modules/index.md
  docs/guides/admin/docs/modules/searchindex/elasticsearch.md
  docs/guides/admin/docs/modules/searchindex/index.md
  docs/guides/admin/docs/modules/searchindex/solr.md
  docs/guides/admin/docs/modules/searchindex/solr1.png
  docs/guides/admin/docs/modules/searchindex/solr2.png
  docs/guides/admin/docs/modules/searchindex/solr3.png
  docs/guides/admin/mkdocs.yml
  etc/custom.properties
  modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/index/AdminUISearchIndex.java
  modules/external-api/src/main/java/org/opencastproject/external/impl/index/ExternalIndex.java
  modules/index-service/src/test/java/org/opencastproject/index/service/message/TestSearchIndex.java
  modules/search/pom.xml
  modules/search/src/main/java/org/opencastproject/matterhorn/search/impl/AbstractElasticsearchIndex.java
  modules/search/src/test/java/org/opencastproject/matterhorn/search/impl/SearchIndexImplStub.java
Labels: enhancement, feature

#587 MH-13252, Ineffective Synchronization of Elasticsearch Startup
  modules/search/src/main/java/org/opencastproject/matterhorn/search/impl/AbstractElasticsearchIndex.java
Labels: bug

#589 MH-13254, Automate Dependency Checking
  modules/animate-api/pom.xml
  modules/animate-impl/pom.xml
  modules/animate-remote/pom.xml
  modules/workspace-api/pom.xml
  modules/workspace-impl/pom.xml
  pom.xml
Labels: enhancement

#605 NOJIRA: Fix misspelled digest
  modules/kernel/src/main/java/org/opencastproject/kernel/security/LtiLaunchAuthenticationHandler.java
Labels: maintenance

#602 MH-13215 WorkflowOperationTagUtil throws a null pointer
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowOperationTagUtil.java
Labels: bug

#606 MH-13266 Start date cross link does not work correctly
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/eventsController.js
Labels: bug

#608 MH-13269, Handle Authorization Errors
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/authorization-manager/src/main/java/org/opencastproject/authorization/xacml/manager/impl/AclServiceImpl.java
Labels: bug

#580 MH-13243, Asset Manager ACL Cache Updates
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerWithSecurity.java
Labels: bug

#609 MH-13270, Fix Message Item Serialization
  modules/message-broker-api/pom.xml
  modules/message-broker-api/src/main/java/org/opencastproject/message/broker/api/scheduler/SchedulerItem.java
  modules/message-broker-api/src/main/java/org/opencastproject/message/broker/api/series/SeriesItem.java
  modules/message-broker-api/src/main/java/org/opencastproject/message/broker/api/theme/ThemeItem.java
Labels: bug

#527 MH-13196, Unregister Resource Servlets of Bundles to be Removed
  modules/kernel/src/main/java/org/opencastproject/kernel/rest/RestPublisher.java
Labels: bug

#617 MH-13278, Drop Unused Exception
  modules/common/src/main/java/org/opencastproject/util/data/FunctionException.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/SeriesServiceImpl.java
Labels: maintenance

#592 MH-13258, Broken User Provider Removal
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/UserAndRoleDirectoryServiceImpl.java
Labels: bug

#598 MH-13263, Invalid Ingest Encoding
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/endpoint/IngestRestService.java
  modules/ingest-service-impl/src/test/java/org/opencastproject/ingest/endpoint/IngestRestServiceTest.java
Labels: bug

#597 MH-13257: Fix outdated command line argument for tesseract >= 4.0.0
  docs/guides/admin/docs/modules/textextraction.md
  etc/custom.properties
  modules/textextractor-tesseract/src/test/java/org/opencastproject/analysis/text/TesseractTextExtractorTest.java
Labels: bug

#624 MH-13283, Fix Custom CXF Error Handler
  modules/kernel/src/main/java/org/opencastproject/kernel/rest/RestPublisher.java
Labels: bug

#613 MH-13276, Drop org.opencastproject.fun
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestEventEndpoint.java
  modules/common/src/main/java/org/opencastproject/fun/Fns.java
  modules/common/src/main/java/org/opencastproject/fun/juc/Immutables.java
  modules/common/src/main/java/org/opencastproject/fun/juc/Iterables.java
  modules/common/src/main/java/org/opencastproject/fun/juc/Lists.java
  modules/common/src/main/java/org/opencastproject/fun/juc/Mutables.java
  modules/common/src/main/java/org/opencastproject/fun/juc/package-info.java
  modules/common/src/main/java/org/opencastproject/job/api/IncidentImpl.java
  modules/common/src/main/java/org/opencastproject/job/api/IncidentTreeImpl.java
  modules/common/src/main/java/org/opencastproject/job/api/IncidentUtil.java
  modules/common/src/main/java/org/opencastproject/job/api/JaxbIncident.java
  modules/common/src/main/java/org/opencastproject/mediapackage/MediaPackageSupport.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/Incidents.java
  modules/common/src/main/java/org/opencastproject/util/Log.java
  modules/common/src/main/java/org/opencastproject/util/persistence/PersistenceUtil.java
  modules/common/src/main/java/org/opencastproject/util/persistencefn/PersistenceUtil.java
  modules/common/src/test/java/org/opencastproject/job/api/IncidentParserTest.java
  modules/common/src/test/java/org/opencastproject/job/api/JaxbIncidentTest.java
  modules/common/src/test/java/org/opencastproject/job/api/JaxbIncidentTreeTest.java
  modules/common/src/test/java/org/opencastproject/job/api/JaxbJobTest.java
  modules/common/src/test/java/org/opencastproject/job/api/JobImplTest.java
  modules/common/src/test/java/org/opencastproject/serviceregistry/api/IncidentsTest.java
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
  modules/email-template-service-impl/src/test/java/org/opencastproject/email/template/impl/EmailTemplateServiceImplTest.java
  modules/engage-paella-player/package-lock.json
  modules/incident-workflowoperation/src/main/java/org/opencastproject/workflow/handler/incident/IncidentCreatorWorkflowOperationHandler.java
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/server/OaiXmlGen.java
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/util/XmlGen.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/AbstractIncidentService.java
  modules/serviceregistry/src/test/java/org/opencastproject/serviceregistry/impl/OsgiIncidentServiceTest.java
Labels: maintenance
