Repository opencast/opencast, pull requests merged in 2018-07, with the labels that each got.

#291 MH-12948, Directly read XACML files
  modules/authorization-xacml/src/main/java/org/opencastproject/authorization/xacml/XACMLAuthorizationService.java
Labels: enhancement

#315 MH-12970, Senseless XACML parsing
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerWithSecurity.java
  modules/authorization-xacml/src/main/java/org/opencastproject/authorization/xacml/XACMLAuthorizationService.java
  modules/common/src/main/java/org/opencastproject/security/api/AuthorizationService.java
  modules/live-schedule-impl/src/test/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImplTest.java
Labels: bug

#344 MH-12995 Fix conflict check not detecting some conflicts
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
Labels: bug

#347 MH-13001 Fixed live scheduler service pom
  modules/live-schedule-impl/pom.xml
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImpl.java
Labels: bug

#363 MH-13017, JS syntax error in publish workflow
  etc/workflows/publish.xml
Labels: bug

#316 MH-12972, Drop unused getAclAttachments
  modules/authorization-xacml/src/main/java/org/opencastproject/authorization/xacml/XACMLAuthorizationService.java
  modules/common/src/main/java/org/opencastproject/security/api/AuthorizationService.java
  modules/live-schedule-impl/src/test/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImplTest.java
Labels: maintenance
