Repository opencast/opencast, pull requests merged in 2019-01, with the labels that each got.

#638 MH-13297, FasterXML Jackson Bugfix Update
  pom.xml
Labels: bug

#639 MH-13299 Make multi-select fields consistent again
  modules/admin-ui/src/main/webapp/scripts/shared/directives/editableMultiSelectDirective.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/editableMultiSelect.html
  modules/admin-ui/src/test/resources/test/unit/shared/directives/editableMultiSelectDirectiveSpec.js
Labels: bug

#640 MH-13300 Display multi-value fields correctly on summary pages
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/new-event/metadata.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/new-series/metadata.js
Labels: bug

#649 MH-13309: return empty list when finding findUsersByUserName when the name param is empty.
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaUserReferenceProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/UserDirectoryPersistenceUtil.java
Labels: bug

#581 MH-13244 Improve concurrency of OAIPMH republication
  modules/authorization-manager/src/main/java/org/opencastproject/authorization/xacml/manager/impl/AclServiceImpl.java
  modules/authorization-manager/src/test/java/org/opencastproject/authorization/xacml/manager/endpoint/TestRestService.java
  modules/conductor/src/main/java/org/opencastproject/event/handler/AssetManagerUpdatedEventHandler.java
  modules/conductor/src/main/java/org/opencastproject/event/handler/SeriesUpdatedEventHandler.java
  modules/conductor/src/main/java/org/opencastproject/event/handler/WorkflowPermissionsUpdatedEventHandler.java
  modules/message-broker-api/src/main/java/org/opencastproject/message/broker/api/series/SeriesItem.java
  modules/series-service-api/src/main/java/org/opencastproject/series/api/SeriesService.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/endpoint/SeriesRestService.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/SeriesServiceImpl.java
  modules/series-service-remote/src/main/java/org/opencastproject/series/remote/SeriesServiceRemoteImpl.java
Labels: enhancement

#651 SUREFIRE-1588: Resolving compilation issue on Debian and related distros
  pom.xml
Labels: bug

#548 MH-13213, Separate External API Index
  assemblies/karaf-features/src/main/feature/feature.xml
  modules/external-api-index/pom.xml
  modules/external-api-index/src/main/java/org/opencastproject/external/index/ExternalIndex.java
  modules/external-api-index/src/main/resources/OSGI-INF/external-index.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-acl.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-assetmanager.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-comment.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-group.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-scheduler.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-series.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-theme.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-workflow.xml
  modules/external-api/pom.xml
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/BaseEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/GroupsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SeriesEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowsEndpoint.java
  modules/external-api/src/main/resources/OSGI-INF/external-base-endpoint.xml
  modules/external-api/src/main/resources/OSGI-INF/external-events-endpoint.xml
  modules/external-api/src/main/resources/OSGI-INF/external-groups-endpoint.xml
  modules/external-api/src/main/resources/OSGI-INF/external-series-endpoint.xml
  modules/external-api/src/main/resources/OSGI-INF/external-workflows-endpoint.xml
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/TestBaseEndpoint.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/TestEventsEndpoint.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/TestSeriesEndpoint.java
  pom.xml
Labels: enhancement

#610 MH-13271, Remove Useless ACL Check
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/SearchServiceImpl.java
Labels: maintenance
