Repository opencast/opencast, pull requests merged in 2019-10, with the labels that each got.

#1054 MH-13710: Fix a bug in paella loader plugin when a track has no tags
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/03_oc_search_converter.js
Labels: bug

#1106 Update to ESLint 6.5.0
  modules/admin-ui/package-lock.json
  modules/admin-ui/package.json
  modules/engage-paella-player/package-lock.json
  modules/engage-paella-player/package.json
  modules/engage-theodul-core/package.json
  modules/engage-ui/package-lock.json
  modules/engage-ui/package.json
  modules/lti/package-lock.json
  modules/lti/package.json
  modules/runtime-info-ui-ng/package-lock.json
  modules/runtime-info-ui-ng/package.json
  modules/runtime-info-ui/package-lock.json
  modules/runtime-info-ui/package.json
Labels: ELAN, maintenance

#1107 ESLint for Theodul Core
  modules/engage-theodul-core/package-lock.json
  modules/engage-theodul-core/package.json
  modules/engage-theodul-core/pom.xml
  modules/engage-theodul-core/src/main/resources/ui/js/engage/core.js
  modules/engage-theodul-core/src/main/resources/ui/js/engage/event.js
  modules/engage-theodul-core/src/main/resources/ui/js/engage/models/engage.js
  modules/engage-theodul-core/src/main/resources/ui/js/engage/models/meInfo.js
  modules/engage-theodul-core/src/main/resources/ui/js/engage/models/pluginInfo.js
  modules/engage-theodul-core/src/main/resources/ui/js/engage/tab_logic.js
  modules/engage-theodul-core/src/main/resources/ui/js/engage/views/desktop.js
  modules/engage-theodul-core/src/main/resources/ui/js/engage/views/embed.js
  modules/engage-theodul-core/src/main/resources/ui/js/engage/views/mobile.js
Labels: ELAN, enhancement, maintenance

#1088 MH-13476 Filter capture agent roles for ACLs
  modules/capture-admin-service-impl/src/main/java/org/opencastproject/capture/admin/impl/CaptureAgentAdminRoleProviderImpl.java
Labels: UCT

#1110 Build failed on captions-impl tests for non english OS
  modules/caption-impl/src/main/java/org/opencastproject/caption/converters/GoogleSpeechCaptionConverter.java
  modules/caption-impl/src/main/java/org/opencastproject/caption/converters/IBMWatsonCaptionConverter.java
Labels: ELAN, bug, needs attention

#884 MH-13542 Display global notifications as overlay
  etc/org.opencastproject.organization-mh_default_org.cfg
  modules/admin-ui/src/main/webapp/scripts/modules/events/subresources/controllers/toolsController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/subresources/partials/tools.html
  modules/admin-ui/src/main/webapp/scripts/shared/directives/notificationDirective.js
  modules/admin-ui/src/main/webapp/scripts/shared/directives/notificationsDirective.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/notifications.html
  modules/admin-ui/src/main/webapp/scripts/shared/services/notificationsService.js
  modules/admin-ui/src/main/webapp/styles/components/_alerts.scss
  modules/admin-ui/src/test/resources/test/unit/modules/events/subresources/controllers/toolsControllerSpec.js
Labels: SWITCH, feature

#1131 Issue1123 TEMP FIX for Paella Player Build error
  modules/engage-paella-player/gulpfile.js
  modules/engage-paella-player/paella622dependency/npm-shrinkwrap.json
  modules/engage-paella-player/pom.xml
Labels: bug

#1102 Clean-up Fast Testing Workflow
  etc/workflows/fast.xml
Labels: ELAN, enhancement

#1130 Updated com.fasterxml.jackson from version 2.9.9 to 2.10.0.
  pom.xml
Labels: ELAN, bug

#1133 Better JPA Annotation for Scheduler
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/persistence/ExtendedEventDto.java
Labels: ELAN, bug, enhancement

#1146 Remove unnecessary global package-lock.json
  package-lock.json
Labels: ELAN

#1105 Use JPA to auto-generate SQL schema
  modules/search-service-impl/pom.xml
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/persistence/SearchEntity.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/persistence/SearchServiceDatabaseImpl.java
  modules/search-service-impl/src/main/resources/META-INF/persistence.xml
  modules/search-service-impl/src/test/java/org/opencastproject/search/impl/SearchServiceImplTest.java
  modules/search-service-impl/src/test/java/org/opencastproject/search/impl/persistence/SearchServicePersistenceTest.java
Labels: ELAN, enhancement, maintenance

#1134 Do not use stack-overflow logo
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/eventActionsCell.html
Labels: ELAN, bug

#1141 Consider file extension of uploaded asset
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
  modules/index-service/src/main/java/org/opencastproject/index/service/util/RequestUtils.java
Labels: ELAN, SWITCH, bug

#1148 VideoEditorServiceImpl: Fixed the file extension duplication with removeExtention from FilenameUtils.
  modules/videoeditor-ffmpeg-impl/src/main/java/org/opencastproject/videoeditor/impl/VideoEditorServiceImpl.java
Labels: bug

#1143 Upgrade jackson to 2.9.10 (6.x)
  pom.xml
Labels: maintenance

#1142 Update apache commons-compress to 1.19
  pom.xml
Labels: bug

#1101 Filter jobs by transcription service provider ID
  etc/workflows/google-speech-attach-transcripts.xml
  modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java
Labels: UCT

#1164 CentOS basic installation guide rewording
  docs/guides/admin/docs/installation/rpm-rhel-sl-centos.md
Labels: documentation

#1132 Fixed the "hide" button in the Documentation.
  docs/guides/admin/docs/css/extra.css
  docs/guides/developer/docs/css/extra.css
  docs/guides/user/docs/css/extra.css
Labels: ELAN, bug, documentation

#1170 MH-9753: Prepare AV WOH can throw a NPE
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/PrepareAVWorkflowOperationHandler.java
Labels: bug
