Repository opencast/opencast, pull requests merged in 2019-09, with the labels that each got.

#1036 MH-13697, Workflow Index Rebuild Memory
  modules/common-jpa-impl/src/main/java/org/opencastproject/job/jpa/JpaJob.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/ServiceRegistry.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/ServiceRegistryInMemoryImpl.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImpl.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: bug, enhancement

#973 MH-13577 Don't consider raw fields updated
  modules/dublincore/src/main/java/org/opencastproject/metadata/dublincore/MetadataField.java
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/ConfigurableDCCatalogUIAdapter.java
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/DublinCoreMetadataCollection.java
  modules/index-service/src/test/java/org/opencastproject/index/service/catalog/adapter/DublinCoreCatalogUIAdapterTest.java
Labels: bug

#862 MH-13516 add single step event deletion
  docs/guides/admin/docs/releasenotes.md
  etc/org.opencastproject.adminui.cfg
  etc/workflows/delete.xml
  etc/workflows/partial-retract.xml
  etc/workflows/retract.xml
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/AdminUIConfiguration.java
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/bulkDeleteController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/eventsController.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/confirm-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/delete-events-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/retract-published-event-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/resources/eventHasSnapshotsResource.js
  modules/admin-ui/src/main/webapp/scripts/shared/resources/eventsResource.js
  modules/admin-ui/src/main/webapp/styles/views/modals/_modal-dialog.scss
  modules/admin-ui/src/test/resources/test/unit/modules/events/controllers/bulkDeleteControllerSpec.js
  modules/common/src/main/java/org/opencastproject/rest/BulkOperationResult.java
  modules/index-service/src/main/java/org/opencastproject/index/service/api/IndexService.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventUtils.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/Retraction.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/RetractionListener.java
  modules/index-service/src/main/resources/OSGI-INF/index_service.xml
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowListener.java
Labels: feature

#1040 MH-13701 Interpret source-audio-name correctly for composite operation
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/CompositeWorkflowOperationHandler.java
Labels: bug

#714 MH-12533, Re-introduce ability to avoid data loss during ingest
  etc/org.opencastproject.ingest.impl.IngestServiceImpl.cfg
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/impl/IngestServiceImpl.java
  modules/ingest-service-impl/src/test/java/org/opencastproject/ingest/impl/IngestServiceImplTest.java
  modules/ingest-service-impl/src/test/resources/source-manifest-partial.xml
  modules/ingest-service-impl/src/test/resources/source-manifest.xml
Labels: bug, enhancement

#1061 MH-13716, Update xmlsec
  pom.xml
Labels: bug

#968 MH-13632, Resolution Based, Conditional Encoding
  docs/guides/admin/docs/workflowoperationhandlers/encode-woh.md
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
Labels: feature

#1059 MH-13714, Hide Column `Stop` By Default
  modules/admin-ui/src/main/webapp/scripts/shared/services/tableService.js
Labels: enhancement

#1050 MH-13447 && MH-13425 - Feeds-Tab / adds a new tab in series properties.
  etc/feeds/series.properties
  modules/admin-ui/pom.xml
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/FeedEndpoint.java
  modules/admin-ui/src/main/resources/OSGI-INF/feed_endpoint.xml
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/serieController.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/series-details.html
  modules/admin-ui/src/test/resources/test/unit/modules/events/controllers/serieControllerSpec.js
  modules/search-service-api/src/main/java/org/opencastproject/feed/api/FeedGenerator.java
  modules/search-service-impl/pom.xml
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/AbstractFeedGenerator.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/FeedServiceImpl.java
Labels: feature

#1022 MH-13681 Automatic publication of streaming URLs
  docs/guides/admin/docs/modules/liveschedule.md
  etc/custom.properties
  etc/org.opencastproject.liveschedule.impl.LiveScheduleServiceImpl.cfg
  modules/common/src/main/java/org/opencastproject/mediapackage/Publication.java
  modules/common/src/main/java/org/opencastproject/mediapackage/PublicationImpl.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandler.java
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImpl.java
  modules/live-schedule-impl/src/test/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImplTest.java
Labels: enhancement

#1062 MH-13676, start on used port
  assemblies/resources/bin/check_ports
Labels: bug, maintenance

#1063 MH-13717: Only events with write access
  etc/org.opencastproject.adminui.endpoint.OsgiEventEndpoint.cfg
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/OsgiEventEndpoint.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestEventEndpoint.java
Labels: feature

#1058 MH-13713, Custom LTI Series Tool Styles
  docs/guides/admin/docs/modules/ltimodule.md
  etc/ui-config/mh_default_org/ltitools/series.css
  modules/lti/src/main/resources/tools/series/index.html
Labels: enhancement, feature

#942 MH-13570 Theodul player ui config
  docs/guides/admin/docs/modules/player.configuration.md
  etc/org.opencastproject.organization-mh_default_org.cfg
  etc/ui-config/mh_default_org/theodul/config.yml
  modules/engage-theodul-core/src/main/resources/ui/js/engage/core.js
  modules/engage-theodul-core/src/main/resources/ui/js/engage/models/engage.js
  modules/engage-theodul-core/src/main/resources/ui/js/engage/models/meInfo.js
  modules/engage-theodul-core/src/main/resources/ui/js/lib/js-yaml.min.js
  modules/engage-theodul-plugin-tab-shortcuts/src/main/resources/static/main.js
  modules/engage-theodul-plugin-video-videojs/src/main/resources/static/main.js
Labels: documentation, enhancement

#1021 MH-13683: Moving mediapackages needs to handle missing version information
  modules/asset-manager-workflowoperation/src/main/java/org/opencastproject/workflow/handler/assetmanager/AssetManagerStorageMoveOperationHandler.java
Labels: bug

#1066 Major developer docs update
  docs/guides/developer/docs/installation/source-linux.md
Labels: ELAN

#1071 Fix Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ELAN, documentation, maintenance, needs attention

#1079 Remove Workflow Operations from Worker
  assemblies/karaf-features/src/main/feature/feature.xml
Labels: ELAN, bug

#1086 Fix CI Builds (Crop Tests)
  modules/crop-ffmpeg/src/test/java/org/opencastproject/crop/CropServiceTest.java
Labels: bug, needs attention

#1075 Remove State Mapping “Importing”
  etc/workflows/schedule-and-upload.xml
Labels: ELAN, enhancement

#1074 Navbar icons toggle
  modules/admin-ui/src/main/webapp/scripts/shared/directives/oldDropdownDirective.js
Labels: ELAN

#1082 Docs readme extended.
  docs/guides/readme.md
Labels: ELAN, documentation

#1084 Fix Player ID Parameter Parsing
  modules/engage-theodul-plugin-custom-mhConnection/src/main/resources/static/models/mediaPackage.js
Labels: ELAN, bug, needs attention

#1065 MH-13720 Remove the RoleProvider.getRoles() method
  modules/admin-ui/src/main/java/org/opencastproject/adminui/userdirectory/UIRolesRoleProvider.java
  modules/capture-admin-service-impl/src/main/java/org/opencastproject/capture/admin/impl/CaptureAgentAdminRoleProviderImpl.java
  modules/common/src/main/java/org/opencastproject/security/api/RoleDirectoryService.java
  modules/common/src/main/java/org/opencastproject/security/api/RoleProvider.java
  modules/external-api/src/main/java/org/opencastproject/external/userdirectory/ExternalApiRoleProvider.java
  modules/security-aai/src/main/java/org/opencastproject/security/aai/ConfigurableLoginHandler.java
  modules/userdirectory-brightspace/src/main/java/org/opencastproject/userdirectory/brightspace/BrightspaceUserProviderInstance.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderInstance.java
  modules/userdirectory-sakai/src/main/java/org/opencastproject/userdirectory/sakai/SakaiUserProviderInstance.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/CustomRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/InMemoryUserAndRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaGroupRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaUserAndRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaUserReferenceProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/OrganizationRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/RoleEndpoint.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/UserAndRoleDirectoryServiceImpl.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/UserIdRoleProvider.java
  modules/userdirectory/src/test/java/org/opencastproject/userdirectory/JpaGroupRoleProviderTest.java
  modules/userdirectory/src/test/java/org/opencastproject/userdirectory/JpaUserProviderTest.java
  modules/userdirectory/src/test/java/org/opencastproject/userdirectory/UserAndRoleDirectoryServiceImplTest.java
Labels: UCT

#1087 Issue 1068, Stop job dispatcher before unregistering hosts, junit MH-13675
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/ServiceRegistryInMemoryImpl.java
  modules/common/src/main/java/org/opencastproject/util/persistence/PersistenceUtil.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImpl.java
  modules/serviceregistry/src/test/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImplTest.java
Labels: bug

#1092 MH-13517 Set an absolute limit on solr query size
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/SolrRequester.java
Labels: UCT, bug

#1072 MH-13706 fix the date cell of the events overview table in the admin UI
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/eventsController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/eventsDateCell.html
  modules/admin-ui/src/main/webapp/scripts/shared/resources/eventsResource.js
  modules/admin-ui/src/test/resources/test/unit/shared/resources/eventsResourceSpec.js
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/DublinCoreMetadataUtil.java
Labels: ELAN, ETH, bug

#1093 Provide access to file contents in the WFR
  modules/working-file-repository-service-api/src/main/java/org/opencastproject/workingfilerepository/api/WorkingFileRepository.java
  modules/working-file-repository-service-impl/src/main/java/org/opencastproject/workingfilerepository/impl/WorkingFileRepositoryImpl.java
  modules/working-file-repository-service-remote/src/main/java/org/opencastproject/workingfilerepository/remote/WorkingFileRepositoryRemoteImpl.java
Labels: UCT, enhancement, feature

#1094 Smarter etc/ hints in documentation
  docs/guides/admin/docs/javascript/extra.js
  docs/guides/developer/docs/javascript/extra.js
  docs/guides/user/docs/javascript/extra.js
Labels: bug, documentation

#1100 Player Scroll/Zoom Overlay
  modules/engage-theodul-plugin-video-videojs/src/main/resources/static/language/en-US.json
  modules/engage-theodul-plugin-video-videojs/src/main/resources/static/main.js
  modules/engage-theodul-plugin-video-videojs/src/main/resources/static/styles/desktop.css
  modules/engage-theodul-plugin-video-videojs/src/main/resources/static/templates/desktop.html
Labels: ELAN, enhancement, needs translation

#1098 Fix displaying tracks with no tags in player
  modules/engage-theodul-plugin-video-videojs/src/main/resources/static/main.js
Labels: ELAN, bug
