Repository opencast/opencast, pull requests merged in 2019-05, with the labels that each got.

#839 MH-13495 Ignore old requests instead of cancelling
  modules/admin-ui/src/main/webapp/scripts/shared/services/tableService.js
Labels: bug

#840 MH-13501 Match against user pattern for loadUser() lookups
  modules/userdirectory-sakai/src/main/java/org/opencastproject/userdirectory/sakai/SakaiUserProviderInstance.java
Labels: maintenance

#824 MH-13381, Use Username In Workflows
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/JobEndpoint.java
  modules/admin-ui/src/main/resources/OSGI-INF/job_endpoint.xml
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestEventEndpoint.java
  modules/admin-ui/src/test/resources/eventWorkflow.json
  modules/comments-workflowoperation/src/main/java/org/opencastproject/workflow/handler/comments/CommentWorkflowOperationHandler.java
  modules/comments-workflowoperation/src/main/resources/OSGI-INF/operations/comments.xml
  modules/comments-workflowoperation/src/test/java/org/opencastproject/workflow/handler/comments/CommentWorkflowOperationHandlerTest.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowsEndpoint.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/TestWorkflowsEndpoint.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowInstance.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowInstanceImpl.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceSolrIndex.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowServiceSolrIndexTest.java
Labels: enhancement

#848 MH-13508 Remove method canLogin from interface User
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/util/TestUser.java
  modules/common-jpa-impl/src/main/java/org/opencastproject/security/impl/jpa/JpaUser.java
  modules/common/src/main/java/org/opencastproject/security/api/JaxbUser.java
  modules/common/src/main/java/org/opencastproject/security/api/User.java
  modules/kernel/src/main/java/org/opencastproject/kernel/security/RemoteUserAndOrganizationFilter.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderInstance.java
  modules/userdirectory-sakai/src/main/java/org/opencastproject/userdirectory/sakai/SakaiUserProviderInstance.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/InMemoryUserAndRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/UserAndRoleDirectoryServiceImpl.java
  modules/userdirectory/src/test/java/org/opencastproject/userdirectory/UserAndRoleDirectoryServiceImplTest.java
Labels: maintenance

#853 MH-13330 The video editor does not always close after the user presses "Publish"
  modules/admin-ui/src/main/webapp/scripts/modules/events/subresources/controllers/toolsController.js
Labels: bug

#850 MH-13514 Add node name to host registration as a UI searchable alternative to hostname
  docs/guides/admin/docs/configuration/basic.md
  docs/scripts/ddl/mysql5.sql
  docs/upgrade/7_to_8/mysql5.sql
  etc/custom.properties
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/JobEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ServerEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ServicesEndpoint.java
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/main/webapp/scripts/modules/systems/controllers/jobsController.js
  modules/admin-ui/src/main/webapp/scripts/modules/systems/controllers/serversController.js
  modules/admin-ui/src/main/webapp/scripts/modules/systems/controllers/servicesController.js
  modules/admin-ui/src/main/webapp/scripts/shared/resources/jobsResource.js
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestJobEndpoint.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestServerEndpoint.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestServicesEndpoint.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/util/TestServiceRegistryFactory.java
  modules/admin-ui/src/test/resources/jobs.json
  modules/admin-ui/src/test/resources/jobsLimitOffset.json
  modules/admin-ui/src/test/resources/servers.json
  modules/admin-ui/src/test/resources/services.json
  modules/common-jpa-impl/src/main/java/org/opencastproject/serviceregistry/impl/jpa/HostRegistrationJpaImpl.java
  modules/common-jpa-impl/src/test/java/org/opencastproject/serviceregistry/impl/jpa/ServiceRegistrationJpaImplTest.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/HostRegistration.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/HostRegistrationInMemory.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/JaxbHostRegistration.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/ServiceRegistry.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/ServiceRegistryInMemoryImpl.java
  modules/common/src/main/java/org/opencastproject/systems/OpencastConstants.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/ServersListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/query/JobsListQuery.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/query/ServersListQuery.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/query/ServicesListQuery.java
  modules/index-service/src/test/java/org/opencastproject/index/service/resources/list/provider/ServersListProviderTest.java
  modules/publication-service-youtube-v3/src/test/java/org/opencastproject/publication/youtube/YouTubeV3PublicationServiceImplTest.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImpl.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/endpoint/ServiceRegistryEndpoint.java
  modules/serviceregistry/src/test/java/org/opencastproject/serviceregistry/impl/JobTest.java
  modules/serviceregistry/src/test/java/org/opencastproject/serviceregistry/impl/ServiceRegistrationTest.java
  modules/serviceregistry/src/test/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImplTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowServiceImplTest.java
Labels: enhancement, needs translation

#855 MH-13519 Migrate mappings to Elastic Search 5.x
  modules/search/src/main/resources/elasticsearch/event-mapping.json
  modules/search/src/main/resources/elasticsearch/group-mapping.json
  modules/search/src/main/resources/elasticsearch/series-mapping.json
  modules/search/src/main/resources/elasticsearch/theme-mapping.json
Labels: bug, maintenance

#851 MH-13496 Highlight main table rows on hover
  modules/admin-ui/src/main/webapp/scripts/modules/configuration/partials/index.html
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/index.html
  modules/admin-ui/src/main/webapp/scripts/modules/recordings/partials/index.html
  modules/admin-ui/src/main/webapp/scripts/modules/systems/partials/index.html
  modules/admin-ui/src/main/webapp/scripts/modules/users/partials/index.html
  modules/admin-ui/src/main/webapp/scripts/shared/directives/tableDirective.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/table.html
  modules/admin-ui/src/main/webapp/styles/base/_variables.scss
  modules/admin-ui/src/main/webapp/styles/components/_tables.scss
Labels: enhancement

#852 MH-13511 Adding events in parallel does not work correctly
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/newEventController.js
Labels: bug

#869 MH-13527 Remove unused method WorkflowDefinition.isPublished
  modules/transcription-service-workflowoperation/src/test/java/org/opencastproject/transcription/workflowoperation/AttachTranscriptionOperationHandlerTest.java
  modules/transcription-service-workflowoperation/src/test/java/org/opencastproject/transcription/workflowoperation/StartTranscriptionOperationHandlerTest.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowDefinition.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowDefinitionImpl.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowInstanceTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowServiceImplTest.java
  modules/workflow-service-impl/src/test/resources/workflow-definition-1.xml
  modules/workflow-service-impl/src/test/resources/workflow-definition-skipping.xml
Labels: maintenance

#865 MH-13524 Empty node name causes exception
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ServerEndpoint.java
Labels: bug

#875 MH-13533 Document parameter "sign" of GET /api/events/{id}/publications/*
  docs/guides/developer/docs/api/events-api.md
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
Labels: documentation

#842 MH-13502: Harmonizing the column names
  docs/scripts/ddl/mysql5.sql
  docs/upgrade/7_to_8/mysql5.sql
  modules/asset-manager-storage-aws/src/main/java/org/opencastproject/assetmanager/aws/persistence/AwsAssetMappingDto.java
  modules/distribution-service-aws-s3/src/test/java/org/opencastproject/distribution/aws/s3/AwsS3DistributionServiceImplTest.java
  modules/distribution-service-aws-s3/src/test/resources/mediapackage.xml
  modules/distribution-service-aws-s3/src/test/resources/mediapackage_distributed.xml
  modules/transcription-service-ibm-watson-impl/src/main/java/org/opencastproject/transcription/ibmwatson/persistence/TranscriptionJobControlDto.java
Labels: maintenance

#882 MH-13540 Navigation of statistics broken
  modules/admin-ui/src/main/webapp/scripts/modules/statistics/partials/index.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/mainNav.html
Labels: bug

#883 MH-13541 Remove inclusion of non-existent scripts in Admin UI
  modules/admin-ui/src/main/webapp/index.html
  modules/admin-ui/src/main/webapp/login.html
Labels: maintenance

#886 MH-13544 Video editor shows incorrect notification
  modules/admin-ui/src/main/webapp/scripts/modules/events/subresources/controllers/toolsController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/subresources/controllers/video/editController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/subresources/partials/tools.html
Labels: bug

#860 MH-13520 Remove unused fields from search index
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/AbstractSearchIndex.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/Event.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventIndexSchema.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventIndexUtils.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventQueryBuilder.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventSearchQuery.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/series/SeriesIndexSchema.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/series/SeriesSearchQuery.java
  modules/search/src/main/resources/elasticsearch/event-mapping.json
  modules/search/src/main/resources/elasticsearch/series-mapping.json
Labels: maintenance

#895 MH-13552, Update Tesseract Code
  modules/textanalyzer-api/src/main/java/org/opencastproject/textextractor/api/TextExtractor.java
  modules/textanalyzer-api/src/main/java/org/opencastproject/textextractor/api/TextFrame.java
  modules/textanalyzer-api/src/main/java/org/opencastproject/textextractor/api/TextLine.java
  modules/textanalyzer-impl/src/main/java/org/opencastproject/textanalyzer/impl/TextAnalyzerServiceImpl.java
  modules/textextractor-tesseract/pom.xml
  modules/textextractor-tesseract/src/main/java/org/opencastproject/textextractor/tesseract/TesseractLine.java
  modules/textextractor-tesseract/src/main/java/org/opencastproject/textextractor/tesseract/TesseractTextExtractor.java
  modules/textextractor-tesseract/src/main/java/org/opencastproject/textextractor/tesseract/TesseractTextFrame.java
  modules/textextractor-tesseract/src/main/resources/OSGI-INF/tesseract.xml
  modules/textextractor-tesseract/src/test/java/org/opencastproject/analysis/text/TesseractTextExtractorTest.java
  modules/textextractor-tesseract/src/test/java/org/opencastproject/analysis/text/TesseractTextFrameTest.java
  modules/textextractor-tesseract/src/test/java/org/opencastproject/analysis/text/TesseractTextLineTest.java
Labels: maintenance

#856 MH-13503: Job Dispatch Fairness
  docs/guides/admin/docs/releasenotes.md
  modules/common-jpa-impl/src/main/java/org/opencastproject/serviceregistry/impl/jpa/ServiceRegistrationJpaImpl.java
  modules/common/src/main/java/org/opencastproject/job/api/AbstractJobProducer.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/ServiceRegistryInMemoryImpl.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/SystemLoad.java
  modules/common/src/test/java/org/opencastproject/job/api/AbstractJobProducerTest.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImpl.java
  modules/serviceregistry/src/test/java/org/opencastproject/serviceregistry/impl/JobTest.java
  modules/serviceregistry/src/test/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImplTest.java
Labels: enhancement

#896 MH-13553, Fix Paella Track Selection
  docs/guides/admin/docs/releasenotes.md
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/03_oc_search_converter.js
Labels: bug

#868 MH-13526 Show unequal tracks correctly in editor
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ToolsEndpoint.java
  modules/common/src/main/java/org/opencastproject/mediapackage/MediaPackageImpl.java
Labels: bug

#877 MH-13536 OAI-PMH Remote Broken
  modules/publication-service-oaipmh-remote/src/main/java/org/opencastproject/publication/oaipmh/remote/OaiPmhPublicationServiceRemoteImpl.java
Labels: bug

#857 MH-13497 resume on past table page when leaving video editor
  modules/admin-ui/src/main/webapp/scripts/modules/events/subresources/controllers/toolsController.js
Labels: enhancement

#898 MH-13555, Fix Spelling of Flavor
  docs/guides/admin/docs/modules/videoeditor.architecture.md
  docs/guides/admin/docs/workflowoperationhandlers/silence-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/tag-by-dcterm-woh.md
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/03_oc_search_converter.js
  modules/search-service-api/src/main/java/org/opencastproject/feed/api/Link.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/EnclosureImpl.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/LinkImpl.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/RomeAtomFeed.java
Labels: maintenance

#899 MH-13556, Fix Login Page
  modules/admin-ui/src/main/webapp/login.html
Labels: bug

#885 MH-13543 Rework workflow conditions, add string data type
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/admin/docs/configuration/workflow.md
  modules/workflow-condition-parser/pom.xml
  modules/workflow-condition-parser/src/main/antlr4/org/opencastproject/workflow/conditionparser/antlr/WorkflowCondition.g4
  modules/workflow-condition-parser/src/main/java/org/opencastproject/workflow/conditionparser/Atom.java
  modules/workflow-condition-parser/src/main/java/org/opencastproject/workflow/conditionparser/ComparisonOperator.java
  modules/workflow-condition-parser/src/main/java/org/opencastproject/workflow/conditionparser/NumericalOperator.java
  modules/workflow-condition-parser/src/main/java/org/opencastproject/workflow/conditionparser/WorkflowConditionBooleanInterpreter.java
  modules/workflow-condition-parser/src/main/java/org/opencastproject/workflow/conditionparser/WorkflowConditionInterpreter.java
  modules/workflow-condition-parser/src/test/java/org/opencastproject/workflow/conditionparser/PropertyReplacementTest.java
  modules/workflow-condition-parser/src/test/java/org/opencastproject/workflow/conditionparser/WorkflowConditionInterpreterTest.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowOperationInstance.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowOperationInstanceImpl.java
  modules/workflow-service-impl/pom.xml
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowOperationWorker.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/PropertyReplacementTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowOperationSkippingIntricateTest.java
  modules/workflow-service-impl/src/test/resources/workflow-definition-skipping-intricate.xml
  pom.xml
Labels: enhancement, maintenance

#903 MH-13561, Access to UI Configuration
  etc/security/mh_default_org.xml
Labels: bug

#904 MH-13562, ReferenceError in Media Module
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js
Labels: bug

#908 MH-13565, Admin interface dependency update
  modules/admin-ui/package-lock.json
  modules/admin-ui/package.json
Labels: bug

#905 MH-13563, Duplicated Variables in Media Module
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js
Labels: bug

#910 MH-13566 Accept duration as either string or number in scheduling JSON
  docs/guides/developer/docs/api/events-api.md
  modules/external-api/src/main/java/org/opencastproject/external/util/SchedulingUtils.java
Labels: documentation, enhancement

#913 MH-13569 Change of PlayerRedirection variable from {{id}} to #{id}
  docs/guides/admin/docs/upgrade.md
  etc/org.opencastproject.organization-mh_default_org.cfg
  modules/engage-ui/src/main/java/org/opencastproject/engage/ui/PlayerRedirect.java
Labels: maintenance

#863 MH-13512 Improve URL signing performance
  modules/urlsigning-service-impl/src/main/java/org/opencastproject/security/urlsigning/provider/impl/AbstractUrlSigningProvider.java
  modules/urlsigning-service-impl/src/test/java/org/opencastproject/security/urlsigning/provider/impl/GenericUrlSigningProviderTest.java
Labels: enhancement, maintenance

#921 MH-13513 Officially support URL signing keys that handle multiple URL prefixes
  docs/guides/admin/docs/configuration/stream-security.md
  etc/org.opencastproject.security.urlsigning.provider.impl.GenericUrlSigningProvider.cfg
  modules/urlsigning-service-impl/src/main/java/org/opencastproject/security/urlsigning/provider/impl/AbstractUrlSigningProvider.java
  modules/urlsigning-service-impl/src/test/java/org/opencastproject/security/urlsigning/provider/impl/GenericUrlSigningProviderTest.java
Labels: feature

#906 MH-13564, Media Module Configuration
  NOTICES
  docs/guides/admin/docs/releasenotes.md
  etc/org.opencastproject.organization-mh_default_org.cfg
  etc/ui-config/mh_default_org/engage-ui/config.yml
  modules/common/src/main/resources/org/opencastproject/util/MimeTypes.xml
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js
  modules/engage-ui/src/main/resources/ui/js/lib/js-yaml.min.js
Labels: enhancement

#919 MH-13580 Fix dependencies for statistics-* and workflow-condition-parser
  modules/statistics-provider-influx/pom.xml
  modules/statistics-provider-random/pom.xml
  modules/statistics-service-api/pom.xml
  modules/statistics-service-impl/pom.xml
  modules/statistics-service-remote/pom.xml
  modules/workflow-condition-parser/pom.xml
Labels: bug, maintenance

#917 MH-13578 Remove obviously unused classes
  modules/authorization-manager/src/main/java/org/opencastproject/authorization/xacml/manager/impl/persistence/Util.java
  modules/common/src/main/java/org/opencastproject/mediapackage/MediaPackageReader.java
  modules/common/src/main/java/org/opencastproject/mediapackage/MetadataException.java
  modules/common/src/main/java/org/opencastproject/mediapackage/RedirectingMediaPackageSerializer.java
  modules/common/src/main/java/org/opencastproject/mediapackage/SubtitleStream.java
  modules/common/src/main/java/org/opencastproject/mediapackage/selector/AudioElementSelector.java
  modules/common/src/main/java/org/opencastproject/mediapackage/selector/AudioVisualElementSelector.java
  modules/common/src/main/java/org/opencastproject/mediapackage/selector/PresentationFirstSelector.java
  modules/common/src/main/java/org/opencastproject/mediapackage/selector/PresenterFirstSelector.java
  modules/common/src/main/java/org/opencastproject/mediapackage/selector/SimpleFlavorPrioritySelector.java
  modules/common/src/main/java/org/opencastproject/mediapackage/selector/StreamElementSelector.java
  modules/common/src/main/java/org/opencastproject/mediapackage/selector/TrackFlavorPrioritySelector.java
  modules/common/src/main/java/org/opencastproject/mediapackage/selector/VideoElementSelector.java
  modules/common/src/main/java/org/opencastproject/util/ChunkedFile.java
  modules/common/src/main/java/org/opencastproject/util/FileLockingTest.java
  modules/common/src/main/java/org/opencastproject/util/QueryStringBuilder.java
  modules/common/src/main/java/org/opencastproject/util/UploadProgressListener.java
  modules/common/src/main/java/org/opencastproject/util/data/Throwables.java
  modules/common/src/main/java/org/opencastproject/util/jaxb/UtcDateAdapter.java
  modules/common/src/main/java/org/opencastproject/util/persistence/OsgiPersistenceEnvUser.java
  modules/common/src/main/java/org/opencastproject/util/persistencefn/OsgiPersistenceEnvUser.java
  modules/common/src/main/java/org/opencastproject/util/query/ResultSetBase.java
  modules/common/src/test/java/org/opencastproject/mediapackage/RedirectingMediaPackageSerializerTest.java
  modules/dublincore/src/main/java/org/opencastproject/metadata/dublincore/DublinCoreValidator.java
  modules/external-api/src/main/java/org/opencastproject/external/exception/ExternalServiceException.java
  modules/external-api/src/main/java/org/opencastproject/external/exception/ListProviderException.java
  modules/external-api/src/main/java/org/opencastproject/external/util/XMLListWrapper.java
Labels: maintenance

#924 MH-13584, Jettison Dependency Management
  assemblies/karaf-features/src/main/feature/feature.xml
  modules/common/pom.xml
  modules/index-service/pom.xml
  modules/kernel/pom.xml
  modules/statistics-service-remote/pom.xml
  pom.xml
Labels: maintenance

#923 MH-13583, Introduce ESLint to Media Module
  modules/engage-ui/package-lock.json
  modules/engage-ui/package.json
  modules/engage-ui/pom.xml
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui-mobile.js
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js
  modules/engage-ui/src/main/resources/ui/js/common.js
  modules/engage-ui/src/main/resources/ui/js/redirect.js
Labels: bug, enhancement, maintenance

#872 MH-13530 Remove pseudo-mechanism for workflow definition registration
  docs/guides/admin/docs/releasenotes.md
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowService.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/endpoint/WorkflowRestService.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/CountWorkflowsTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/HoldStateTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/PauseFinalOperationTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/PauseWorkflowTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowOperationSkippingIntricateTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowOperationSkippingTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowServiceImplTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowStatisticsTest.java
  modules/workflow-service-impl/src/test/resources/workflow-definition-3.xml
  modules/workflow-service-impl/src/test/resources/workflow-definition-exception-handler.xml
  modules/workflow-service-remote/src/main/java/org/opencastproject/workflow/remote/WorkflowServiceRemoteImpl.java
Labels: api change, maintenance

#926 MH-13586 Remove unused code
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/JobEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/TasksEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ToolsEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/util/QueryPreprocessor.java
  modules/asset-manager-util/pom.xml
  modules/asset-manager-util/src/main/java/org/opencastproject/assetmanager/util/Workflows.java
  modules/authorization-manager/src/main/java/org/opencastproject/authorization/xacml/manager/endpoint/AbstractAclServiceRestEndpoint.java
  modules/authorization-manager/src/main/java/org/opencastproject/authorization/xacml/manager/impl/OsgiAclServiceFactory.java
  modules/common/src/main/java/org/opencastproject/util/JsonArr.java
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/endpoint/ComposerRestService.java
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/CompositeWorkflowOperationHandler.java
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/ProcessSmilWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/ConfigurableRetractWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/resources/OSGI-INF/operations/publish-engage.xml
  modules/distribution-workflowoperation/src/test/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandlerTest.java
  modules/dublincore/src/main/java/org/opencastproject/metadata/dublincore/MetadataField.java
  modules/dublincore/src/main/java/org/opencastproject/metadata/dublincore/OpencastMetadataCodec.java
  modules/external-api-index/pom.xml
  modules/external-api-index/src/main/java/org/opencastproject/external/index/ExternalIndex.java
  modules/external-api/src/main/java/org/opencastproject/external/common/ApiResponses.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventHttpServletRequest.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventSearchQuery.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/group/GroupIndexUtils.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/theme/ThemeIndexUtils.java
  modules/index-service/src/main/java/org/opencastproject/index/service/util/JSONUtils.java
  modules/ingest-download-service-workflowoperation/pom.xml
  modules/ingest-download-service-workflowoperation/src/main/java/org/opencastproject/workflow/handler/ingest/IngestDownloadWorkflowOperationHandler.java
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/impl/IngestServiceImpl.java
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/InboxScannerService.java
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/Ingestor.java
  modules/ingest-service-impl/src/main/resources/OSGI-INF/inbox-scanner-service.xml
  modules/ingest-service-impl/src/main/resources/OSGI-INF/ingest-service.xml
  modules/ingest-service-impl/src/test/java/org/opencastproject/ingest/impl/IngestServiceImplTest.java
  modules/oaipmh-persistence/src/main/java/org/opencastproject/oaipmh/persistence/impl/SearchResultItemImpl.java
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/server/OaiPmhServer.java
  modules/runtime-info/src/main/java/org/opencastproject/runtimeinfo/Activator.java
  modules/runtime-info/src/main/java/org/opencastproject/runtimeinfo/rest/RestDocData.java
  modules/runtime-info/src/test/java/org/opencastproject/runtimeinfo/rest/RestDocsAnnotationTest.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/endpoint/SchedulerRestService.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
  modules/schema/src/main/java/org/opencastproject/schema/OcDublinCoreUtil.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/persistence/SeriesServiceDatabaseImpl.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/solr/SeriesServiceSolrIndex.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImpl.java
  modules/smil-impl/src/main/java/org/opencastproject/smil/entity/SmilBodyImpl.java
  modules/transcription-service-ibm-watson-impl/src/main/java/org/opencastproject/transcription/ibmwatson/IBMWatsonTranscriptionService.java
  modules/transcription-service-ibm-watson-impl/src/main/java/org/opencastproject/transcription/ibmwatson/persistence/TranscriptionDatabase.java
  modules/userdirectory-sakai/src/main/java/org/opencastproject/userdirectory/sakai/SakaiUserProviderInstance.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaUserAndRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/OrganizationRoleProvider.java
  modules/videosegmenter-ffmpeg/src/main/java/org/opencastproject/videosegmenter/ffmpeg/OptimizationStep.java
  modules/videosegmenter-ffmpeg/src/main/java/org/opencastproject/videosegmenter/ffmpeg/VideoSegmenterServiceImpl.java
  modules/videosegmenter-ffmpeg/src/test/java/org/opencastproject/videosegmenter/ffmpeg/VideoSegmenterTest.java
  modules/waveform-ffmpeg/src/main/java/org/opencastproject/waveform/ffmpeg/WaveformServiceImpl.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowInstanceImpl.java
Labels: maintenance

#925 MH-13585, Media Module Dependency Management
  modules/engage-ui/package-lock.json
  modules/engage-ui/package.json
  modules/engage-ui/pom.xml
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js
  modules/engage-ui/src/main/resources/ui/js/common.js
  modules/engage-ui/src/main/resources/ui/js/lib/bootbox.js
  modules/engage-ui/src/main/resources/ui/js/lib/jquery.js
  modules/engage-ui/src/main/resources/ui/js/lib/js-yaml.min.js
  modules/engage-ui/src/main/resources/ui/js/lib/redirect.js
  modules/engage-ui/src/main/resources/ui/js/lib/require.js
  modules/engage-ui/src/main/resources/ui/js/lib/seedrandom.js
  modules/engage-ui/src/main/resources/ui/js/lib/underscore.js
Labels: maintenance

#918 MH-13579 Remove module 'dataloader'
  NOTICES
  assemblies/karaf-features/src/main/feature/feature.xml
  etc/custom.properties
  modules/dataloader/pom.xml
  modules/dataloader/src/main/java/org/opencastproject/dataloader/EventEntry.java
  modules/dataloader/src/main/java/org/opencastproject/dataloader/EventsLoader.java
  modules/dataloader/src/main/java/org/opencastproject/dataloader/UserAndSeriesLoader.java
  modules/dataloader/src/main/resources/OSGI-INF/dataloader.xml
  modules/dataloader/src/main/resources/av.mov
  modules/dataloader/src/main/resources/base_mediapackage.xml
  pom.xml
Labels: maintenance
