Repository opencast/opencast, pull requests merged in 2019-11, with the labels that each got.

#1200 Fix Crowdin Deployment
  .travis.yml
Labels: ELAN, bug

#1199 Fix Crowdin Upload
  .upload-crowdin.sh
Labels: ELAN, bug

#1203 Warn about using H2
  modules/db/src/main/java/org/opencastproject/db/Activator.java
Labels: ELAN, documentation, enhancement

#1202 Overhaul RPM Installation Guide
  docs/guides/admin/docs/installation/index.md
  docs/guides/admin/docs/installation/rpm-el7.md
  docs/guides/admin/docs/installation/rpm-el8.md
  docs/guides/admin/docs/installation/rpm-rhel-sl-centos.md
  docs/guides/admin/mkdocs.yml
Labels: ELAN, documentation

#1205 Dropping SysV-Init
  docs/scripts/service/etc-init.d-opencast
  docs/scripts/service/readme.md
Labels: ELAN

#1109 Extended statistics export
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/developer/docs/api/statistics-api.md
  etc/org.opencastproject.statistics.export.impl.StatisticsExportServiceImpl.cfg
  etc/security/mh_default_org.xml
  etc/security/security_sample_ldap.xml-example
  modules/admin-ui/pom.xml
  modules/external-api/pom.xml
  modules/external-api/src/main/java/org/opencastproject/external/common/ApiMediaType.java
  modules/external-api/src/main/java/org/opencastproject/external/common/ApiVersion.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/BaseEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/CaptureAgentsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/GroupsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SecurityEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SeriesEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/StatisticsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowDefinitionsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/util/statistics/DetailLevelUtils.java
  modules/external-api/src/main/java/org/opencastproject/external/util/statistics/QueryUtils.java
  modules/external-api/src/main/java/org/opencastproject/external/util/statistics/StatisticsProviderUtils.java
  modules/external-api/src/main/resources/OSGI-INF/external-statistics-endpoint.xml
  modules/external-api/src/test/java/org/opencastproject/external/common/ApiMediaTypeTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/BaseEndpointTest.java
  modules/statistics-export-service-api/pom.xml
  modules/statistics-export-service-api/src/main/java/org/opencastproject/statistics/export/api/DetailLevel.java
  modules/statistics-export-service-api/src/main/java/org/opencastproject/statistics/export/api/StatisticsExportService.java
  modules/statistics-export-service-api/src/main/java/org/opencastproject/statistics/export/package-info.java
  modules/statistics-export-service-impl/pom.xml
  modules/statistics-export-service-impl/src/main/java/org/opencastproject/statistics/export/impl/StatisticsExportServiceImpl.java
  modules/statistics-export-service-impl/src/main/java/org/opencastproject/statistics/export/package-info.java
  modules/statistics-export-service-impl/src/main/resources/OSGI-INF/statistics-export-service.xml
  modules/statistics-export-service/src/main/java/org/opencastproject/statistics/export/impl/StatisticsExportServiceImpl.java
  modules/statistics-export-service/src/main/java/org/opencastproject/statistics/export/package-info.java
  pom.xml
Labels: ETH, feature

#1151 MH-12821 (#1008): Better crop detect test #1085
  modules/crop-ffmpeg/src/main/java/org/opencastproject/crop/impl/CropServiceImpl.java
  modules/crop-ffmpeg/src/test/java/org/opencastproject/crop/CropServiceTest.java
Labels: enhancement

#1179 Make wowza configuration tenant-specific
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/admin/docs/modules/streaming-wowza.md
  docs/guides/admin/mkdocs.yml
  etc/custom.properties
  etc/org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.cfg
  modules/common/src/main/java/org/opencastproject/systems/OpencastConstants.java
  modules/common/src/main/java/org/opencastproject/util/LoadUtil.java
  modules/distribution-service-adaptive-streaming-wowza/src/test/java/org/opencastproject/distribution/streaming/wowza/StreamingDistributionServiceTest.java
  modules/distribution-service-api/src/main/java/org/opencastproject/distribution/api/StreamingDistributionService.java
  modules/distribution-service-streaming-remote/src/main/java/org/opencastproject/distribution/streaming/remote/StreamingDistributionServiceRemoteImpl.java
  modules/distribution-service-streaming-wowza/pom.xml
  modules/distribution-service-streaming-wowza/src/main/java/org/opencastproject/distribution/streaming/wowza/WowzaStreamingDistributionService.java
  modules/distribution-service-streaming-wowza/src/main/java/org/opencastproject/distribution/streaming/wowza/endpoint/WowzaStreamingDistributionRestService.java
  modules/distribution-service-streaming-wowza/src/main/resources/OSGI-INF/distribution-service-streaming.xml
  modules/distribution-service-streaming-wowza/src/test/java/org/opencastproject/distribution/streaming/wowza/WowzaStreamingDistributionServiceTest.java
  modules/distribution-service-streaming-wowza/src/test/resources/mediapackage.xml
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishOaiPmhWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/RetractEngageWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/resources/OSGI-INF/operations/publish-engage.xml
  modules/distribution-workflowoperation/src/main/resources/OSGI-INF/operations/publish-oaipmh.xml
  modules/distribution-workflowoperation/src/main/resources/OSGI-INF/operations/retract-engage.xml
  modules/textanalyzer-impl/pom.xml
  modules/textanalyzer-impl/src/main/java/org/opencastproject/textanalyzer/impl/TextAnalyzerServiceImpl.java
  pom.xml
Labels: ELAN, enhancement, help wanted

#1220 Make Thumbnail Optional
  etc/org.opencastproject.adminui.endpoint.ToolsEndpoint.cfg
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ToolsEndpoint.java
  modules/admin-ui/src/main/webapp/scripts/modules/events/subresources/partials/tools.html
Labels: bug

#1103 Fix PostreSQL Support
  modules/common-jpa-impl/src/main/java/org/opencastproject/serviceregistry/impl/jpa/ServiceRegistrationJpaImpl.java
  modules/db/pom.xml
  pom.xml
Labels: ELAN, bug

#1154 Show users with same mail address and name
  etc/org.opencastproject.organization-mh_default_org.cfg
  modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/groupController.js
  modules/admin-ui/src/main/webapp/scripts/shared/directives/selectBoxDirective.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/group-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/selectContainer.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/wizards/new-group.html
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/new-group/users.js
  modules/admin-ui/src/test/resources/app/GET/admin-ng/resources/USERS.INVERSE.WITH.USERNAME.json
  modules/admin-ui/src/test/resources/app/GET/admin-ng/resources/USERS.NAME.AND.USERNAME.json
  modules/admin-ui/src/test/resources/test/unit/modules/users/controllers/groupControllerSpec.js
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/UsersListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/query/ThemesListQuery.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/query/UsersListQuery.java
  modules/index-service/src/test/java/org/opencastproject/index/service/resources/list/provider/UsersListProviderTest.java
Labels: ELAN, SWITCH, enhancement

#1226 Implement StreamingDistributionService remotely
  modules/distribution-service-streaming-remote/src/main/resources/OSGI-INF/distribution-remote-streaming.xml
Labels: ELAN, bug

#1206 Temporarily Ignore Failing Test
  modules/termination-state-aws/src/test/java/org/opencastproject/terminationstate/aws/AutoScalingTerminationStateServiceTest.java
Labels: ELAN

#1207 Enable Browser Tests
  .travis.yml
Labels: ELAN

#1216 Simplify Editor URL Signing
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ToolsEndpoint.java
Labels: ELAN, maintenance

#1245 AngularJS 1.7.9 Security Update
  modules/admin-ui/bower.json
Labels: ELAN, bug, dependencies, security

#1081 MH-13718 Add modal to edit metadata of multiple events
  etc/security/mh_default_org.xml
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/main/webapp/index.html
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/editEventsMetadataController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/index.html
  modules/admin-ui/src/main/webapp/scripts/shared/directives/datetimepickerDirective.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/edit-events-metadata-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/edit-events-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/resources/eventsMetadataResource.js
  modules/admin-ui/src/main/webapp/styles/components/modals/_modal-base.scss
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/AbstractEventEndpointTest.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestEventEndpoint.java
  modules/admin-ui/src/test/resources/app/GET/admin-ng/event/events/metadata.json
  modules/admin-ui/src/test/resources/app/GET/admin-ng/event/events/metadataErrors.json
  modules/admin-ui/src/test/resources/app/GET/admin-ng/event/events/metadataErrors2.json
  modules/admin-ui/src/test/resources/app/POST/admin-ng/event/events/metadata.json
  modules/admin-ui/src/test/resources/eventsMetadata.json
  modules/admin-ui/src/test/resources/eventsMetadataUpdateErrors.json
  modules/admin-ui/src/test/resources/test/unit/modules/events/controllers/editEventsMetadataControllerSpec.js
  modules/admin-ui/src/test/resources/test/unit/shared/resources/eventsMetadataResourceSpec.js
  modules/dublincore/src/main/java/org/opencastproject/metadata/dublincore/MetadataField.java
  modules/index-service/src/test/java/org/opencastproject/index/service/catalog/adapter/MetadataFieldTest.java
  modules/index-service/src/test/resources/catalog-adapter/text/text-with-different-values.json
Labels: ELAN, feature

#1250 Drop Unused Tables
  docs/scripts/ddl/mysql5.sql
  docs/upgrade/8_to_9/mysql5.sql
Labels: ELAN

#1230 Single image video fix
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/ImageWorkflowOperationHandler.java
  modules/inspection-service-ffmpeg/src/main/java/org/opencastproject/inspection/ffmpeg/FFmpegAnalyzer.java
Labels: ELAN

#1198 Introduce ESlint for Theodul Controls Plugin
  modules/engage-theodul-plugin-controls/package-lock.json
  modules/engage-theodul-plugin-controls/package.json
  modules/engage-theodul-plugin-controls/pom.xml
  modules/engage-theodul-plugin-controls/src/main/resources/static/main.js
  modules/engage-theodul-plugin-controls/src/main/resources/static/utils.js
Labels: ELAN
