Repository opencast/opencast, pull requests merged in 2019-02, with the labels that each got.

#657 MH-13319, Update Paella Binding Dependencies
  modules/engage-paella-player/gulpfile.js
  modules/engage-paella-player/package-lock.json
  modules/engage-paella-player/package.json
Labels: maintenance

#668 MH-13329 Removing a capture agent resets the password of all Opencast users
  modules/capture-admin-service-impl/src/main/java/org/opencastproject/capture/admin/impl/CaptureAgentAdminRoleProviderImpl.java
Labels: bug

#673 MH-13338, Elasticsearch Upgrade Documentation
  docs/guides/admin/docs/upgrade.md
Labels: documentation

#654 MH-13312 Do not show outdated conflict information
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/new-event/source.js
Labels: bug

#655 MH-13315 Don't destroy Notifications service on destruction of the Notifications directive
  modules/admin-ui/src/main/webapp/scripts/shared/directives/notificationsDirective.js
Labels: bug

#401 MH-13062, Added credentials for the Ingest Service.
  etc/org.opencastproject.ingest.impl.IngestServiceImpl.cfg
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/impl/IngestServiceImpl.java
  modules/ingest-service-impl/src/test/java/org/opencastproject/ingest/impl/IngestServiceImplTest.java
Labels: feature

#672 MH-13337 Admin UI workflow status translation keys added
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
Labels: bug, needs_translation

#687 Documentation: Publish Engage Workflow OH
  docs/guides/admin/docs/workflowoperationhandlers/publish-engage-woh.md
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandler.java
Labels: documentation

#528 MH-13197, Separate Admin Interface Index
  assemblies/karaf-features/src/main/feature/feature.xml
  modules/admin-ui-index/pom.xml
  modules/admin-ui-index/src/main/java/org/opencastproject/adminui/index/AdminUISearchIndex.java
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-acl.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-assetmanager.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-comment.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-group.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-scheduler.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-series.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-theme.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-workflow.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/search-index.xml
  modules/admin-ui-index/src/test/java/org/opencastproject/adminui/index/AdminUIElasticsearchUtils.java
  modules/admin-ui-index/src/test/java/org/opencastproject/adminui/index/AdminUIEventSearchQueryTest.java
  modules/admin-ui-index/src/test/java/org/opencastproject/adminui/index/AdminUISearchIndexStub.java
  modules/admin-ui/pom.xml
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/GroupsEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/IndexEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/OsgiEventEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/SeriesEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ThemesEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ToolsEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/util/BulkUpdateUtil.java
  modules/admin-ui/src/main/resources/OSGI-INF/event_endpoint.xml
  modules/admin-ui/src/main/resources/OSGI-INF/groups_endpoint.xml
  modules/admin-ui/src/main/resources/OSGI-INF/index_endpoint.xml
  modules/admin-ui/src/main/resources/OSGI-INF/search-index.xml
  modules/admin-ui/src/main/resources/OSGI-INF/series_endpoint.xml
  modules/admin-ui/src/main/resources/OSGI-INF/themes_endpoint.xml
  modules/admin-ui/src/main/resources/OSGI-INF/tools_endpoint.xml
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/AbstractEventEndpointTest.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestEventEndpoint.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestSeriesEndpoint.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestThemesEndpoint.java
  modules/index-service/src/main/resources/OSGI-INF/list-providers/contributors.xml
  modules/index-service/src/main/resources/OSGI-INF/list-providers/events.xml
  modules/index-service/src/main/resources/OSGI-INF/list-providers/themes.xml
  pom.xml
Labels: enhancement

#539 NOJIRA: Add Ansible docs
  docs/guides/admin/docs/installation/ansible.md
  docs/guides/admin/docs/installation/debs.md
  docs/guides/admin/docs/installation/index.md
  docs/guides/admin/mkdocs.yml
Labels: documentation, enhancement

#631 MH-13289 Introduce Metadatafield Copy Constructor
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/SeriesEndpoint.java
  modules/dublincore/src/main/java/org/opencastproject/metadata/dublincore/MetadataField.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SeriesEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/util/ExternalMetadataUtils.java
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/DublinCoreMetadataUtil.java
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/MetadataUtils.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventUtils.java
  modules/index-service/src/test/java/org/opencastproject/index/service/impl/IndexServiceImplTest.java
Labels: maintenance

#630 MH-13288 Don't create incomplete metadata fields
  modules/dublincore/src/main/java/org/opencastproject/metadata/dublincore/MetadataField.java
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/DublinCoreMetadataUtil.java
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/MetadataUtils.java
  modules/index-service/src/test/java/org/opencastproject/index/service/impl/IndexServiceImplTest.java
Labels: bug, enhancement

#667 MH-13331, Fix ActiveMQ Defaults
  etc/custom.properties
  modules/message-broker-impl/src/main/java/org/opencastproject/message/broker/impl/MessageBaseFacility.java
Labels: bug

#671 MH-13336, Upgrade c3p0
  pom.xml
Labels: bug

#679 MH-13343 Load track into workspace with unique ID
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
  modules/composer-ffmpeg/src/test/java/org/opencastproject/composer/impl/ComplexCmdsEncoderEngineTest.java
  modules/composer-ffmpeg/src/test/java/org/opencastproject/composer/impl/ComposerServiceTest.java
Labels: bug, needs attention

#694 MH-13354, Asset Manager Property Performance
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestTasksEndpoint.java
  modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/AssetManager.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AbstractAssetManager.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerDecorator.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerWithSecurity.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/OsgiAssetManager.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/Database.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/PropertyDto.java
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AbstractTieredStorageAssetManagerTest.java
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AssetManagerTestBase.java
  modules/scheduler-impl/src/test/java/org/opencastproject/scheduler/impl/SchedulerServiceImplTest.java
Labels: needs attention

#707 MH-13364, Fix hidden OSGI wiring errors
  assemblies/pom.xml
  modules/asset-manager-impl/pom.xml
  modules/message-broker-api/pom.xml
  modules/publication-service-youtube-v3/pom.xml
Labels: bug

#632 MH-13290, Asset Manager Query Performance
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerWithSecurity.java
Labels: enhancement

#653 MH-13313, Properly Use ACL Merge-Mode Configuration
  modules/authorization-xacml/src/main/java/org/opencastproject/authorization/xacml/XACMLAuthorizationService.java
  modules/authorization-xacml/src/main/resources/OSGI-INF/authorization-service.xml
Labels: bug, needs attention

#622 MH-12091, Per-Tenant Capture Agent Users
  etc/org.opencastproject.userdirectory.InMemoryUserAndRoleProvider.cfg
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerWithSecurity.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/InMemoryUserAndRoleProvider.java
  modules/userdirectory/src/main/resources/OSGI-INF/user-and-role-provider-inmemory.xml
Labels: feature

#662 MH-13324, Simplify Data Loader
  etc/custom.properties
  modules/dataloader/src/main/java/org/opencastproject/dataloader/EventsLoader.java
Labels: enhancement

#659 MH-13321, Fix Series Item Serialization
  modules/message-broker-api/src/main/java/org/opencastproject/message/broker/api/series/SeriesItem.java
Labels: bug, needs attention

#660 MH-13322, Avoid . in Elasticsearch Field Names
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventIndexUtils.java
  modules/search/src/main/java/org/opencastproject/matterhorn/search/impl/SearchMetadataCollection.java
Labels: bug, needs attention

#715 MH-13369, Delete Capture Agents
  modules/admin-ui/src/main/webapp/scripts/shared/resources/captureAgentsResource.js
Labels: bug

#702 MH-13361, Fix Scheduler Item Serialization
  modules/message-broker-api/src/main/java/org/opencastproject/message/broker/api/scheduler/SchedulerItem.java
Labels: bug, needs attention

#695 MH-13347, Don't always look for orphaned properties
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/AbstractADeleteQuery.java
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AbstractAssetManagerDeleteSnapshotTest.java
Labels: needs attention

#719 MH-13373, Upgrade Admin Interface Libraries
  modules/admin-ui/package-lock.json
  modules/admin-ui/package.json
Labels: maintenance

#722 MH-13376, Fix OSGI Bindings
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-acl.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-assetmanager.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-comment.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-group.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-scheduler.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-series.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-theme.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-workflow.xml
  modules/index-service/src/main/resources/OSGI-INF/list-providers/contributors.xml
  modules/index-service/src/main/resources/OSGI-INF/list-providers/events.xml
  modules/index-service/src/main/resources/OSGI-INF/list-providers/themes.xml
Labels: bug

#720 MH-13374, Update Node.js
  modules/admin-ui/package-lock.json
  modules/engage-paella-player/package-lock.json
  pom.xml
Labels: maintenance

#575 MH-13129 More configuration options for thumbnails
  docs/guides/admin/docs/configuration/admin-ui/thumbnails.md
  etc/encoding/opencast-images.properties
  etc/org.opencastproject.adminui.cfg
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ToolsEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/AdminUIConfiguration.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/ThumbnailImpl.java
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/endpoint/ComposerRestService.java
  modules/composer-service-api/src/main/java/org/opencastproject/composer/api/ComposerService.java
  modules/composer-service-remote/src/main/java/org/opencastproject/composer/remote/ComposerServiceRemoteImpl.java
Labels: enhancement

#723 MH-13377 Fix scheduler rrule TimeZone issue
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
  modules/index-service/src/test/java/org/opencastproject/index/service/impl/IndexServiceImplTest.java
  modules/scheduler-api/src/main/java/org/opencastproject/scheduler/api/SchedulerService.java
  modules/scheduler-api/src/main/java/org/opencastproject/scheduler/api/Util.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
  modules/scheduler-impl/src/test/java/org/opencastproject/scheduler/impl/SchedulerServiceImplTest.java
  modules/scheduler-remote/src/main/java/org/opencastproject/scheduler/remote/SchedulerServiceRemoteImpl.java
Labels: bug, needs attention

#716 MH-13370, Don't configure unnecessary default credentials
  etc/org.opencastproject.ingest.impl.IngestServiceImpl.cfg
Labels: maintenance

#647 MH-13306 Clean up MetadataUtils
  modules/dublincore/src/main/java/org/opencastproject/metadata/dublincore/MetadataCollection.java
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/AbstractMetadataCollection.java
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/MetadataUtils.java
Labels: maintenance

#656 MH-13318, Update to Apache Karaf 4.2.2
  assemblies/dist-admin/pom.xml
  assemblies/dist-adminpresentation/pom.xml
  assemblies/dist-adminworker/pom.xml
  assemblies/dist-allinone/pom.xml
  assemblies/dist-develop/pom.xml
  assemblies/dist-ingest/pom.xml
  assemblies/dist-migration/pom.xml
  assemblies/dist-presentation/pom.xml
  assemblies/dist-worker/pom.xml
  assemblies/pom.xml
  assemblies/resources/startup.properties.append
  pom.xml
Labels: maintenance

#697 MH-13357 Enable being able to disable 2 confusing Admin UI metadata: "duration" & "created"
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/DublinCoreMetadataUtil.java
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/events/CommonEventCatalogUIAdapter.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventUtils.java
Labels: bug

#730 MH-13384: Remove duplicate `joda-time` dependency declaration
  modules/index-service/pom.xml
Labels: maintenance

#726 MH-13379, Simplify Mime Type Handling
  modules/common/src/main/java/org/opencastproject/mediapackage/elementbuilder/AbstractElementBuilderPlugin.java
  modules/common/src/main/java/org/opencastproject/util/MimeTypes.java
  modules/inspection-service-ffmpeg/src/main/java/org/opencastproject/inspection/ffmpeg/MediaInspector.java
Labels: maintenance

#703 MH-13362, Harmonize Admin Interface Menu Tooltips
  modules/admin-ui/src/main/webapp/scripts/shared/partials/mainNav.html
  modules/admin-ui/src/main/webapp/styles/components/_menu.scss
  modules/admin-ui/src/main/webapp/styles/main.scss
Labels: maintenance

#728 MH-13383 don't smooth the waveform in the editor
  modules/admin-ui/src/main/webapp/styles/components/video/_video-editor.scss
Labels: enhancement

#689 MH-13275 - Allows the workflow to select the audio track for composite videos
  docs/guides/admin/docs/workflowoperationhandlers/composite-woh.md
  modules/admin-ui/package-lock.json
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/endpoint/ComposerRestService.java
  modules/composer-ffmpeg/src/test/java/org/opencastproject/composer/impl/ComposerServiceTest.java
  modules/composer-service-api/src/main/java/org/opencastproject/composer/api/ComposerService.java
  modules/composer-service-remote/src/main/java/org/opencastproject/composer/remote/ComposerServiceRemoteImpl.java
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/CompositeWorkflowOperationHandler.java
  modules/composer-workflowoperation/src/test/java/org/opencastproject/workflow/handler/composer/CompositeWorkflowOperationHandlerTest.java
Labels: feature

#735 MH-13390, Quick-Filter by Presenter
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/eventsPresentersCell.html
Labels: enhancement, needs translation

#674 MH-13339, Handle Bad User Update Requests
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/UsersEndpoint.java
  modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/userController.js
Labels: bug

#678 MH-13342 Don't try to create events with empty metadata
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/new-event/metadata.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/new-event/metadataExtended.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/new-series/metadata.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/new-series/metadataExtended.js
  modules/admin-ui/src/test/resources/test/unit/shared/services/wizards/new-event/metadataSpec.js
  modules/admin-ui/src/test/resources/test/unit/shared/services/wizards/new-series/metadataSpec.js
Labels: bug

#666 MH-13328 Remove save button at top of videoeditor
  modules/admin-ui/src/main/webapp/scripts/modules/events/subresources/partials/tools.html
Labels: maintenance

#685 MH-13344 Enable AssetManager to reply NOT_MODIFIED
  modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/Asset.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AbstractAssetManager.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AbstractAssetManagerWithTieredStorage.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetImpl.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/endpoint/AbstractAssetManagerRestEndpoint.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/AssetDto.java
  modules/common/src/main/java/org/opencastproject/util/Checksum.java
Labels: feature

#732 MH-13221 Improve behaviour of single-select metadata fields
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/main/webapp/scripts/shared/directives/editableSingleSelectDirective.js
  modules/admin-ui/src/main/webapp/scripts/shared/partials/editableSingleSelect.html
  modules/admin-ui/src/test/resources/test/unit/shared/directives/editableSingleSelectDirectiveSpec.js
Labels: needs translation

#738 MH-13393, Remove leftover index resources
  modules/admin-ui/src/test/resources/index/adminui/default-mapping.json
  modules/admin-ui/src/test/resources/index/adminui/event-mapping.json
  modules/admin-ui/src/test/resources/index/adminui/group-mapping.json
  modules/admin-ui/src/test/resources/index/adminui/names.txt
  modules/admin-ui/src/test/resources/index/adminui/series-mapping.json
  modules/admin-ui/src/test/resources/index/adminui/settings.json
  modules/admin-ui/src/test/resources/index/adminui/settings.yml
  modules/admin-ui/src/test/resources/index/adminui/theme-mapping.json
  modules/admin-ui/src/test/resources/index/adminui/version-mapping.json
Labels: maintenance

#742 MH-13395 Remove unfinished feature "Dashboard"
  modules/admin-ui/src/main/webapp/img/activity.png
  modules/admin-ui/src/main/webapp/img/activity_2x.png
  modules/admin-ui/src/main/webapp/img/dashboard-on.png
  modules/admin-ui/src/main/webapp/img/dashboard-on_2x.png
  modules/admin-ui/src/main/webapp/img/dashboard.png
  modules/admin-ui/src/main/webapp/img/dashboard_2x.png
  modules/admin-ui/src/main/webapp/index.html
  modules/admin-ui/src/main/webapp/scripts/modules/dashboard/controllers/dashboardController.js
  modules/admin-ui/src/main/webapp/scripts/modules/dashboard/partials/index.html
  modules/admin-ui/src/main/webapp/styles/components/_menu.scss
  modules/admin-ui/src/main/webapp/styles/views/_dashboard.scss
  modules/admin-ui/src/main/webapp/styles/views/_views-config.scss
  modules/admin-ui/src/test/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/test/resources/test/unit/modules/dashboard/controllers/dashboardControllerSpec.js
Labels: maintenance

#745 MH-13400, Admin Index Test Cleanup
  modules/admin-ui-index/src/test/java/org/opencastproject/adminui/index/AdminUIElasticsearchUtils.java
  modules/admin-ui-index/src/test/java/org/opencastproject/adminui/index/AdminUIEventSearchQueryTest.java
  modules/admin-ui-index/src/test/java/org/opencastproject/adminui/index/AdminUISearchIndexStub.java
Labels: maintenance

#736 Revert #523: Special handling of asset manager event removal
  modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/query/ADeleteQuery.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/ADeleteQueryDecorator.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/AbstractADeleteQuery.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/DeleteQueryContribution.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
Labels: enhancement, maintenance

#741 MH-13394 Remove unfinished feature "User Blacklisting"
  etc/listproviders/pm.blacklist.reasons.person.properties
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/main/webapp/index.html
  modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/userblacklistController.js
  modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/userblacklistsController.js
  modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/usersController.js
  modules/admin-ui/src/main/webapp/scripts/modules/users/partials/index.html
  modules/admin-ui/src/main/webapp/scripts/modules/users/partials/userblacklistActionsCell.html
  modules/admin-ui/src/main/webapp/scripts/modules/users/partials/userblacklistsButtons.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/user-blacklist-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/wizards/userblacklist.html
  modules/admin-ui/src/main/webapp/scripts/shared/resources/usersResource.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/userblacklist/dates.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/userblacklist/items.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/userblacklist/reason.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/userblacklist/states.js
  modules/admin-ui/src/main/webapp/scripts/shared/services/wizards/userblacklist/summary.js
  modules/admin-ui/src/main/webapp/styles/main.scss
  modules/admin-ui/src/main/webapp/styles/views/_views-config.scss
  modules/admin-ui/src/main/webapp/styles/views/modals/_remove-blacklist-by-user-modal.scss
  modules/admin-ui/src/test/resources/app/GET/admin-ng/resources/BLACKLISTS.USERS.REASONS.json
  modules/admin-ui/src/test/resources/app/GET/admin-ng/users/admin.json
  modules/admin-ui/src/test/resources/app/GET/admin-ng/users/matterhorn_system_account.json
  modules/admin-ui/src/test/resources/app/GET/admin-ng/users/users.json
  modules/admin-ui/src/test/resources/app/GET/info/me.json
  modules/admin-ui/src/test/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/test/resources/test/e2e/users/blacklist_mocks.js
  modules/admin-ui/src/test/resources/test/e2e/users/user_blacklist_creation_page.js
  modules/admin-ui/src/test/resources/test/e2e/users/user_blacklist_creation_spec.js
  modules/admin-ui/src/test/resources/test/unit/modules/users/controllers/userblacklistControllerSpec.js
  modules/admin-ui/src/test/resources/test/unit/modules/users/controllers/userblacklistsControllerSpec.js
  modules/admin-ui/src/test/resources/test/unit/shared/resources/blacklistCountResourceSpec.js
  modules/admin-ui/src/test/resources/test/unit/shared/resources/userBlacklistsResourceSpec.js
  modules/admin-ui/src/test/resources/test/unit/shared/services/wizards/userblacklist/datesSpec.js
  modules/admin-ui/src/test/resources/test/unit/shared/services/wizards/userblacklist/itemsSpec.js
  modules/admin-ui/src/test/resources/test/unit/shared/services/wizards/userblacklist/reasonSpec.js
  modules/admin-ui/src/test/resources/test/unit/shared/services/wizards/userblacklist/statesSpec.js
  modules/admin-ui/src/test/resources/test/unit/shared/services/wizards/userblacklist/summarySpec.js
  modules/index-service/src/test/java/org/opencastproject/index/service/resources/list/impl/ListProvidersScannerTest.java
  modules/index-service/src/test/resources/ListProvidersScannerTest-AllProperties.properties
  modules/index-service/src/test/resources/ListProvidersScannerTest-EmptyListName.properties
  modules/index-service/src/test/resources/ListProvidersScannerTest-GoodProperties.properties
  modules/index-service/src/test/resources/ListProvidersScannerTest-MissingListName.properties
  modules/index-service/src/test/resources/ListProvidersScannerTest-WithOrg.properties
Labels: maintenance
