Repository opencast/opencast, pull requests merged in 2019-04, with the labels that each got.

#821 MH-13479, Filter Tesseracts Resolution Warning
  modules/textextractor-tesseract/src/main/java/org/opencastproject/textextractor/tesseract/TesseractTextExtractor.java
Labels: bug

#791 MH-13451 Improve delete-event submit button
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/delete-events-modal.html
Labels: enhancement, needs translation

#825 MH-13480 - Remove leftover service
  modules/index-service/pom.xml
  modules/index-service/src/main/resources/OSGI-INF/list-providers/email.xml
Labels: maintenance

#807 MH-13465, Prevent NullPointerException
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
Labels: bug

#829 MH-13486 Cleanup NOTICES 6.x
  NOTICES
Labels: maintenance

#833 MH-13492 Add language support for Italian
  modules/admin-ui/src/main/resources/public/org/opencastproject/adminui/languages/lang-it_IT.json
  modules/admin-ui/src/main/webapp/img/lang/it_IT.svg
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/it-IT.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsPlugin/localization/it-IT.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/localization/it-IT.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.logIn/localization/it-IT.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.transcriptionTabBarPlugin/localization/it-IT.json
  modules/engage-theodul-core/src/main/resources/ui/js/engage/core.js
  modules/engage-theodul-core/src/main/resources/ui/language/it-IT.json
  modules/engage-theodul-plugin-controls/src/main/resources/static/language/it-IT.json
  modules/engage-theodul-plugin-custom-matomo/src/main/resources/static/language/it-IT.json
  modules/engage-theodul-plugin-custom-mhConnection/src/main/resources/static/language/it-IT.json
  modules/engage-theodul-plugin-custom-notifications/src/main/resources/static/language/it-IT.json
  modules/engage-theodul-plugin-description/src/main/resources/static/language/it-IT.json
  modules/engage-theodul-plugin-tab-description/src/main/resources/static/language/it-IT.json
  modules/engage-theodul-plugin-tab-shortcuts/src/main/resources/static/language/it-IT.json
  modules/engage-theodul-plugin-tab-slidetext/src/main/resources/static/language/it-IT.json
  modules/engage-theodul-plugin-video-videojs/src/main/resources/static/language/it-IT.json
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js
  modules/engage-ui/src/main/resources/ui/language/it-IT.json
Labels: enhancement

#816 MH-13474 Change the default composer job load from 0.8 to 1.5
  modules/composer-service-api/src/main/java/org/opencastproject/composer/api/EncodingProfileImpl.java
Labels: maintenance

#818 MH-13476 Filter capture agent roles for ACLs
  modules/capture-admin-service-impl/src/main/java/org/opencastproject/capture/admin/impl/CaptureAgentAdminRoleProviderImpl.java
Labels: bug

#837 NOJIRA: Fix adaptive streaming configuration guide
  docs/guides/admin/docs/modules/adaptivestreaming-wowza.md
Labels: bug, documentation
