Repository opencast/opencast, pull requests merged in 2019-12, with the labels that each got.

#1233 Change bibliographicdate if technicaldate is changed.
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
Labels: ELAN

#1122 fixes #1069 workflow tab shows scheduling info instead of workflows
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
Labels: enhancement

#1274 Update Security Configuration
  etc/security/mh_default_org.xml
Labels: ELAN, bug

#1269 Fix processing of odd video width
  etc/encoding/fast-movies.properties
Labels: ELAN, bug

#1153 Keep generated SMIL for partial tracks
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/impl/IngestServiceImpl.java
Labels: ELAN, bug

#1246 Remove default storage_id setting from asset Manager
  docs/scripts/ddl/mysql5.sql
Labels: maintenance

#1283 Fix hourly statistics export
  modules/statistics-export-service-impl/src/main/java/org/opencastproject/statistics/export/impl/StatisticsExportServiceImpl.java
Labels: SWITCH, bug

#1286 Fix Role For Assets Quick Access
  modules/admin-ui/src/main/webapp/scripts/modules/events/partials/eventActionsCell.html
Labels: ELAN, bug

#1278 Editor Thumbnail Default
  etc/org.opencastproject.adminui.endpoint.ToolsEndpoint.cfg
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ToolsEndpoint.java
Labels: ELAN

#1271 Wrong encoding in video editor zoom box
  modules/admin-ui/src/main/webapp/scripts/shared/directives/timelineDirective.js
Labels: ELAN, bug

#1234 MH-12391 Add audio and video stream selectors for tracks to ExecuteMany WOH
  docs/guides/admin/docs/workflowoperationhandlers/execute-many-woh.md
  modules/execute-workflowoperation/src/main/java/org/opencastproject/execute/operation/handler/ExecuteManyWorkflowOperationHandler.java
Labels: UCT, feature

#1299 Fix AWS WOH OSGI dependencies
  modules/distribution-workflowoperation/src/main/resources/OSGI-INF/operations/publish-aws.xml
Labels: ELAN, bug, good first issue, needs attention
