Repository opencast/opencast, pull requests merged in 2020-10, with the labels that each got.

#1771 OSGi Annotations for Engage UI
  modules/engage-ui/pom.xml
  modules/engage-ui/src/main/java/org/opencastproject/engage/ui/PlayerRedirect.java
  modules/engage-ui/src/main/resources/OSGI-INF/player-redirect.xml
Labels: ELAN, enhancement

#1773 Ingest Service Cleanup
  modules/ingest-service-impl/pom.xml
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/endpoint/IngestRestService.java
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/impl/IngestServiceImpl.java
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/InboxScannerService.java
  modules/ingest-service-impl/src/main/resources/OSGI-INF/inbox-scanner-service.xml
  modules/ingest-service-impl/src/main/resources/OSGI-INF/ingest-service-rest.xml
  modules/ingest-service-impl/src/main/resources/OSGI-INF/ingest-service.xml
Labels: ELAN, java, maintenance

#1801 Remove Unused Servicewarnings Backend
  modules/common-jpa-impl/src/main/java/org/opencastproject/serviceregistry/impl/jpa/ServiceRegistrationJpaImpl.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/ServiceRegistry.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/ServiceRegistryInMemoryImpl.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImpl.java
Labels: ELAN

#1796 Minimal message broker impl improvement
  modules/message-broker-impl/src/main/java/org/opencastproject/message/broker/impl/MessageReceiverImpl.java
Labels: ELAN

#1890 Fix error while searching episode by browser
  modules/search-service-impl/src/main/java/org/opencastproject/search/endpoint/SearchRestService.java
Labels: bug, java

#1795 Login Autocomplete Instructions
  modules/admin-ui-frontend/app/login.html
Labels: ELAN, enhancement

#1794 Icon Cleanup
  modules/admin-ui-frontend/app/img/activity.png
  modules/admin-ui-frontend/app/img/activity_2x.png
  modules/admin-ui-frontend/app/img/calendar.png
  modules/admin-ui-frontend/app/img/calendar_2x.png
  modules/admin-ui-frontend/app/img/cog.png
  modules/admin-ui-frontend/app/img/cog_2x.png
  modules/admin-ui-frontend/app/img/configuration-on.png
  modules/admin-ui-frontend/app/img/configuration-on_2x.png
  modules/admin-ui-frontend/app/img/configuration.png
  modules/admin-ui-frontend/app/img/configuration_2x.png
  modules/admin-ui-frontend/app/img/edit-icon.png
  modules/admin-ui-frontend/app/img/edit-icon_2x.png
  modules/admin-ui-frontend/app/img/events-on.png
  modules/admin-ui-frontend/app/img/events-on_2x.png
  modules/admin-ui-frontend/app/img/events.png
  modules/admin-ui-frontend/app/img/events_2x.png
  modules/admin-ui-frontend/app/img/filter-icon.png
  modules/admin-ui-frontend/app/img/filter-icon_2x.png
  modules/admin-ui-frontend/app/img/help.png
  modules/admin-ui-frontend/app/img/help_2x.png
  modules/admin-ui-frontend/app/img/logout.png
  modules/admin-ui-frontend/app/img/logout_2x.png
  modules/admin-ui-frontend/app/img/menu-icon-on.png
  modules/admin-ui-frontend/app/img/menu-icon-on_2x.png
  modules/admin-ui-frontend/app/img/menu-icon.png
  modules/admin-ui-frontend/app/img/menu-icon_2x.png
  modules/admin-ui-frontend/app/img/play-icon-on.png
  modules/admin-ui-frontend/app/img/play-icon-on_2x.png
  modules/admin-ui-frontend/app/img/play-icon.png
  modules/admin-ui-frontend/app/img/play-icon_2x.png
  modules/admin-ui-frontend/app/img/recordings-on.png
  modules/admin-ui-frontend/app/img/recordings-on_2x.png
  modules/admin-ui-frontend/app/img/recordings.png
  modules/admin-ui-frontend/app/img/recordings_2x.png
  modules/admin-ui-frontend/app/img/servers-on.png
  modules/admin-ui-frontend/app/img/servers-on_2x.png
  modules/admin-ui-frontend/app/img/servers.png
  modules/admin-ui-frontend/app/img/servers_2x.png
  modules/admin-ui-frontend/app/img/time-icon.png
  modules/admin-ui-frontend/app/img/time-icon_2x.png
  modules/admin-ui-frontend/app/img/user-group-on.png
  modules/admin-ui-frontend/app/img/user-group-on_2x.png
  modules/admin-ui-frontend/app/img/user-group.png
  modules/admin-ui-frontend/app/img/user-group_2x.png
  modules/admin-ui-frontend/app/img/video.png
  modules/admin-ui-frontend/app/img/video_2x.png
  modules/admin-ui-frontend/app/img/youtube.png
  modules/admin-ui-frontend/app/img/youtube_2x.png
  modules/admin-ui-frontend/app/scripts/modules/events/partials/publishedCell.html
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/event-details.html
  modules/admin-ui-frontend/app/styles/components/_menu.scss
  modules/admin-ui-frontend/app/styles/components/_popover.scss
  modules/admin-ui-frontend/app/styles/components/_tables.scss
  modules/admin-ui-frontend/app/styles/views/modals/_lists.scss
Labels: ELAN, enhancement

#1874 PostgreSQL and auto-generated databases
  .travis.yml
  docs/guides/admin/docs/configuration/database.md
  docs/scripts/ddl/README.md
  docs/scripts/ddl/mysql5.sql
  etc/custom.properties
Labels: ELAN, documentation, feature

#1788 Properly parse boolean values
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderFactory.java
Labels: ELAN, bug

#1867 Update Mock Data
  modules/admin-ui-frontend/lib/staticMiddleware.js
  modules/admin-ui-frontend/test/app/GET/admin-ng/acl/roles.json
  modules/admin-ui-frontend/test/app/GET/oc-version/version.json
  modules/admin-ui-frontend/test/app/GET/sysinfo/bundles/version
Labels: ELAN, bug, javascript

#1764 LTI Context Role Prefix
  docs/guides/admin/docs/modules/ltimodule.md
  etc/org.opencastproject.security.lti.LtiLaunchAuthenticationHandler.cfg
  modules/security-lti/src/main/java/org/opencastproject/security/lti/LtiLaunchAuthenticationHandler.java
Labels: ELAN, feature, java, security

#1900 Docs: admin-ui moved to admin-ui-frontend
  docs/guides/developer/docs/modules/admin-ui/development.md
Labels: documentation

#1895 Development Runtime Dependency Containers
  docs/guides/package.json
  docs/scripts/devel-dependency-containers/docker-compose-mariadb.yml
  docs/scripts/devel-dependency-containers/docker-compose-postgresql.yml
  docs/scripts/devel-dependency-containers/docker-compose.yml
  docs/scripts/devel-dependency-containers/readme.md
Labels: ELAN, dependencies, documentation

#1772 Role Prefix in Moodle User Provider
  etc/org.opencastproject.userdirectory.moodle-default.cfg.template
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderFactory.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderInstance.java
Labels: ELAN, feature

#1823 Update Studio from 2020-06-25 to 2020-09-14
  docs/guides/admin/docs/modules/studio.md
  etc/ui-config/mh_default_org/studio/settings.json
  etc/ui-config/mh_default_org/studio/settings.toml
  modules/admin-ui-frontend/app/index.html
  modules/admin-ui-frontend/app/scripts/shared/controllers/applicationController.js
  modules/studio/pom.xml
Labels: ELAN, feature, studio

#1876 OSGi Dependency Update
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/checkstyle/maven-dependency-plugin.exceptions
  docs/guides/admin/docs/modules/searchindex/elasticsearch.md
  docs/guides/developer/docs/installation/source-linux.md
  docs/scripts/devel-dependency-containers/docker-compose-mariadb.yml
  docs/scripts/devel-dependency-containers/docker-compose-postgresql.yml
  docs/scripts/devel-dependency-containers/docker-compose.yml
  modules/search/pom.xml
  modules/solr/pom.xml
  modules/transcription-service-workflowoperation/src/main/resources/OSGI-INF/google-speech-attach-transcription.xml
  pom.xml
Labels: ELAN, dependencies

#1875 Update NodeJS
  pom.xml
Labels: ELAN, dependencies, javascript

#1866 Update to AngularJS 1.8
  modules/admin-ui-frontend/app/scripts/shared/directives/editableSingleValueDirective.js
  modules/admin-ui-frontend/app/scripts/shared/partials/editableSingleValue.html
  modules/admin-ui-frontend/app/scripts/shared/resources/eventsResource.js
  modules/admin-ui-frontend/bower.json
Labels: ELAN, dependencies, javascript

#1615 Aditive Filter for Api/events endpoint
  docs/guides/developer/docs/api/events-api.md
  modules/external-api/src/main/java/org/opencastproject/external/common/ApiMediaType.java
  modules/external-api/src/main/java/org/opencastproject/external/common/ApiVersion.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/BaseEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
  modules/external-api/src/test/java/org/opencastproject/external/common/ApiMediaTypeTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/BaseEndpointTest.java
Labels: api change, enhancement

#1886 Remove Spring's Patched JDOM
  NOTICES
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/checkstyle/maven-dependency-plugin.exceptions
  modules/publication-service-youtube-v3/pom.xml
  modules/search-service-impl/pom.xml
  pom.xml
Labels: ELAN, dependencies

#1750 HTTPS with Apache httpd
  docs/guides/admin/docs/configuration/https/apache-httpd.md
  docs/guides/admin/docs/configuration/https/index.md
  docs/guides/admin/mkdocs.yml
Labels: ELAN, documentation

#1901 OSGi Annotations and Configuration
  modules/silencedetection-impl/pom.xml
  modules/silencedetection-impl/src/main/java/org/opencastproject/silencedetection/endpoint/SilenceDetectionServiceEndpoint.java
  modules/silencedetection-impl/src/main/java/org/opencastproject/silencedetection/impl/SilenceDetectionServiceImpl.java
  modules/silencedetection-impl/src/main/resources/OSGI-INF/silence-detection-service.xml
Labels: ELAN, enhancement

#1910 Test admin frontend only once on CI
  .travis.yml
Labels: ELAN, tests

#1746 VideoGrid WOH
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/admin/docs/workflowoperationhandlers/video-grid-woh-figure-1.png
  docs/guides/admin/docs/workflowoperationhandlers/video-grid-woh-figure-2.png
  docs/guides/admin/docs/workflowoperationhandlers/video-grid-woh.md
  docs/guides/admin/mkdocs.yml
  modules/videogrid-remote/pom.xml
  modules/videogrid-remote/src/main/java/org/opencastproject/videogrid/remote/VideoGridServiceRemoteImpl.java
  modules/videogrid-remote/src/main/resources/OSGI-INF/videogrid-remote.xml
  modules/videogrid-service-api/pom.xml
  modules/videogrid-service-api/src/main/java/org/opencastproject/videogrid/api/VideoGridService.java
  modules/videogrid-service-api/src/main/java/org/opencastproject/videogrid/api/VideoGridServiceException.java
  modules/videogrid-service-impl/pom.xml
  modules/videogrid-service-impl/src/main/java/org/opencastproject/videogrid/endpoint/VideoGridServiceEndpoint.java
  modules/videogrid-service-impl/src/main/java/org/opencastproject/videogrid/impl/VideoGridServiceImpl.java
  modules/videogrid-service-impl/src/main/resources/OSGI-INF/videogrid-endpoint.xml
  modules/videogrid-service-impl/src/main/resources/OSGI-INF/videogrid.xml
  modules/videogrid-service-impl/src/test/java/org/opencastproject/videogrid/impl/VideoGridServiceImplTest.java
  modules/videogrid-workflowoperation/pom.xml
  modules/videogrid-workflowoperation/src/main/java/org/opencastproject/workflow/handler/videogrid/VideoGridWorkflowOperationHandler.java
  modules/videogrid-workflowoperation/src/main/resources/OSGI-INF/operations/videogrid.xml
  modules/videogrid-workflowoperation/src/test/java/org/opencastproject/workflow/handler/videogrid/VideoGridWorkflowOperationHandlerTest.java
  modules/videogrid-workflowoperation/src/test/resources/af3bd8bb-2cd4-4d79-8e64-8d54a96876fe.mp4
  modules/videogrid-workflowoperation/src/test/resources/smil_ingest.xml
  pom.xml
Labels: ELAN, feature

#1791 Add with acl option to series api
  docs/guides/developer/docs/api/series-api.md
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/BaseEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/CaptureAgentsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/GroupsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SecurityEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SeriesEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/StatisticsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowDefinitionsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowsEndpoint.java
Labels: ELAN, SWITCH, api change, enhancement

#1920 Fix Log Spamming
  modules/adopter-statistics-impl/src/main/java/org/opencastproject/adopter/registration/Controller.java
Labels: ELAN, bug

#1905 Automerge ESLint Updates
  .github/workflows/automerge-eslint.yml
Labels: ELAN, dependencies, tests

#1921 Fixed spelling errors and some formatting inconsistencies in docs
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/configuration/basic.md
  docs/guides/admin/docs/configuration/listproviders.md
  docs/guides/admin/docs/configuration/message-broker.md
  docs/guides/admin/docs/index.md
  docs/guides/admin/docs/installation/source-macosx.md
  docs/guides/admin/docs/workflowoperationhandlers/prepareav-woh.md
  docs/guides/admin/mkdocs.yml
Labels: ELAN, documentation

#1894 Remove references to removed modules
  NOTICES
  pom.xml
Labels: ELAN, dependencies, documentation

#1939 Update jakarta.xml.bind-api to 2.3.3
  assemblies/pom.xml
  assemblies/resources/lib/jdk9plus/jakarta.xml.bind-api-2.3.3.jar
  pom.xml
Labels: dependencies

#1836 Ensure User Roles
  modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/LdapUserProviderFactory.java
Labels: ELAN, bug

#1954 Fix Paella Player assuming track is audio-only when it's actually video and audio
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/03_oc_search_converter.js
Labels: bug, javascript

#1962 Adjust title of the select-tracks WOH documentation
  docs/guides/admin/docs/workflowoperationhandlers/select-streams-woh.md
Labels: ELAN, documentation

#1970 Update cURL Commands
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/endpoint/IngestRestService.java
Labels: ELAN, documentation

#1964 Docs: When the sidebar is hidden, the navigation links are disabled now
  docs/guides/admin/docs/javascript/extra.js
  docs/guides/developer/docs/javascript/extra.js
Labels: ELAN, bug, documentation

#2005 Synchronize merge conflict check
  .github/workflows/check-merge-conflict.yml
Labels: ELAN

#1980 Harmonize defaults of serviceregistry with config file
  etc/org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.cfg
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImpl.java
Labels: ELAN, SWITCH, enhancement, small pull request

#1891 Creating a new series doesn't send user collections anymore
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/eventController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/newSeriesController.js
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/serieController.js
Labels: ELAN, bug, javascript

#2008 Speed up preview encoding
  etc/encoding/engage-movies.properties
Labels: ELAN
