Repository opencast/opencast, pull requests merged in 2020-01, with the labels that each got.

#1321 Fix URL Parameters in Theodul Player
  modules/engage-theodul-core/src/main/resources/ui/js/engage/models/engage.js
Labels: ELAN, bug

#1325 Secure FPS For Smil Processing
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/EncoderEngine.java
Labels: ELAN, bug

#1318 Remove Custom Plugin Repositories
  pom.xml
Labels: ELAN

#1276 Don't add the internal publication of the original event twice
  modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/DuplicateEventWorkflowOperationHandler.java
Labels: ELAN

#1333 Switch to mvn.opencast.org
  pom.xml
Labels: ELAN, dependencies

#1343 [MH-13686] Fixes Admin-UI Presenter's column
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/eventsController.js
Labels: bug

#1329 Remove Spring Request Logger Configuration
  etc/security/mh_default_org.xml
Labels: ELAN, bug, documentation

#1338 Sakai User Directory Dependencies
  modules/userdirectory-sakai/pom.xml
Labels: ELAN, bug, dependencies

#1277 Fixed streaming distribution remote
  modules/distribution-service-streaming-remote/src/main/java/org/opencastproject/distribution/streaming/remote/StreamingDistributionServiceRemoteImpl.java
Labels: ELAN, SWITCH, bug

#1352 Remove unsafe option in ffmpeg command for SMIL processing
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/EncoderEngine.java
  modules/composer-ffmpeg/src/test/resources/audiovideo.mov
Labels: bug

#1353 Handle empty fields from REST docs in EventHttpServletRequest
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/EventHttpServletRequest.java
Labels: ELAN, bug

#1358 Switch To HTTPS Maven Repository
  assemblies/pom.xml
Labels: ELAN, SWITCH, bug, needs attention

#1339 Add Missing Karaf Features
  assemblies/dist-admin/pom.xml
  assemblies/dist-adminpresentation/pom.xml
  assemblies/dist-allinone/pom.xml
  assemblies/dist-develop/pom.xml
  assemblies/dist-ingest/pom.xml
  assemblies/dist-presentation/pom.xml
  assemblies/dist-worker/pom.xml
Labels: ELAN, bug, dependencies, needs attention

#1328 AngularJS Components 1.7.9
  modules/admin-ui/bower.json
Labels: ELAN, dependencies

#1326 Fix Image Extraction From Short Videos
  etc/encoding/engage-images.properties
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
Labels: ELAN, bug

#1300 Allow Root In Bower
  modules/admin-ui/pom.xml
Labels: ELAN, bug

#1340 LDAP User Directory Dependencies
  modules/userdirectory-ldap/pom.xml
Labels: ELAN, bug, dependencies

#1350 Dependency Tests
  .travis.yml
  docs/checkstyle/maven-dependency-plugin.exceptions
  modules/capture-admin-service-impl/pom.xml
  modules/capture-admin-service-impl/src/test/resources/META-INF/persistence.xml
  modules/common/pom.xml
  modules/crop-api/pom.xml
  modules/crop-ffmpeg/pom.xml
  modules/crop-remote/pom.xml
  modules/crop-workflowoperation/pom.xml
  modules/kernel/pom.xml
  modules/statistics-writer-workflowoperation/pom.xml
  modules/termination-state-api/pom.xml
  modules/termination-state-aws/pom.xml
  modules/termination-state-impl/pom.xml
  pom.xml
Labels: ELAN, tests

#1346 Adjust documentation regarding Elasticsearch setup
  docs/guides/admin/docs/configuration/basic.md
  docs/guides/admin/docs/upgrade.md
Labels: documentation

#1347 LDAP Configuration
  docs/guides/admin/docs/configuration/security.ldap.md
  etc/security/mh_default_org.xml
  etc/security/security_sample_ldap.xml-example
Labels: ELAN, documentation, enhancement

#1265 Some error operations referencing the wrong error-handler.
  etc/workflows/cleanup-publish-placeholder.xml
  etc/workflows/fast.xml
  etc/workflows/import.xml
  etc/workflows/partial-publish.xml
  etc/workflows/publish.xml
Labels: ELAN

#1375 Log the proper index name when updating the asset manager index
  modules/index-service/src/main/java/org/opencastproject/index/service/message/AssetManagerMessageReceiverImpl.java
Labels: ELAN

#1266 Allow capture agent users to read properties of series
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/persistence/SeriesServiceDatabaseImpl.java
Labels: ELAN, bug
