Repository opencast/opencast, pull requests merged in 2020-08, with the labels that each got.

#1657 Fixed the video outline in the theodul player
  modules/engage-theodul-plugin-video-videojs/src/main/resources/static/main.js
  modules/engage-theodul-plugin-video-videojs/src/main/resources/static/styles/desktop.css
Labels: ELAN, bug

#1667 Fix managed acl filter in api
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SeriesEndpoint.java
Labels: ELAN, SWITCH, api change, bug, small pr

#1744 Fix for issue 1616: User keep write permission on ACL template selection
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/eventController.js
Labels: ELAN, bug

#1720 Corrected title of user delete button
  modules/admin-ui/src/main/webapp/scripts/modules/events/controllers/eventController.js
Labels: ELAN, bug

#1713 Fixed double encoding of search-field in engage-ui
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js
Labels: ELAN, bug

#1753 Admin interface event API logs on user error
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
Labels: ELAN, bug

#1760 User interface to sort by number of publications
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventsController.js
Labels: ELAN, feature, javascript

#1758 Fix events sorted by publication
  modules/search/src/main/java/org/opencastproject/matterhorn/search/impl/AbstractElasticsearchIndex.java
Labels: ELAN, bug

#1759 Create admin user cleanup
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/AdminUserAndGroupLoader.java
Labels: ELAN

#1762 Fixed a typo in es.upv.paella.opencast.loader.md
  docs/guides/admin/docs/modules/paella.player/plugins/es.upv.paella.opencast.loader.md
Labels: ELAN, documentation

#1735 Added reloading of filters in users page
  modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/userController.js
  modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/usersController.js
  modules/admin-ui/src/main/webapp/scripts/shared/directives/tableFilterDirective.js
Labels: ELAN, bug

#1763 Fix for issue 1280: Notification of Newer Opencast Version in Admin UI
  modules/admin-ui-frontend/app/index.html
  modules/admin-ui-frontend/app/scripts/shared/services/restServiceMonitor.js
  modules/admin-ui-frontend/test/test/unit/shared/controllers/applicationControllerSpec.js
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/VersionEndpoint.java
Labels: ELAN, feature

#1786 Removed servicewarnings endpoint
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/endpoint/ServiceRegistryEndpoint.java
Labels: ELAN

#1770 Paella player should only list http(s) URLs in the download plugin
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsPlugin/mh_downloads.js
Labels: ELAN, bug
