Repository opencast/opencast, pull requests merged in 2020-07, with the labels that each got.

#1670 Python < 3.0 requirement deleted
  docs/guides/admin/docs/installation/source-macosx.md
Labels: ELAN, documentation

#1671 Python < 3.0 requirement deleted
  docs/guides/admin/docs/installation/source-linux.md
Labels: ELAN, documentation

#1640 Fix Capture Agent API REST Docs
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/endpoint/IngestRestService.java
Labels: ELAN, bug, documentation, needs attention

#1637 Fix: Multiple identical workflow IDs prevent Opencast form starting properly
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowDefinitionScanner.java
Labels: ELAN, bug

#1629 LTI User Data
  modules/security-lti/src/main/java/org/opencastproject/security/lti/LtiLaunchAuthenticationHandler.java
Labels: ELAN, enhancement, feature

#1668 Improved ffmpeg profile for extracting the last image of a video in P…
  etc/encoding/opencast-images.properties
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/PartialImportWorkflowOperationHandler.java
Labels: ELAN

#1663 Enable publish-configure to publish to streaming
  docs/guides/admin/docs/workflowoperationhandlers/publish-configure-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/retract-configure-woh.md
  etc/workflows/cleanup-publish-placeholder.xml
  etc/workflows/fast.xml
  etc/workflows/import.xml
  etc/workflows/partial-preview.xml
  etc/workflows/partial-publish.xml
  etc/workflows/studio-upload.xml
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/ConfigurablePublishWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/ConfigurableRetractWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/ConfigurableWorkflowOperationHandlerBase.java
  modules/distribution-workflowoperation/src/main/resources/OSGI-INF/operations/publish-configurable.xml
  modules/distribution-workflowoperation/src/main/resources/OSGI-INF/operations/retract-configurable.xml
  modules/distribution-workflowoperation/src/test/java/org/opencastproject/workflow/handler/distribution/ConfigurablePublishWorkflowOperationHandlerTest.java
Labels: ELAN, SWITCH, feature

#1710 Added Elasticsearch dependency to developer installation guide
  docs/guides/developer/docs/installation/source-linux.md
Labels: ELAN, documentation

#1709 Use FontAwesome Icon
  modules/admin-ui-frontend/app/img/embeddingcode-icon.png
  modules/admin-ui-frontend/app/img/embeddingcode-icon_2x.png
  modules/admin-ui-frontend/app/scripts/modules/events/partials/eventActionsCell.html
  modules/admin-ui-frontend/app/styles/components/_tables.scss
Labels: ELAN

#1700 Document bundle:watch
  docs/guides/developer/docs/development-environment.md
Labels: documentation

#1701 Window Selection Style
  modules/admin-ui-frontend/app/styles/views/modals/_embedded-code.scss
Labels: ELAN
