Repository opencast/opencast, pull requests merged in 2020-12, with the labels that each got.

#2116 Update live streaming documentation
  docs/guides/admin/docs/modules/liveschedule.md
  etc/org.opencastproject.liveschedule.impl.LiveScheduleServiceImpl.cfg
Labels: documentation

#2049 Endtime of segments fixed in the editor
  modules/admin-ui/src/main/webapp/scripts/shared/directives/segmentsDirective.js
Labels: ELAN, bug

#2110 Error Notification Style
  modules/admin-ui-frontend/app/styles/main.scss
Labels: ELAN, bug

#2169 Better Port Randomization
  modules/rest-test-environment/src/main/java/org/opencastproject/test/rest/RestServiceTestEnv.java
Labels: ELAN, bug, tests

#2102 Added link to recordings to docs landing page
  docs/guides/.infrastructure/index.html.j2
Labels: ELAN, documentation

#2154 Move governance document from website to docs
  docs/guides/developer/docs/governance.md
Labels: documentation
