Repository opencast/opencast, pull requests merged in 2020-09, with the labels that each got.

#1768 Remove Empty Test Classes
  modules/userdirectory-brightspace/pom.xml
  modules/userdirectory-brightspace/src/test/java/org/opencastproject/userdirectory/brightspace/BrightspaceUserProviderInstanceTest.java
  modules/userdirectory-moodle/pom.xml
  modules/userdirectory-moodle/src/test/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderTest.java
  modules/userdirectory-sakai/pom.xml
  modules/userdirectory-sakai/src/test/java/org/opencastproject/userdirectory/sakai/SakaiUserProviderTest.java
Labels: ELAN, java, maintenance, tests

#1252 Make JPA Generated Database Match Script Generated Database
  modules/admin-ui/src/main/java/org/opencastproject/adminui/usersettings/persistence/UserSettingDto.java
  modules/annotation-impl/src/main/java/org/opencastproject/annotation/impl/AnnotationImpl.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/AssetDto.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/PropertyDto.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/SnapshotDto.java
  modules/asset-manager-storage-aws/src/main/java/org/opencastproject/assetmanager/aws/persistence/AwsAssetMappingDto.java
  modules/authorization-manager/src/main/java/org/opencastproject/authorization/xacml/manager/impl/persistence/ManagedAclEntity.java
  modules/capture-admin-service-impl/src/main/java/org/opencastproject/capture/admin/impl/AgentImpl.java
  modules/common-jpa-impl/src/main/java/org/opencastproject/job/jpa/JpaJob.java
  modules/common-jpa-impl/src/main/java/org/opencastproject/security/impl/jpa/JpaGroup.java
  modules/common-jpa-impl/src/main/java/org/opencastproject/security/impl/jpa/JpaOrganization.java
  modules/common-jpa-impl/src/main/java/org/opencastproject/security/impl/jpa/JpaRole.java
  modules/common-jpa-impl/src/main/java/org/opencastproject/security/impl/jpa/JpaUser.java
  modules/common-jpa-impl/src/main/java/org/opencastproject/security/impl/jpa/JpaUserReference.java
  modules/common-jpa-impl/src/main/java/org/opencastproject/serviceregistry/impl/jpa/HostRegistrationJpaImpl.java
  modules/common-jpa-impl/src/main/java/org/opencastproject/serviceregistry/impl/jpa/ServiceRegistrationJpaImpl.java
  modules/event-comment/src/main/java/org/opencastproject/event/comment/persistence/EventCommentDto.java
  modules/event-comment/src/main/java/org/opencastproject/event/comment/persistence/EventCommentReplyDto.java
  modules/kernel/src/main/java/org/opencastproject/kernel/bundleinfo/BundleInfoJpa.java
  modules/oaipmh-persistence/src/main/java/org/opencastproject/oaipmh/persistence/OaiPmhElementEntity.java
  modules/oaipmh-persistence/src/main/java/org/opencastproject/oaipmh/persistence/OaiPmhEntity.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/persistence/LastModifiedDto.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/persistence/SeriesEntity.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/IncidentDto.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/IncidentTextDto.java
  modules/themes/src/main/java/org/opencastproject/themes/persistence/ThemeDto.java
  modules/transcription-service-persistence/src/main/java/org/opencastproject/transcription/persistence/TranscriptionJobControlDto.java
  modules/usertracking-impl/src/main/java/org/opencastproject/usertracking/impl/UserActionImpl.java
  modules/usertracking-impl/src/main/java/org/opencastproject/usertracking/impl/UserSessionImpl.java
Labels: ELAN, bug, enhancement

#1828 Recommend https
  docs/guides/admin/docs/configuration/basic.md
  docs/guides/admin/docs/configuration/https/opencast.only.md
Labels: ELAN, documentation

#1827 Clean up basic configuration
  docs/guides/admin/docs/configuration/basic.md
Labels: ELAN, documentation

#1831 Clarify the documentation on when new source tracks can be added
  docs/guides/admin/docs/configuration/admin-ui/asset-upload.md
Labels: ELAN, documentation

#1719 Download button in theodul player
  assemblies/karaf-features/src/main/feature/feature.xml
  etc/ui-config/mh_default_org/theodul/config.yml
  modules/engage-theodul-core/src/main/java/org/opencastproject/engage/theodul/manager/impl/EngagePluginManagerImpl.java
  modules/engage-theodul-core/src/main/resources/ui/js/engage/models/meInfo.js
  modules/engage-theodul-plugin-tab-downloads/package-lock.json
  modules/engage-theodul-plugin-tab-downloads/package.json
  modules/engage-theodul-plugin-tab-downloads/pom.xml
  modules/engage-theodul-plugin-tab-downloads/src/main/java/org/opencastproject/engage/theodul/plugin/tab/downloads/EngagePluginTabDownloads.java
  modules/engage-theodul-plugin-tab-downloads/src/main/resources/static/language/de-DE.json
  modules/engage-theodul-plugin-tab-downloads/src/main/resources/static/language/en-US.json
  modules/engage-theodul-plugin-tab-downloads/src/main/resources/static/main.js
  modules/engage-theodul-plugin-tab-downloads/src/main/resources/static/styles/desktop.css
  modules/engage-theodul-plugin-tab-downloads/src/main/resources/static/templates/desktop.html
  modules/engage-theodul-plugin-tab-downloads/src/main/resources/static/utils.js
  pom.xml
Labels: ELAN, feature

#1833 Add Merge Conflict Check
  .github/workflows/check-merge-conflict.yml
Labels: ELAN, tests

#1848 Fix capture agent dropdown menus
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/edit-events-modal.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/modals/event-details.html
  modules/admin-ui/src/main/webapp/scripts/shared/partials/wizards/new-event.html
Labels: ELAN, SWITCH, bug, javascript, needs attention

#1812 Missing ACL after asset upload
  etc/workflows/publish-uploaded-assets.xml
Labels: ELAN, bug

#1851 Fix conflict checking for scheduled events in multitenant systems
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
Labels: ELAN, SWITCH, bug, java, needs attention

#1869 Extend the documentation concerning multiple audio tracks
  docs/guides/admin/docs/modules/paella.player/plugins/es.upv.paella.opencast.loader.md
Labels: ELAN, documentation

#1789 Remove JDOM From Ingest Service
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/checkstyle/maven-dependency-plugin.exceptions
  modules/ingest-service-impl/pom.xml
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/impl/IngestServiceImpl.java
Labels: ELAN, dependencies, enhancement

#1790 Request Lowercase Usernames in Moodle
  etc/org.opencastproject.userdirectory.moodle-default.cfg.template
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderFactory.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderInstance.java
Labels: ELAN, enhancement

#1872 Fix Version Check
  modules/admin-ui-frontend/app/index.html
  modules/admin-ui-frontend/app/scripts/shared/services/restServiceMonitor.js
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
Labels: ELAN, bug, javascript, needs translation

#1887 Remove Dead OpenID Module
  modules/security-openid/pom.xml
  modules/security-openid/src/main/resources/readme.txt
  pom.xml
Labels: ELAN, bug, dependencies

#1580 TagWorkflowOperationHandler now allows wildcards in target flavor
  modules/common/src/main/java/org/opencastproject/mediapackage/MediaPackageElementFlavor.java
  modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/TagWorkflowOperationHandler.java
  modules/workflow-workflowoperation/src/test/java/org/opencastproject/workflow/handler/workflow/TagWorkflowOperationHandlerTest.java
Labels: ELAN, feature
