Repository opencast/opencast, pull requests merged in 2020-06, with the labels that each got.

#1612 Use normal file appender instead of RandomAccessFile for logging
  modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/OpencastLdapAuthoritiesPopulator.java
Labels: ELAN, bug

#1611 Fix LDAP Debug Logging
  modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/OpencastLdapAuthoritiesPopulator.java
Labels: ELAN, bug

#1605 Update Several JavaScript Libraries
  modules/admin-ui-frontend/package-lock.json
Labels: ELAN, bug, dependencies

#1549 Resolution based encoding extension: if-width-or-height-geq-
  docs/guides/admin/docs/workflowoperationhandlers/encode-woh.md
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
Labels: ELAN

#1620 Fix Formatting
  modules/security-lti/src/main/java/org/opencastproject/security/lti/LtiLaunchAuthenticationHandler.java
Labels: bug, maintenance

#1622 Fix LTI Without Persistence
  modules/security-lti/pom.xml
  modules/security-lti/src/main/java/org/opencastproject/security/lti/LtiLaunchAuthenticationHandler.java
Labels: ELAN, bug, needs attention

#1630 Fix Series in Media Module
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js
Labels: ELAN, bug

#1623 Update Node.js
  pom.xml
Labels: ELAN, dependencies, maintenance

#1641 Capture Agent Authentication Method
  docs/guides/developer/docs/modules/capture-agent/capture-agent.md
Labels: ELAN, documentation

#1659 Updating Guava version
  modules/publication-service-youtube-v3/pom.xml
  pom.xml
Labels: maintenance

#1662 Update Studio from 2020-05-20 to 2020-06-25
  modules/studio/pom.xml
Labels: ELAN, studio

#1639 Don't raise a NPE when the workflow creator was deleted
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowServiceImplTest.java
Labels: ELAN, bug
