Repository opencast/opencast, pull requests merged in 2021-08, with the labels that each got.

#2666 Fix checkstyle violations in 11 modules
  docs/checkstyle/checkstyle-suppressions.xml
  modules/authorization-xacml/src/main/java/org/opencastproject/authorization/xacml/XACMLAuthorizationService.java
  modules/authorization-xacml/src/main/java/org/opencastproject/authorization/xacml/XACMLUtils.java
  modules/authorization-xacml/src/test/java/org/opencastproject/authorization/xacml/XACMLSecurityTest.java
  modules/authorization-xacml/src/test/java/org/opencastproject/authorization/xacml/XACMLUtilsTest.java
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImpl.java
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/message/AssetManagerUpdateHandler.java
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/message/SchedulerUpdateHandler.java
  modules/live-schedule-impl/src/test/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImplTest.java
  modules/runtime-info/src/main/java/org/opencastproject/runtimeinfo/RuntimeInfo.java
  modules/runtime-info/src/test/java/org/opencastproject/runtimeinfo/rest/RestDocsAnnotationTest.java
  modules/smil-impl/src/main/java/org/opencastproject/smil/endpoint/SmilServiceRest.java
  modules/smil-impl/src/main/java/org/opencastproject/smil/impl/SmilServiceImpl.java
  modules/smil-impl/src/test/java/org/opencastproject/smil/impl/SmilServiceImplTest.java
  modules/statistics-export-service-impl/src/main/java/org/opencastproject/statistics/export/impl/StatisticsExportServiceImpl.java
  modules/statistics-provider-influx/src/main/java/org/opencastproject/statistics/provider/influx/provider/InfluxStatisticsProvider.java
  modules/statistics-provider-influx/src/main/java/org/opencastproject/statistics/provider/influx/provider/InfluxTimeSeriesStatisticsProvider.java
  modules/statistics-provider-influx/src/test/java/org/opencastproject/statistics/provider/influx/provider/InfluxStatisticsProviderTest.java
  modules/statistics-service-api/src/main/java/org/opencastproject/statistics/api/StatisticsService.java
  modules/statistics-service-api/src/main/java/org/opencastproject/statistics/api/StatisticsUtil.java
  modules/statistics-service-api/src/test/java/org/opencastproject/statistics/api/StatisticsUtilTest.java
  modules/statistics-service-impl/src/main/java/org/opencastproject/statistics/endpoint/StatisticsRestService.java
  modules/statistics-service-remote/src/main/java/org/opencastproject/statistics/remote/StatisticsServiceRemoteImpl.java
  modules/termination-state-aws/src/main/java/org/opencastproject/terminationstate/aws/AutoScalingTerminationStateService.java
  modules/termination-state-aws/src/main/java/org/opencastproject/terminationstate/endpoint/aws/AutoScalingTerminationStateRestService.java
  modules/termination-state-aws/src/test/java/org/opencastproject/terminationstate/aws/AutoScalingTerminationStateServiceTest.java
  modules/termination-state-impl/src/main/java/org/opencastproject/terminationstate/endpoint/impl/TerminationStateRestServiceImpl.java
  modules/termination-state-impl/src/main/java/org/opencastproject/terminationstate/impl/TerminationStateServiceImpl.java
Labels: codestyle

#2893 Add index changes to release notes of 10.1
  docs/guides/admin/docs/releasenotes.md
Labels: ELAN, documentation, small pull request

#2882 Silence Unknown Action Warning
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/SolrIndexManager.java
Labels: ELAN, bug

#2513 LTI Tool Updates
  .github/dependabot.yml
  modules/lti/package-lock.json
  modules/lti/package.json
  modules/lti/tsconfig.json
Labels: ELAN, dependencies, javascript

#2879 Editor Service Build
  assemblies/karaf-features/src/main/feature/feature.xml
  modules/editor-service-api/pom.xml
  modules/editor-service-api/src/main/java/org/opencastproject/editor/api/EditorRestEndpointBase.java
  modules/editor-service-endpoint-remote/pom.xml
  modules/editor-service-endpoint-remote/src/main/resources/OSGI-INF/editor_service_endpoint.xml
  modules/editor-service-endpoint/pom.xml
  modules/editor-service-endpoint/src/main/docs/editor-service-swagger.yaml
  modules/editor-service-endpoint/src/main/docs/index.html
  modules/editor-service-endpoint/src/main/resources/OSGI-INF/editor_service_endpoint.xml
  modules/editor-service-remote/pom.xml
  modules/editor-service-remote/src/main/java/org/opencastproject/editor/remote/EditorServiceRemoteEndpoint.java
  modules/editor-service-remote/src/main/java/org/opencastproject/editor/remote/EditorServiceRemoteImpl.java
  modules/editor-service-remote/src/main/resources/OSGI-INF/editor_service_remote.xml
  modules/editor-service/pom.xml
  modules/editor-service/src/main/java/org/opencastproject/editor/EditorServiceEndpoint.java
  modules/editor-service/src/main/java/org/opencastproject/editor/EditorServiceImpl.java
  modules/editor-service/src/main/resources/OSGI-INF/editor_service.xml
  pom.xml
Labels: ELAN, bug, editor

#2872 Minor Improvements to Cleanup Operation
  modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/CleanupWorkflowOperationHandler.java
Labels: bug, ELAN

#2871 No Manual Job Sorting
  modules/common-jpa-impl/src/main/java/org/opencastproject/job/jpa/JpaJob.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImpl.java
Labels: bug, ELAN

#2856 Server Job Statistics
  modules/admin-ui-frontend/app/scripts/modules/systems/controllers/serversController.js
  modules/admin-ui-frontend/app/scripts/shared/resources/serversResource.js
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui-frontend/test/app/GET/admin-ng/server/servers.json
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ServerEndpoint.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/ServerEndpointTest.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestServerEndpoint.java
  modules/admin-ui/src/test/resources/servers.json
  modules/common-jpa-impl/src/main/java/org/opencastproject/serviceregistry/impl/jpa/HostRegistrationJpaImpl.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/HostRegistration.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/HostRegistrationInMemory.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/HostStatistics.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/JaxbHostRegistration.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/ServiceRegistry.java
  modules/common/src/main/java/org/opencastproject/serviceregistry/api/ServiceRegistryInMemoryImpl.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImpl.java
Labels: bug, ELAN

#2899 Hello World Workflow Operation
  modules/hello-world-workflowoperation/pom.xml
  modules/hello-world-workflowoperation/src/main/java/org/opencastproject/workflow/handler/hello/HelloWorldWorkflowOperationHandler.java
  pom.xml
Labels: ELAN

#2826 Update Deprecated Code
  modules/common/src/main/java/org/opencastproject/job/api/JobContext.java
  modules/common/src/main/java/org/opencastproject/util/IoSupport.java
  modules/common/src/main/java/org/opencastproject/util/data/Collections.java
  modules/common/src/main/java/org/opencastproject/util/data/Creator.java
  modules/common/src/test/java/org/opencastproject/util/data/CollectionsTest.java
  modules/dublincore/src/main/java/org/opencastproject/metadata/dublincore/DublinCoreCatalog.java
  modules/dublincore/src/main/java/org/opencastproject/metadata/dublincore/DublinCoreCatalogService.java
  modules/dublincore/src/main/java/org/opencastproject/metadata/dublincore/StaticMetadataServiceDublinCoreImpl.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/SolrIndexManager.java
Labels: ELAN

#2910 Document Committers
  docs/guides/developer/.generate-list-of-committers.sh
  docs/guides/developer/docs/committer.md
Labels: documentation, ELAN

#2863 Fix Maven Plugin Multithreading Problems
  pom.xml
Labels: bug, ELAN

#2650 sort the options alphabeticaly, this makes the languages field etc more readable
  modules/lti/src/components/EditForm.tsx
Labels: small pull request

#2847 Notes in Admin UI
  etc/listproviders/event.comment.reasons.properties
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventsController.js
  modules/admin-ui-frontend/app/scripts/modules/events/partials/eventsNotesCell.html
  modules/admin-ui-frontend/app/scripts/shared/resources/commentResource.js
  modules/admin-ui-frontend/app/scripts/shared/services/tableService.js
  modules/admin-ui-frontend/app/styles/components/_tables.scss
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-de_DE.json
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui-frontend/test/app/GET/admin-ng/resources/components.json
  modules/admin-ui-frontend/test/test/unit/modules/events/controllers/eventsControllerSpec.js
  modules/admin-ui-frontend/test/test/unit/shared/controllers/tablePreferencesControllerSpec.js
Labels: feature, ELAN

#2880 Remove Unwanted Logs
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
Labels: bug, ELAN

#2913 Fix series endpoint update series method by skipping the ACL update if the parameter is empty
  modules/series-service-impl/src/main/java/org/opencastproject/series/endpoint/SeriesRestService.java
Labels: bug

#2922 Fix i18next import
  modules/lti/src/components/EditForm.tsx
Labels: bug, ELAN

#2920 Add search form input field epFrom on sort if url parameter is set
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js
Labels: bug, javascript

#2860 UI Configuration Service Configuration
  etc/custom.properties
  etc/org.opencastproject.uiconfig.UIConfigRest.cfg
  modules/user-interface-configuration/pom.xml
  modules/user-interface-configuration/src/main/java/org/opencastproject/uiconfig/UIConfigRest.java
  modules/user-interface-configuration/src/main/resources/OSGI-INF/uiconfig.xml
  modules/user-interface-configuration/src/test/java/org/opencastproject/uiconfig/UIConfigTest.java
Labels: feature, ELAN

#2912 Delete extra colon in paella description plugin's localization key
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/da-DK.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/de-DE.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/el-GR.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/en-GB.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/en-US.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/es-ES.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/fr-FR.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/gl-ES.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/he-IL.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/it-IT.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/nl-NL.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/pl-PL.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/sl-SI.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/sv-SE.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/tr-TR.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/zh-CN.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/zh-TW.json
Labels: bug, needs translation

#2881 Player Plugin Loading
  modules/engage-theodul-api/src/main/java/org/opencastproject/engage/theodul/api/AbstractEngagePlugin.java
  modules/engage-theodul-core/pom.xml
  modules/engage-theodul-core/src/main/java/org/opencastproject/engage/theodul/manager/impl/EngagePluginManagerImpl.java
  modules/engage-theodul-core/src/main/java/org/opencastproject/engage/theodul/manager/impl/EngagePluginManagerRestService.java
  modules/engage-theodul-core/src/main/java/org/opencastproject/engage/theodul/manager/impl/TheodulCoreStaticResources.java
  modules/engage-theodul-core/src/main/resources/OSGI-INF/theodul-core-static-resources.xml
  modules/engage-theodul-core/src/main/resources/OSGI-INF/theodul-pluginmanager-service-rest.xml
  modules/engage-theodul-core/src/main/resources/OSGI-INF/theodul-pluginmanager-service.xml
  modules/engage-theodul-plugin-archetype/src/main/resources/archetype-resources/src/main/resources/OSGI-INF/engage-plugin.xml
  modules/engage-theodul-plugin-controls/pom.xml
  modules/engage-theodul-plugin-controls/src/main/java/org/opencastproject/engage/theodul/plugin/controls/EngagePluginControls.java
  modules/engage-theodul-plugin-controls/src/main/resources/OSGI-INF/engage-plugin.xml
  modules/engage-theodul-plugin-custom-matomo/pom.xml
  modules/engage-theodul-plugin-custom-matomo/src/main/java/org/opencastproject/engage/theodul/plugin/custom/matomo/EngagePluginImpl.java
  modules/engage-theodul-plugin-custom-matomo/src/main/resources/OSGI-INF/engage-plugin.xml
  modules/engage-theodul-plugin-custom-mhConnection/pom.xml
  modules/engage-theodul-plugin-custom-mhConnection/src/main/java/org/opencastproject/engage/theodul/plugin/custom/mhConnection/EngagePluginCustomMhConnection.java
  modules/engage-theodul-plugin-custom-mhConnection/src/main/resources/OSGI-INF/engage-plugin.xml
  modules/engage-theodul-plugin-custom-notifications/pom.xml
  modules/engage-theodul-plugin-custom-notifications/src/main/java/org/opencastproject/engage/theodul/plugin/custom/notifications/EngagePluginCustomNotifications.java
  modules/engage-theodul-plugin-custom-notifications/src/main/resources/OSGI-INF/engage-plugin.xml
  modules/engage-theodul-plugin-description/pom.xml
  modules/engage-theodul-plugin-description/src/main/java/org/opencastproject/engage/theodul/plugin/description/EngagePluginDescription.java
  modules/engage-theodul-plugin-description/src/main/resources/OSGI-INF/engage-plugin.xml
  modules/engage-theodul-plugin-tab-description/pom.xml
  modules/engage-theodul-plugin-tab-description/src/main/java/org/opencastproject/engage/theodul/plugin/tab/description/EngagePluginTabDescription.java
  modules/engage-theodul-plugin-tab-description/src/main/resources/OSGI-INF/engage-plugin.xml
  modules/engage-theodul-plugin-tab-downloads/src/main/java/org/opencastproject/engage/theodul/plugin/tab/downloads/EngagePluginTabDownloads.java
  modules/engage-theodul-plugin-tab-shortcuts/pom.xml
  modules/engage-theodul-plugin-tab-shortcuts/src/main/java/org/opencastproject/engage/theodul/plugin/tab/shortcuts/EngagePluginTabShortcuts.java
  modules/engage-theodul-plugin-tab-shortcuts/src/main/resources/OSGI-INF/engage-plugin.xml
  modules/engage-theodul-plugin-tab-slidetext/pom.xml
  modules/engage-theodul-plugin-tab-slidetext/src/main/java/org/opencastproject/engage/theodul/plugin/tab/slidetext/EngagePluginTabSlidetext.java
  modules/engage-theodul-plugin-tab-slidetext/src/main/resources/OSGI-INF/engage-plugin.xml
  modules/engage-theodul-plugin-video-videojs/pom.xml
  modules/engage-theodul-plugin-video-videojs/src/main/java/org/opencastproject/engage/theodul/plugin/video/videojs/EngagePluginVideoVideojs.java
  modules/engage-theodul-plugin-video-videojs/src/main/resources/OSGI-INF/engage-plugin.xml
Labels: bug, ELAN

#2935 Update Editor to 2021-08-17
  etc/ui-config/mh_default_org/editor/editor-settings.toml
  modules/editor/pom.xml
Labels: bug, enhancement, ELAN, editor

#2892 Fix checkstyle violations in 6 `userdirectory*` modules
  docs/checkstyle/checkstyle-suppressions.xml
  modules/userdirectory-brightspace/src/main/java/org/opencastproject/userdirectory/brightspace/BrightspaceUserProviderFactory.java
  modules/userdirectory-brightspace/src/main/java/org/opencastproject/userdirectory/brightspace/client/BrightspaceClientImpl.java
  modules/userdirectory-brightspace/src/main/java/org/opencastproject/userdirectory/brightspace/client/api/BrightspaceUser.java
  modules/userdirectory-brightspace/src/main/java/org/opencastproject/userdirectory/brightspace/client/api/OrgUnit.java
  modules/userdirectory-brightspace/src/main/java/org/opencastproject/userdirectory/brightspace/client/api/UsersResponse.java
  modules/userdirectory-canvas/src/main/java/org/opencastproject/userdirectory/canvas/CanvasUserRoleProvider.java
  modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/LdapUserProviderFactory.java
  modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/LdapUserProviderInstance.java
  modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/OpencastLdapAuthoritiesPopulator.java
  modules/userdirectory-ldap/src/test/java/org/opencastproject/userdirectory/ldap/OpencastLdapAuthoritiesPopulatorTest.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUser.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderFactory.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleUserProviderInstance.java
  modules/userdirectory-moodle/src/main/java/org/opencastproject/userdirectory/moodle/MoodleWebServiceImpl.java
  modules/userdirectory-sakai/src/main/java/org/opencastproject/userdirectory/sakai/SakaiUserProviderFactory.java
  modules/userdirectory-sakai/src/main/java/org/opencastproject/userdirectory/sakai/SakaiUserProviderInstance.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/AdminUserAndGroupLoader.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/CustomRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/InMemoryUserAndRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaGroupRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaUserAndRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaUserReferenceProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/OrganizationRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/RoleEndpoint.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/UserAndRoleDirectoryServiceImpl.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/UserDirectoryPersistenceUtil.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/UserEndpoint.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/UserIdRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/api/GroupRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/api/UserReferenceProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/endpoint/GroupRoleEndpoint.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/endpoint/UserEndpoint.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/utils/UserDirectoryUtils.java
  modules/userdirectory/src/test/java/org/opencastproject/userdirectory/CustomRoleProviderTest.java
  modules/userdirectory/src/test/java/org/opencastproject/userdirectory/JpaUserProviderTest.java
  modules/userdirectory/src/test/java/org/opencastproject/userdirectory/UserAndRoleDirectoryServiceImplTest.java
Labels: codestyle

#2926 Add exception for extron smp351 technical catalog
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/impl/IngestServiceImpl.java
Labels: bug, ELAN

#2929 Display version updates only as warning in the admin interface
  modules/admin-ui-frontend/app/scripts/shared/services/restServiceMonitor.js
Labels: ELAN, small pull request

#2939 Document Version Warning Conditions
  modules/admin-ui-frontend/app/scripts/shared/services/restServiceMonitor.js
Labels: documentation, ELAN, javascript

#2940 Document Opencast 11 RPM Installation
  docs/guides/admin/docs/installation/rpm-el7.md
  docs/guides/admin/docs/installation/rpm-el8.md
Labels: documentation, ELAN

#2914 Metadata to ACL Operation
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/admin/docs/workflowoperationhandlers/index.md
  docs/guides/admin/docs/workflowoperationhandlers/metadata-to-acl.md
  docs/guides/admin/mkdocs.yml
  modules/metadata-to-acl-workflowoperation/pom.xml
  modules/metadata-to-acl-workflowoperation/src/main/java/org/opencastproject/workflow/handler/metadatatoacl/MetadataToAclWorkflowOperationHandler.java
  modules/metadata-to-acl-workflowoperation/src/test/java/org/opencastproject/workflow/handler/metadatatoacl/MetadataToAclWorkflowOperationHandlerTest.java
  modules/metadata-to-acl-workflowoperation/src/test/resources/dublincore.xml
  pom.xml
Labels: feature, ELAN

#2923 Fix Solr Metadata Field
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/SolrIndexManager.java
Labels: bug, needs attention, ELAN

#2941 Opencast 10.2 Release Notes
  docs/guides/admin/docs/releasenotes.md
Labels: documentation, ELAN

#2944 Fix Dependency Documentation
  docs/guides/admin/docs/installation/source-linux.md
  docs/guides/admin/docs/installation/source-macosx.md
  docs/guides/developer/docs/installation/source-linux.md
Labels: bug, documentation, ELAN

#2942 Update Nginx example regarding proxy_cookie_path
  docs/guides/admin/docs/configuration/https/nginx.md
Labels: documentation

#2952 Link Crowdin Project List
  docs/guides/.infrastructure/index.html.j2
Labels: documentation, ELAN

#2814 Add track fields `is_master_playlist` and `is_live` to external API
  docs/guides/developer/docs/api/events-api.md
  modules/external-api/src/main/java/org/opencastproject/external/common/ApiMediaType.java
  modules/external-api/src/main/java/org/opencastproject/external/common/ApiVersion.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/BaseEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/CaptureAgentsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/GroupsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SecurityEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SeriesEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/StatisticsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowDefinitionsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowsEndpoint.java
  modules/external-api/src/test/java/org/opencastproject/external/common/ApiMediaTypeTest.java
Labels: enhancement, api change, documentation
