Repository opencast/opencast, pull requests merged in 2021-06, with the labels that each got.

#2651 fix language for the captions upload, als dfxp is supported now
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
Labels: needs translation, small pull request

#2652 change translation for the video file upload from the lti tool
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/lti/src/components/EditForm.tsx
Labels: needs translation

#2653 Meta publication handling by publish-configure WOH
  docs/guides/admin/docs/workflowoperationhandlers/publish-configure-woh.md
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/ConfigurablePublishWorkflowOperationHandler.java
Labels: ELAN

#2670 Update Responsibilities of a Committer
  docs/guides/developer/docs/committer.md
Labels: ELAN, documentation

#2674 Fix `metrics-exporter` Prometheus dependency
  modules/metrics-exporter/pom.xml
Labels: ELAN

#2655 Document encode WOH's source-flavors config key
  docs/guides/admin/docs/workflowoperationhandlers/encode-woh.md
Labels: documentation

#2675 Add workflow state for standalone editor
  modules/editor-service-api/src/main/java/org/opencastproject/editor/api/EditingData.java
  modules/editor-service-api/src/test/resources/edit.json
  modules/editor-service-endpoint/src/main/docs/editor-service-swagger.yaml
  modules/editor-service/src/main/java/org/opencastproject/editor/EditorServiceImpl.java
Labels: ELAN, editor

#2676 Event status will not change after removing the workflow
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/index/event/Event.java
Labels: ELAN, bug

#2692 Admin UI editor segment list item delete button position fixed
  modules/admin-ui-frontend/app/styles/components/video/_video-editor.scss
Labels: ELAN, bug, small pull request

#2695 Fixes removing a series from an event
  modules/admin-ui-frontend/app/scripts/shared/directives/editableSingleSelectDirective.js
Labels: ELAN, bug

#2697 Admin UI theme wizard fixed (fixes #2460)
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/theme-modal.html
Labels: ELAN, bug

#2696 Fix Media Package Series ACL Update
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: ELAN, bug

#2644 Use millisecond precision in Solr date range queries (instead of secs)
  modules/common/src/main/java/org/opencastproject/util/SolrUtils.java
  modules/common/src/test/java/org/opencastproject/util/SolrUtilsTest.java
Labels: ELAN

#2667 Removed Paella Player Play Button when pausing playback
  etc/ui-config/mh_default_org/paella/config.json
  modules/engage-paella-player/gulpfile.js
Labels: ELAN

#2673 Don't list docs twice
  docs/scripts/service/opencast.service
Labels: ELAN, documentation

#2677 Move just the latest snapshot to S3
  docs/guides/admin/docs/workflowoperationhandlers/move-storage-woh.md
  modules/asset-manager-workflowoperation/pom.xml
  modules/asset-manager-workflowoperation/src/main/java/org/opencastproject/workflow/handler/assetmanager/AssetManagerStorageMoveOperationHandler.java
  modules/asset-manager-workflowoperation/src/main/resources/OSGI-INF/operations/move-storage.xml
Labels: ELAN

#2643 Set modified date to deletion date when an event is deleted
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js
  modules/engage-ui/src/main/resources/ui/template/desktop.html
  modules/search-service-api/src/main/java/org/opencastproject/search/api/SearchQuery.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/endpoint/SearchRestService.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/persistence/SearchServiceDatabaseImpl.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/SolrIndexManager.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/SolrRequester.java
  modules/search-service-impl/src/test/java/org/opencastproject/search/impl/SearchServiceImplTest.java
Labels: ELAN

#2645 Update to Elasticsearch 7.10.2
  modules/elasticsearch-impl/pom.xml
  modules/elasticsearch-index/pom.xml
Labels: ELAN, bug

#2648 Spelling Fixes
  etc/listproviders/event.comment.reasons.properties
  modules/admin-ui-frontend/app/scripts/modules/events/validators/taskStartableValidator.js
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui-frontend/test/app/GET/admin-ng/resources/components.json
  modules/admin-ui-frontend/test/app/GET/admin-ng/resources/events/filters.json
  modules/admin-ui-frontend/test/test/unit/modules/events/validators/taskStartableValidatorSpec.js
  modules/common/src/main/java/org/opencastproject/job/api/Job.java
  modules/common/src/main/java/org/opencastproject/job/api/JobBarrier.java
  modules/common/src/main/java/org/opencastproject/util/JobUtil.java
  modules/common/src/test/java/org/opencastproject/job/api/JobBarrierTest.java
  modules/elasticsearch-index/src/main/java/org/opencastproject/elasticsearch/index/event/Event.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/EventsListProvider.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImpl.java
  modules/serviceregistry/src/test/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImplTest.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: bug, needs translation

#2708 Add info about renamed enum name of search API to release notes
  docs/guides/admin/docs/releasenotes/changed-behavior/search-api-sort-enum.txt
Labels: ELAN, documentation

#2716 Fix URL to the Security Issue Process
  SECURITY.md
Labels: documentation, small pull request

#2715 Update pull request template's URL
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#2718 Closing tags for consecutive select elements
  modules/admin-ui-frontend/app/scripts/shared/partials/editableSingleValue.html
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/acl-details.html
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/edit-events-modal.html
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/event-details.html
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/series-details.html
  modules/admin-ui-frontend/app/scripts/shared/partials/wizards/new-acl.html
  modules/admin-ui-frontend/app/scripts/shared/partials/wizards/new-series.html
Labels: bug, javascript, small pull request

#2734 MH-13617 Prepare AV fix for fast workflow: add textual warning to docs
  docs/guides/developer/docs/api/workflow-api.md
  etc/workflows/fast.xml
Labels: documentation

#2691 Document Start Task Endpoint
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/TasksEndpoint.java
Labels: ELAN, documentation

#2713 Update Opencast Studio to 2021-06-11
  modules/studio/pom.xml
Labels: ELAN, studio

#2730 Use version variable in poms
  modules/elasticsearch-api/pom.xml
  modules/engage-theodul-plugin-archetype/pom.xml
  modules/transcription-service-workflowoperation/pom.xml
Labels: ELAN, dependencies, small pull request

#2714 Fix pagination in engage-ui
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js
Labels: javascript, small pull request

#2735 Clarifies debug options in setenv file
  assemblies/resources/bin/setenv
Labels: documentation

#2731 Improve debug mode documentation
  docs/guides/developer/docs/development-environment.md
Labels: documentation

#2741 Add JVM Metrics to Release Notes
  docs/guides/admin/docs/releasenotes/jvm-metrics.txt
Labels: ELAN, documentation

#2710 Recognize more input types in WF configuration
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-event/processing.js
  modules/admin-ui-frontend/test/test/unit/shared/services/wizards/new-event/proccessingSpec.js
Labels: bug, javascript, small pull request

#2717 Make Series Endpoint Accept Metadata Fields
  modules/series-service-impl/pom.xml
  modules/series-service-impl/src/main/java/org/opencastproject/series/endpoint/SeriesRestService.java
Labels: ELAN, enhancement

#2722 Default for Access Control Entry Allow
  modules/common/src/main/java/org/opencastproject/security/api/AccessControlParser.java
Labels: ELAN, enhancement

#2749 Use HTTPS in Documentation Landing Page
  docs/guides/.infrastructure/index.html.j2
Labels: ELAN, documentation

#2761 Prevent Users From Modifying ICLA Workflow
  .github/workflows/check-icla.yml
Labels: ELAN, security, tests

#2720 Fixed admin interface tests in certain timezones
  modules/admin-ui-frontend/test/test/unit/shared/directives/tableFilterDirectiveSpec.js
Labels: ELAN, bug, needs attention, tests

#2747 Fix `jakarta.mail` Dependency Problem
  assemblies/karaf-features/src/main/feature/feature.xml
  pom.xml
Labels: ELAN, bug

#2740 Fix Log Statements
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImpl.java
Labels: ELAN, bug

#2766 Document Opencast 10 RPM Install
  docs/guides/admin/docs/installation/rpm-el7.md
  docs/guides/admin/docs/installation/rpm-el8.md
Labels: ELAN, documentation

#2767 Fix Upgrade Documentation
  docs/guides/admin/docs/upgrade.md
Labels: ELAN, documentation

#2768 Fix Upgrade Documentation
  docs/guides/admin/docs/upgrade.md
Labels: ELAN, documentation

#2723 Limit Ingest Filename Length
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/impl/IngestServiceImpl.java
Labels: ELAN, enhancement

#2736 Fix processing of `fast` events
  docs/guides/developer/docs/api/workflow-api.md
  etc/workflows/fast.xml
  etc/workflows/partial-publish.xml
  etc/workflows/publish-after-cutting.xml
Labels: ELAN, bug

#2706 Add Integration Tests
  .github/workflows/test-opencast-build.yml
Labels: ELAN, tests

#2721 Update Admin Interface Dependencies
  modules/admin-ui-frontend/bower.json
Labels: ELAN, dependencies

#2724 Remove Usertracking from Worker
  assemblies/karaf-features/src/main/feature/feature.xml
Labels: ELAN, bug

#2748 Simplify Publication Check
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandler.java
Labels: ELAN, enhancement, java

#2764 Remove Unused Dependency on Series Service
  modules/authorization-xacml/pom.xml
  modules/authorization-xacml/src/main/java/org/opencastproject/authorization/xacml/XACMLAuthorizationService.java
Labels: ELAN, bug

#2765 Fix Wowza Streaming Misconfiguration
  etc/org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.cfg
  modules/distribution-service-streaming-wowza/src/main/java/org/opencastproject/distribution/streaming/wowza/WowzaStreamingDistributionService.java
Labels: ELAN, bug, needs attention

#2698 Improved Error Handling
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/SeriesServiceImpl.java
Labels: ELAN, java

#2770 Link Video in Installation Guide
  docs/guides/admin/docs/installation/rpm-el8.md
Labels: ELAN, documentation

#2762 Small additions and improvements in search service (for the upcoming Tobira module)
  modules/search-service-api/src/main/java/org/opencastproject/search/api/SearchQuery.java
  modules/search-service-api/src/main/java/org/opencastproject/search/api/SearchResultItem.java
  modules/search-service-api/src/main/java/org/opencastproject/search/api/SearchResultItemImpl.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/SeriesFeedService.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/SolrRequester.java
  modules/search-service-remote/src/main/java/org/opencastproject/search/remote/SearchServiceRemoteImpl.java
Labels: ELAN

#2705 Remove OAI-PMH Harvester
  modules/oaipmh/pom.xml
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/harvester/GetRecordResponse.java
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/harvester/HarvesterException.java
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/harvester/IdentifyResponse.java
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/harvester/LastHarvested.java
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/harvester/ListRecordsResponse.java
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/harvester/MalformedResponseException.java
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/harvester/OaiPmhHarvester.java
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/harvester/OaiPmhRepositoryClient.java
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/harvester/OaiPmhResponse.java
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/harvester/RecordHandler.java
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/harvester/RequestException.java
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/matterhorn/MatterhornRecordHandler.java
  modules/oaipmh/src/main/resources/OSGI-INF/matterhorn-harvester.xml
  modules/oaipmh/src/main/resources/OSGI-INF/matterhorn-record-handler.xml
  modules/oaipmh/src/test/java/org/opencastproject/oaipmh/harvester/LastHarvestedTest.java
Labels: ELAN, maintenance

#2776 Fix Workflow Operation Documentation
  docs/guides/admin/docs/workflowoperationhandlers/index.md
  docs/guides/admin/docs/workflowoperationhandlers/partial-import-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/retract-partial-woh.md
Labels: ELAN, documentation
