Repository opencast/opencast, pull requests merged in 2021-03, with the labels that each got.

#2316 Changed PartialImportWOH to ignore smil entries for tracks that don't exist
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/PartialImportWorkflowOperationHandler.java
Labels: ELAN

#2330 Fix Search Capability in Documentation
  docs/guides/admin/mkdocs.yml
Labels: ELAN, bug, documentation

#2331 Simplify Conflict Check
  modules/scheduler-api/src/main/java/org/opencastproject/scheduler/api/Util.java
Labels: ELAN

#2277 Add Event Metrics
  docs/guides/admin/docs/modules/metrics.md
  modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/AssetManager.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AbstractAssetManager.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerDecorator.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/OsgiAssetManager.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/Database.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/SnapshotDto.java
  modules/metrics-exporter/pom.xml
  modules/metrics-exporter/src/main/java/org/opencastproject/metrics/impl/MetricsExporter.java
  modules/metrics-exporter/src/test/java/org/opencastproject/metrics/impl/MetricsExporterTest.java
Labels: ELAN

#2335 Distinguish Between Documentation and Configuration Checks
  .github/workflows/test-configuration.yml
  .github/workflows/test-documentation-build.yml
  .style-and-markdown-build.sh
  docs/checkstyle/check-config.sh
  docs/checkstyle/check-docs.sh
Labels: ELAN, tests

#2338 Fix checkstyle violations in 5 `publications-service-*` modules
  docs/checkstyle/checkstyle-suppressions.xml
  modules/publication-service-api/src/main/java/org/opencastproject/publication/api/ConfigurablePublicationService.java
  modules/publication-service-api/src/main/java/org/opencastproject/publication/api/OaiPmhPublicationService.java
  modules/publication-service-configurable/src/main/java/org/opencastproject/publication/configurable/ConfigurablePublicationServiceImpl.java
  modules/publication-service-configurable/src/main/java/org/opencastproject/publication/configurable/endpoint/ConfigurablePublicationRestService.java
  modules/publication-service-oaipmh-remote/src/main/java/org/opencastproject/publication/oaipmh/remote/OaiPmhPublicationServiceRemoteImpl.java
  modules/publication-service-oaipmh-remote/src/test/java/org/opencastproject/publication/oaipmh/endpoint/OaiPmhPublicationRestServiceTest.java
  modules/publication-service-oaipmh-remote/src/test/java/org/opencastproject/publication/oaipmh/endpoint/TestOaiPmhPublicationRestService.java
  modules/publication-service-oaipmh/src/main/java/org/opencastproject/publication/oaipmh/OaiPmhPublicationServiceImpl.java
  modules/publication-service-oaipmh/src/main/java/org/opencastproject/publication/oaipmh/endpoint/OaiPmhPublicationRestService.java
  modules/publication-service-youtube-v3/src/main/java/org/opencastproject/publication/youtube/VideoUpload.java
  modules/publication-service-youtube-v3/src/main/java/org/opencastproject/publication/youtube/YouTubeAPIVersion3ServiceImpl.java
  modules/publication-service-youtube-v3/src/main/java/org/opencastproject/publication/youtube/YouTubeKey.java
  modules/publication-service-youtube-v3/src/main/java/org/opencastproject/publication/youtube/YouTubePublicationAdapter.java
  modules/publication-service-youtube-v3/src/main/java/org/opencastproject/publication/youtube/YouTubeV3PublicationServiceImpl.java
  modules/publication-service-youtube-v3/src/main/java/org/opencastproject/publication/youtube/auth/GoogleAPICredentialRequestor.java
  modules/publication-service-youtube-v3/src/main/java/org/opencastproject/publication/youtube/auth/OAuth2CredentialFactory.java
  modules/publication-service-youtube-v3/src/main/java/org/opencastproject/publication/youtube/auth/OAuth2CredentialFactoryImpl.java
  modules/publication-service-youtube-v3/src/main/java/org/opencastproject/publication/youtube/endpoint/YouTubePublicationRestService.java
  modules/publication-service-youtube-v3/src/test/java/org/opencastproject/publication/youtube/UnitTestUtils.java
  modules/publication-service-youtube-v3/src/test/java/org/opencastproject/publication/youtube/YouTubeV3PublicationServiceImplTest.java
  modules/publication-service-youtube-v3/src/test/java/org/opencastproject/publication/youtube/auth/GoogleAPICredentialRequestorTest.java
Labels: ELAN, codestyle

#2340 Fix checkstyle violations in 5 `distribution-*` modules
  docs/checkstyle/checkstyle-suppressions.xml
  modules/distribution-service-api/src/main/java/org/opencastproject/distribution/api/DistributionService.java
  modules/distribution-service-api/src/main/java/org/opencastproject/distribution/api/DownloadDistributionService.java
  modules/distribution-service-api/src/main/java/org/opencastproject/distribution/api/StreamingDistributionService.java
  modules/distribution-service-aws-s3/src/main/java/org/opencastproject/distribution/aws/s3/AwsS3DistributionServiceImpl.java
  modules/distribution-service-aws-s3/src/main/java/org/opencastproject/distribution/aws/s3/PresignedUrlMediaPackageSerializer.java
  modules/distribution-service-aws-s3/src/main/java/org/opencastproject/distribution/aws/s3/endpoint/AwsS3DistributionRestService.java
  modules/distribution-service-aws-s3/src/test/java/org/opencastproject/distribution/aws/s3/AwsS3DistributionServiceImplTest.java
  modules/distribution-service-download/src/main/java/org/opencastproject/distribution/download/DownloadDistributionServiceImpl.java
  modules/distribution-service-download/src/main/java/org/opencastproject/distribution/download/endpoint/DownloadDistributionRestService.java
  modules/distribution-service-download/src/test/java/org/opencastproject/distribution/download/DownloadDistributionServiceImplTest.java
  modules/distribution-service-streaming-wowza/src/main/java/org/opencastproject/distribution/streaming/wowza/WowzaStreamingDistributionService.java
  modules/distribution-service-streaming-wowza/src/main/java/org/opencastproject/distribution/streaming/wowza/endpoint/WowzaStreamingDistributionRestService.java
  modules/distribution-service-streaming-wowza/src/test/java/org/opencastproject/distribution/streaming/wowza/WowzaStreamingDistributionServiceTest.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/ConfigurablePublishWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/ConfigurableWorkflowOperationHandlerBase.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PartialRetractEngageWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishOaiPmhWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishYouTubeWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/RetractEngageWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/RetractOaiPmhWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/RetractYouTubeWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/test/java/org/opencastproject/workflow/handler/distribution/ConfigurablePublishWorkflowOperationHandlerTest.java
Labels: ELAN, codestyle

#2329 Fixes Solr search failing when titles containing lots of upper case characters
  modules/series-service-impl/src/main/java/org/opencastproject/series/endpoint/SeriesRestService.java
  modules/series-service-remote/src/main/java/org/opencastproject/series/remote/SeriesServiceRemoteImpl.java
Labels: bug, java

#2353 OAI-PMH Primary Key Length
  modules/oaipmh-persistence/src/main/java/org/opencastproject/oaipmh/persistence/OaiPmhEntity.java
Labels: ELAN, bug

#2361 Handle image extraction from very short videos
  etc/encoding/engage-images.properties
  etc/encoding/feed-images.properties
Labels: ELAN, bug

#2355 Document and Test i18next in LTI Tools
  docs/guides/admin/docs/modules/ltimodule.md
  modules/lti/selenium-tests
Labels: ELAN, documentation, tests

#2343 Fix LTI Tool Value Checks
  modules/lti/src/OpencastRest.ts
Labels: ELAN, bug

#2289 Start Index Rebuild directly
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-acl.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-assetmanager.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-comment.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-group.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-scheduler.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-series.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-theme.xml
  modules/admin-ui-index/src/main/resources/OSGI-INF/message-receiver-workflow.xml
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/IndexEndpoint.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerWithMessaging.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/OsgiAssetManager.java
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AssetManagerWithMessagingTest.java
  modules/authorization-manager/src/main/java/org/opencastproject/authorization/xacml/manager/impl/OsgiAclServiceFactory.java
  modules/authorization-manager/src/main/resources/OSGI-INF/acl-service-factory.xml
  modules/common/src/main/java/org/opencastproject/util/Log.java
  modules/event-comment/pom.xml
  modules/event-comment/src/main/java/org/opencastproject/event/comment/persistence/EventCommentDatabaseServiceImpl.java
  modules/event-comment/src/main/resources/OSGI-INF/event-comment-database-service.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-acl.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-assetmanager.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-comment.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-group.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-scheduler.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-series.xml
  modules/external-api-index/src/main/resources/OSGI-INF/message-receiver-workflow.xml
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/BaseEndpoint.java
  modules/index-rebuild/pom.xml
  modules/index-rebuild/src/main/java/org/opencastproject/index/rebuild/AbstractIndexProducer.java
  modules/index-rebuild/src/main/java/org/opencastproject/index/rebuild/IndexProducer.java
  modules/index-rebuild/src/main/java/org/opencastproject/index/rebuild/IndexRebuildException.java
  modules/index-rebuild/src/main/java/org/opencastproject/index/rebuild/IndexRebuildService.java
  modules/index-service/pom.xml
  modules/index-service/src/main/java/org/opencastproject/index/service/message/BaseMessageReceiverImpl.java
  modules/message-broker-api/src/main/java/org/opencastproject/message/broker/api/index/IndexRecreateObject.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
  modules/scheduler-impl/src/main/resources/OSGI-INF/scheduler-service.xml
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/SeriesServiceImpl.java
  modules/themes/src/main/java/org/opencastproject/themes/persistence/ThemesServiceDatabaseImpl.java
  modules/themes/src/main/resources/OSGI-INF/themes-service-persistence.xml
  modules/themes/src/test/java/org/opencastproject/themes/ThemesServiceDatabaseTest.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaGroupRoleProvider.java
  modules/userdirectory/src/test/java/org/opencastproject/userdirectory/JpaGroupRoleProviderTest.java
  modules/userdirectory/src/test/java/org/opencastproject/userdirectory/endpoint/GroupRoleEndpointTest.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: ELAN, SWITCH, enhancement, java

#2260 Stand-Alone Video Editor
  assemblies/karaf-features/src/main/feature/feature.xml
  etc/org.opencastproject.editor.EditorServiceImpl.cfg
  etc/org.opencastproject.organization-mh_default_org.cfg
  etc/security/mh_default_org.xml
  etc/ui-config/mh_default_org/editor/editor-settings.toml
  etc/workflows/partial-preview.xml
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventsController.js
  modules/admin-ui-frontend/app/scripts/modules/events/partials/eventActionsCell.html
  modules/admin-ui-frontend/test/test/unit/modules/events/controllers/eventsControllerSpec.js
  modules/editor-service-api/pom.xml
  modules/editor-service-api/src/main/java/org/opencastproject/editor/api/EditingData.java
  modules/editor-service-api/src/main/java/org/opencastproject/editor/api/EditorService.java
  modules/editor-service-api/src/main/java/org/opencastproject/editor/api/EditorServiceException.java
  modules/editor-service-api/src/main/java/org/opencastproject/editor/api/ErrorStatus.java
  modules/editor-service-api/src/main/java/org/opencastproject/editor/api/SegmentData.java
  modules/editor-service-api/src/main/java/org/opencastproject/editor/api/SeriesData.java
  modules/editor-service-api/src/main/java/org/opencastproject/editor/api/TrackData.java
  modules/editor-service-api/src/main/java/org/opencastproject/editor/api/TrackSubData.java
  modules/editor-service-api/src/main/java/org/opencastproject/editor/api/WorkflowData.java
  modules/editor-service-api/src/test/java/org/opencastproject/editor/api/EditingDataTest.java
  modules/editor-service-api/src/test/resources/edit.json
  modules/editor-service-api/src/test/resources/editWithoutWorkflow.json
  modules/editor-service-endpoint/pom.xml
  modules/editor-service-endpoint/src/main/docs/editor-service-swagger.yaml
  modules/editor-service-endpoint/src/main/docs/index.html
  modules/editor-service-endpoint/src/main/java/org/opencastproject/editor/endpoint/EditorRestEndpoint.java
  modules/editor-service-endpoint/src/main/resources/OSGI-INF/editor_service_endpoint.xml
  modules/editor-service-remote/pom.xml
  modules/editor-service-remote/src/main/java/org/opencastproject/editor/remote/EditorServiceRemoteImpl.java
  modules/editor-service-remote/src/main/resources/OSGI-INF/editor_service_remote.xml
  modules/editor-service/pom.xml
  modules/editor-service/src/main/java/org/opencastproject/editor/EditorServiceImpl.java
  modules/editor-service/src/main/resources/OSGI-INF/editor_service.xml
  modules/editor-service/src/test/java/org/opencastproject/editor/EditorServiceImplTest.java
  modules/editor-service/src/test/resources/POST-editor.json
  modules/editor-service/src/test/resources/smil1.xml
  modules/editor/pom.xml
  pom.xml
Labels: ELAN

#2394 Editor Workflow Description
  etc/workflows/cleanup-publish-placeholder.xml
  etc/workflows/publish-after-cutting.xml
Labels: ELAN, documentation

#2395 Fix Hardcoded Dependency Version
  modules/editor-service-api/pom.xml
Labels: ELAN, bug, dependencies

#2396 Fix 9.x to develop merge conflicts
  modules/editor-service-api/pom.xml
  modules/editor-service-endpoint/pom.xml
  modules/editor-service-remote/pom.xml
  modules/editor-service/pom.xml
  modules/editor-service/src/main/java/org/opencastproject/editor/EditorServiceImpl.java
  modules/editor/pom.xml
Labels: ELAN, bug

#2411 Editor Documentation
  docs/guides/admin/docs/index.md
  docs/guides/admin/docs/modules/editor.md
  docs/guides/admin/docs/modules/index.md
  docs/guides/admin/mkdocs.yml
Labels: ELAN, documentation

#2413 Link new features
  docs/guides/admin/docs/releasenotes.md
Labels: ELAN, documentation

#2414 Corrected configuration files in editor documentation
  docs/guides/admin/docs/modules/editor.md
Labels: ELAN, documentation

#2409 8.x specific fixes for the markdown generation code
  .github/workflows/deploy-docs.yml
  .github/workflows/test-opencast-build.yml
  docs/guides/requirements.txt
Labels: documentation

#2415 Revert "8.x specific fixes for the markdown generation code"
  .github/workflows/deploy-docs.yml
  .github/workflows/test-opencast-build.yml
  docs/guides/requirements.txt
Labels: ELAN, bug, documentation

#2112 Fix admin interface not displaying the correct role
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventController.js
Labels: ELAN, bug

#2418 Update Test Server Builds
  .github/workflows/test-opencast-build.yml
Labels: ELAN

#2408 Bump react-scripts from 3.4.1 to 4.0.3 in /modules/lti
  modules/lti/.eslintrc.json
  modules/lti/package-lock.json
  modules/lti/package.json
  modules/lti/pom.xml
  modules/lti/src/OpencastRest.ts
  modules/lti/src/components/EditForm.tsx
  modules/lti/tsconfig.json
Labels: ELAN, dependencies

#2318 Serverless HLS leaves files open
  modules/common/src/main/java/org/opencastproject/mediapackage/AdaptivePlaylist.java
  modules/distribution-service-aws-s3/src/main/java/org/opencastproject/distribution/aws/s3/AwsS3DistributionServiceImpl.java
Labels: bug

#2332 Fix resolution scaling by removing `force_original_aspect_ratio`
  etc/encoding/adaptive-streaming-movies.properties
Labels: ELAN, bug

#2391 Perform `check-availibility` WF check with system user
  modules/distribution-service-download/src/main/java/org/opencastproject/distribution/download/DownloadDistributionServiceImpl.java
  modules/distribution-service-download/src/test/java/org/opencastproject/distribution/download/DownloadDistributionServiceImplTest.java
Labels: ELAN, bug, java

#2417 Correct Series ACLs when Recreating the Search Service Index
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/SearchServiceImpl.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/SolrIndexManager.java
Labels: ELAN, bug

#2019 Users in the admin ui filter can be reduced via regex now.
  etc/custom.properties
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ListProvidersEndpoint.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestListProvidersEndpoint.java
  modules/index-service/src/main/java/org/opencastproject/index/service/util/JSONUtils.java
  modules/index-service/src/test/java/org/opencastproject/index/service/util/JSONUtilsTest.java
  modules/index-service/src/test/resources/filters_reduced.json
Labels: ELAN, enhancement, feature

#2427 Revert "No Matrix Build on Opencast 8"
  .github/workflows/test-opencast-build.yml
Labels: ELAN

#2419 Fix checkstyle violations in 5 asset manager modules
  docs/checkstyle/checkstyle-suppressions.xml
  modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/Asset.java
  modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/AssetManager.java
  modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/Value.java
  modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/fn/Properties.java
  modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/query/ARecord.java
  modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/query/Field.java
  modules/asset-manager-api/src/test/java/org/opencastproject/assetmanager/api/AssetManagerTest.java
  modules/asset-manager-api/src/test/java/org/opencastproject/assetmanager/api/fn/PropertiesTest.java
  modules/asset-manager-api/src/test/java/org/opencastproject/assetmanager/api/test/ValueTest.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AbstractAssetManager.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AbstractAssetManagerWithTieredStorage.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetImpl.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerWithMessaging.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerWithSecurity.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/OsgiAssetManager.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/SnapshotImpl.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/TieredStorageAssetManagerJobProducer.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/TimedMediaArchiver.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/endpoint/AbstractAssetManagerRestEndpoint.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/endpoint/AbstractTieredStorageAssetManagerRestEndpoint.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/endpoint/OsgiEndpointHttpAssetProvider.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/AssetDto.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/AssetDtos.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/Database.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/PropertyDto.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/SnapshotDto.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/SnapshotDtos.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/persistence/VersionClaimDto.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/AQueryBuilderImpl.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/ARecordImpl.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/AbstractADeleteQuery.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/AbstractASelectQuery.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/AbstractPredicate.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/AbstractSnapshotField.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/JpaFns.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/PropertyFieldImpl.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/PropertyPredicates.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/query/SelectQueryContribution.java
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/storage/RemoteAssetStore.java
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AbstractAssetManagerDeletePropertyTest.java
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AbstractAssetManagerDeleteSnapshotTest.java
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AbstractAssetManagerPropertyRetrievalTest.java
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AbstractTieredStorageAssetManagerTest.java
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AssetManagerTestBase.java
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AssetManagerWithMessagingTest.java
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AssetManagerWithSecurityTest.java
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/TieredStorageAssetManagerJobProducerTest.java
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/util/TestOrganization.java
  modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/util/TestUser.java
  modules/asset-manager-storage-aws/src/main/java/org/opencastproject/assetmanager/aws/AwsAbstractArchive.java
  modules/asset-manager-storage-aws/src/main/java/org/opencastproject/assetmanager/aws/persistence/AwsAssetDatabaseImpl.java
  modules/asset-manager-storage-aws/src/main/java/org/opencastproject/assetmanager/aws/persistence/AwsAssetMappingDto.java
  modules/asset-manager-storage-aws/src/main/java/org/opencastproject/assetmanager/aws/s3/AwsS3AssetStore.java
  modules/asset-manager-storage-aws/src/test/java/org/opencastproject/assetmanager/aws/persistence/AwsAssetDatabaseImplTest.java
  modules/asset-manager-storage-aws/src/test/java/org/opencastproject/assetmanager/aws/s3/AwsS3AssetStoreTest.java
  modules/asset-manager-storage-fs/src/main/java/org/opencastproject/assetmanager/storage/impl/fs/AbstractFileSystemAssetStore.java
  modules/asset-manager-storage-fs/src/main/java/org/opencastproject/assetmanager/storage/impl/fs/OsgiFileSystemAssetStore.java
  modules/asset-manager-storage-fs/src/test/java/org/opencastproject/assetmanager/storage/impl/fs/AbstractFileSystemAssetStoreTest.java
  modules/asset-manager-workflowoperation/src/main/java/org/opencastproject/workflow/handler/assetmanager/AssetManagerSnapshotWorkflowOperationHandler.java
Labels: ELAN, codestyle

#2420 Fix checkstyle violations in `lti` and `lti-service-impl`
  docs/checkstyle/checkstyle-suppressions.xml
  modules/lti-service-impl/src/main/java/org/opencastproject/lti/service/endpoint/LtiServiceRestEndpoint.java
  modules/lti-service-impl/src/main/java/org/opencastproject/lti/service/impl/LtiServiceImpl.java
  modules/lti/src/main/java/org/opencastproject/lti/LtiServiceGuiEndpoint.java
  modules/lti/src/main/java/org/opencastproject/lti/LtiServlet.java
Labels: ELAN, codestyle

#2423 Fix checkstyle violations for 3 `series-service*` modules
  docs/checkstyle/checkstyle-suppressions.xml
  modules/series-service-api/src/main/java/org/opencastproject/series/api/SeriesQuery.java
  modules/series-service-api/src/main/java/org/opencastproject/series/api/SeriesService.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/endpoint/SeriesRestService.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/SeriesServiceImpl.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/persistence/SeriesEntity.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/persistence/SeriesServiceDatabaseImpl.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/solr/SeriesServiceSolrIndex.java
  modules/series-service-remote/src/main/java/org/opencastproject/series/remote/SeriesServiceRemoteImpl.java
Labels: ELAN, codestyle

#2424 Fix checkstyle violations in 22 modules
  docs/checkstyle/checkstyle-suppressions.xml
  modules/admin-ui-index/src/main/java/org/opencastproject/adminui/index/AdminUISearchIndex.java
  modules/admin-ui-index/src/test/java/org/opencastproject/adminui/index/AdminUIElasticsearchUtils.java
  modules/animate-impl/src/main/java/org/opencastproject/animate/impl/endpoint/AnimateServiceRestEndpoint.java
  modules/comments-workflowoperation/src/main/java/org/opencastproject/workflow/handler/comments/CommentWorkflowOperationHandler.java
  modules/comments-workflowoperation/src/test/java/org/opencastproject/workflow/handler/comments/CommentWorkflowOperationHandlerTest.java
  modules/email-template-service-impl/src/main/java/org/opencastproject/email/template/impl/EmailTemplateServiceImpl.java
  modules/email-template-service-impl/src/test/java/org/opencastproject/email/template/impl/EmailTemplateServiceImplTest.java
  modules/engage-ui/src/main/java/org/opencastproject/engage/ui/PlayerRedirect.java
  modules/hello-world-impl/src/main/java/org/opencastproject/helloworld/impl/HelloWorldServiceImpl.java
  modules/hello-world-impl/src/main/java/org/opencastproject/helloworld/impl/endpoint/HelloWorldRestEndpoint.java
  modules/inspection-service-remote/src/main/java/org/opencastproject/inspection/remote/MediaInspectionServiceRemoteImpl.java
  modules/inspection-workflowoperation/src/main/java/org/opencastproject/workflow/handler/inspection/InspectWorkflowOperationHandler.java
  modules/list-providers-service/src/main/java/org/opencastproject/list/impl/ListProvidersScanner.java
  modules/list-providers-service/src/main/java/org/opencastproject/list/impl/ListProvidersServiceImpl.java
  modules/list-providers-service/src/main/java/org/opencastproject/list/util/ListProviderUtil.java
  modules/list-providers-service/src/test/java/org/opencastproject/list/impl/ListProvidersServiceTest.java
  modules/list-providers-service/src/test/java/org/opencastproject/list/util/ListProviderUtilTest.java
  modules/logging-workflowoperation/src/main/java/org/opencastproject/workflow/handler/logging/LoggingWorkflowOperationHandler.java
  modules/metadata-api/src/main/java/org/opencastproject/metadata/api/MediapackageMetadataImpl.java
  modules/metadata-api/src/main/java/org/opencastproject/metadata/api/util/Interval.java
  modules/metadata/src/main/java/org/opencastproject/metadata/StaticMetadataServiceMediaPackageImpl.java
  modules/metrics-exporter/src/main/java/org/opencastproject/metrics/impl/MetricsExporter.java
  modules/presets/src/main/java/org/opencastproject/presets/impl/PresetProviderImpl.java
  modules/presets/src/test/java/org/opencastproject/presets/impl/PresetProviderImplTest.java
  modules/security-shibboleth/src/main/java/org/opencastproject/security/shibboleth/ShibbolethRequestHeaderAuthenticationFilter.java
  modules/shared-filesystem-utils/src/main/java/org/opencastproject/assetmanager/util/DistributionPathUtils.java
  modules/shared-filesystem-utils/src/main/java/org/opencastproject/assetmanager/util/Workflows.java
  modules/smil-workflowoperation/src/main/java/org/opencastproject/workflow/handler/smil/CutMarksToSmilWorkflowOperationHandler.java
  modules/static/src/main/java/org/opencastproject/fsresources/StaticResourceServlet.java
  modules/themes-workflowoperation/src/main/java/org/opencastproject/workflow/handler/themes/ThemeWorkflowOperationHandler.java
  modules/themes/src/main/java/org/opencastproject/themes/persistence/ThemeDto.java
  modules/themes/src/main/java/org/opencastproject/themes/persistence/ThemesServiceDatabaseImpl.java
  modules/urlsigning-service-api/src/main/java/org/opencastproject/security/urlsigning/utils/UrlSigningServiceOsgiUtil.java
  modules/waveform-remote/src/main/java/org/opencastproject/waveform/remote/WaveformServiceRemote.java
Labels: ELAN, codestyle

#2465 Exclude Dependabot from ICLA Check
  .github/workflows/check-icla.yml
Labels: ELAN, bug, tests
