Repository opencast/opencast, pull requests merged in 2021-10, with the labels that each got.

#2962 Update Editor Profile
  etc/encoding/opencast-movies.properties
Labels: ELAN

#3041 Point out memory limits
  docs/guides/admin/docs/upgrade.md
Labels: documentation

#3013 Amberscript attach WOH improvements
  docs/guides/admin/docs/workflowoperationhandlers/amberscript-attach-transcription-woh.md
  modules/transcription-service-workflowoperation/src/main/java/org/opencastproject/transcription/workflowoperation/AmberscriptAttachTranscriptionOperationHandler.java
Labels: bug, ELAN, java

#2956 Show link to annotation tool in the series LTI tool
  docs/guides/admin/docs/modules/ltimodule.md
  modules/lti/src/components/Series.tsx
  modules/lti/src/components/Welcome.tsx
Labels: enhancement, ELAN

#3040 Deactivate Parallel Builds in CI
  .github/workflows/test-opencast-build.yml
Labels: tests
