Repository opencast/opencast, pull requests merged in 2021-04, with the labels that each got.

#2437 Updated new editor with new frontend-release 2021-03-24
  docs/guides/admin/docs/releasenotes.md
  etc/ui-config/mh_default_org/editor/editor-settings.toml
  modules/editor/pom.xml
Labels: ELAN

#2471 Remove broken admin-frontend test
  modules/admin-ui-frontend/test/test/unit/shared/directives/tableFilterDirectiveSpec.js
Labels: ELAN, bug, needs attention, tests

#2473 Document Hardware Requirements
  docs/guides/admin/docs/installation/index.md
  docs/guides/admin/docs/installation/server-requirements.md
  docs/guides/admin/mkdocs.yml
Labels: ELAN, documentation

#2475 Enable Elasticsearch in docs
  docs/guides/admin/docs/installation/debs.md
Labels: has-conflicts

#2426 Bump @types/react-select from 3.0.21 to 4.0.13 in /modules/lti
  modules/lti/package-lock.json
  modules/lti/package.json
  modules/lti/src/components/EditForm.tsx
  modules/lti/src/components/Upload.tsx
Labels: dependencies

#1792 Standalone downloads Paella plugin
  etc/ui-config/mh_default_org/paella/config.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/da-DK.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/de-DE.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/el-GR.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/en-GB.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/en-US.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/es-ES.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/fr-FR.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/gl-ES.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/he-IL.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/it-IT.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/nl-NL.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/pl-PL.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/sl-SI.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/sv-SE.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/tr-TR.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/zh-CN.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/localization/zh-TW.json
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/mh_downloads.js
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsButtonPlugin/mh_downloads.less
Labels: ELAN, feature, javascript

#2464 Use a different ServiceType for the Standalone Video Editor on the presentation Node
  assemblies/karaf-features/src/main/feature/feature.xml
  modules/editor-service-endpoint-remote/pom.xml
  modules/editor-service-endpoint-remote/src/main/resources/OSGI-INF/editor_service_endpoint.xml
  pom.xml
Labels: ELAN, bug

#2472 Internal server error in workflow endpoint
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/endpoint/WorkflowRestService.java
Labels: ELAN, bug

#2479 Fix Memory Leak
  modules/common/src/main/java/org/opencastproject/util/HttpUtil.java
  modules/workspace-impl/src/main/java/org/opencastproject/workspace/impl/WorkspaceImpl.java
Labels: ELAN, bug, needs attention

#2492 Prevent NPE if mediapackage duration is null
  modules/editor-service/src/main/java/org/opencastproject/editor/EditorServiceImpl.java
Labels: ELAN, bug, java

#2494 Fix Processing of Unicode Titles
  assemblies/karaf-features/src/main/feature/feature.xml
  modules/common/src/main/java/org/opencastproject/mediapackage/XMLCatalogImpl.java
  modules/dublincore/src/main/java/org/opencastproject/metadata/dublincore/DublinCoreCatalogService.java
  modules/dublincore/src/test/java/org/opencastproject/metadata/dublincore/DublinCoreCatalogTest.java
  modules/dublincore/src/test/resources/sorting/dublincore2-2.xml
  pom.xml
Labels: ELAN, bug, java

#2467 Changed the content-type of the adopter POST request.
  modules/admin-ui-frontend/app/scripts/modules/registration/controllers/registrationController.js
  modules/admin-ui-frontend/app/scripts/shared/resources/adopterRegistrationResource.js
  modules/adopter-statistics-impl/src/main/java/org/opencastproject/adopter/registration/Controller.java
  modules/adopter-statistics-impl/src/main/java/org/opencastproject/adopter/registration/Form.java
Labels: ELAN, bug

#2498 Backport of Fixed test for daylight saving time
  modules/admin-ui/src/test/resources/test/unit/shared/directives/tableFilterDirectiveSpec.js
Labels: bug, tests

#2470 fixed admin UI - displaying roles correctly when adding a new event to a series
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-event/access.js
Labels: ELAN, bug

#2500 Make media package handle multi-byte Unicode characters
  modules/common/src/main/java/org/opencastproject/mediapackage/MediaPackageBuilderImpl.java
  modules/common/src/main/java/org/opencastproject/mediapackage/MediaPackageImpl.java
  modules/common/src/test/java/org/opencastproject/mediapackage/MediaPackageMergeTest.java
  modules/common/src/test/resources/manifest.xml
  modules/search-service-impl/src/test/java/org/opencastproject/search/impl/SearchServiceImplTest.java
Labels: ELAN, bug, java, needs attention

#2506 Fix checkstyle violation in 4 `search*` modules
  docs/checkstyle/checkstyle-suppressions.xml
  modules/search-service-api/src/main/java/org/opencastproject/feed/api/Feed.java
  modules/search-service-api/src/main/java/org/opencastproject/feed/api/FeedGenerator.java
  modules/search-service-api/src/main/java/org/opencastproject/search/api/SearchQuery.java
  modules/search-service-api/src/main/java/org/opencastproject/search/api/SearchResultImpl.java
  modules/search-service-api/src/main/java/org/opencastproject/search/api/SearchResultItemImpl.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/AbstractFeedGenerator.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/AbstractFeedService.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/AggregationFeedService.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/CustomFeedService.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/DOIExtension.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/FeedEntryImpl.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/FeedImpl.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/FeedServiceImpl.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/ITunesFeedExtension.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/RomeAtomFeed.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/RomeRssFeed.java
  modules/search-service-impl/src/main/java/org/opencastproject/feed/impl/SeriesFeedService.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/endpoint/SearchRestService.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/SearchServiceImpl.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/persistence/SearchEntity.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/persistence/SearchServiceDatabase.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/persistence/SearchServiceDatabaseImpl.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/Schema.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/SolrIndexManager.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/SolrRequester.java
  modules/search-service-impl/src/test/java/org/opencastproject/feed/impl/CategoryImplTest.java
  modules/search-service-impl/src/test/java/org/opencastproject/feed/impl/ContentImplTest.java
  modules/search-service-impl/src/test/java/org/opencastproject/feed/impl/DOIExtensionTest.java
  modules/search-service-impl/src/test/java/org/opencastproject/feed/impl/DublinCoreExtensionTest.java
  modules/search-service-impl/src/test/java/org/opencastproject/feed/impl/EnclosureImplTest.java
  modules/search-service-impl/src/test/java/org/opencastproject/feed/impl/FeedImplTest.java
  modules/search-service-remote/src/main/java/org/opencastproject/search/remote/SearchServiceRemoteImpl.java
  modules/search/src/main/java/org/opencastproject/matterhorn/search/impl/AbstractElasticsearchQueryBuilder.java
  modules/search/src/main/java/org/opencastproject/matterhorn/search/impl/AbstractSearchQuery.java
  modules/search/src/main/java/org/opencastproject/matterhorn/search/impl/ElasticsearchDocument.java
  modules/search/src/main/java/org/opencastproject/matterhorn/search/impl/IndexUtils.java
  modules/search/src/main/java/org/opencastproject/matterhorn/search/impl/SearchMetadataCollection.java
  modules/search/src/main/java/org/opencastproject/matterhorn/search/impl/SearchMetadataImpl.java
  modules/search/src/main/java/org/opencastproject/matterhorn/search/impl/SearchResultImpl.java
  modules/search/src/main/java/org/opencastproject/matterhorn/search/impl/SearchResultItemImpl.java
  modules/search/src/main/java/org/opencastproject/matterhorn/search/impl/SearchTermsImpl.java
  modules/search/src/main/java/org/opencastproject/matterhorn/search/impl/SortCriterionImpl.java
Labels: ELAN, codestyle

#2509 Fix checkstyle violations in 24 modules
  docs/checkstyle/checkstyle-suppressions.xml
  modules/engage-theodul-core/src/main/java/org/opencastproject/engage/theodul/manager/impl/EngagePluginManagerRestService.java
  modules/engage-theodul-core/src/main/java/org/opencastproject/engage/theodul/manager/impl/EngagePluginRegistrationImpl.java
  modules/engage-theodul-core/src/main/java/org/opencastproject/engage/theodul/manager/impl/EngagePluginRegistrationList.java
  modules/engage-theodul-core/src/main/java/org/opencastproject/engage/theodul/manager/impl/PluginData.java
  modules/engage-theodul-core/src/main/java/org/opencastproject/engage/theodul/manager/impl/StaticResourceClassloader.java
  modules/engage-theodul-core/src/test/java/org/opencastproject/engage/theodul/manager/impl/StaticResourceClassloaderTest.java
  modules/engage-theodul-plugin-controls/src/main/java/org/opencastproject/engage/theodul/plugin/controls/EngagePluginControls.java
  modules/engage-theodul-plugin-custom-matomo/src/main/java/org/opencastproject/engage/theodul/plugin/custom/matomo/EngagePluginImpl.java
  modules/engage-theodul-plugin-custom-mhConnection/src/main/java/org/opencastproject/engage/theodul/plugin/custom/mhConnection/EngagePluginCustomMhConnection.java
  modules/engage-theodul-plugin-custom-notifications/src/main/java/org/opencastproject/engage/theodul/plugin/custom/notifications/EngagePluginCustomNotifications.java
  modules/engage-theodul-plugin-custom-usertracking/src/main/java/org/opencastproject/engage/theodul/plugin/custom/usertracking/EngagePluginImpl.java
  modules/engage-theodul-plugin-description/src/main/java/org/opencastproject/engage/theodul/plugin/description/EngagePluginDescription.java
  modules/engage-theodul-plugin-tab-description/src/main/java/org/opencastproject/engage/theodul/plugin/tab/description/EngagePluginTabDescription.java
  modules/engage-theodul-plugin-tab-shortcuts/src/main/java/org/opencastproject/engage/theodul/plugin/tab/shortcuts/EngagePluginTabShortcuts.java
  modules/engage-theodul-plugin-tab-slidetext/src/main/java/org/opencastproject/engage/theodul/plugin/tab/slidetext/EngagePluginTabSlidetext.java
  modules/engage-theodul-plugin-timeline-statistics/src/main/java/org/opencastproject/engage/theodul/plugin/timeline/statistics/EngagePluginTimelineStatistics.java
  modules/engage-theodul-plugin-video-videojs/src/main/java/org/opencastproject/engage/theodul/plugin/video/videojs/EngagePluginVideoVideojs.java
  modules/notification-workflowoperation/src/main/java/org/opencastproject/workflow/handler/notification/EmailWorkflowOperationHandler.java
  modules/notification-workflowoperation/src/main/java/org/opencastproject/workflow/handler/notification/MediaPackagePostOperationHandler.java
  modules/notification-workflowoperation/src/test/java/org/opencastproject/workflow/handler/notification/EmailWorkflowOperationHandlerTest.java
  modules/notification-workflowoperation/src/test/java/org/opencastproject/workflow/handler/notification/MediaPackagePostOperationHandlerTest.java
  modules/security-aai/src/main/java/org/opencastproject/security/aai/ConfigurableLoginHandler.java
  modules/security-aai/src/main/java/org/opencastproject/security/aai/DynamicLoginHandler.java
  modules/silencedetection-impl/src/main/java/org/opencastproject/silencedetection/endpoint/SilenceDetectionServiceEndpoint.java
  modules/silencedetection-impl/src/main/java/org/opencastproject/silencedetection/ffmpeg/FFmpegSilenceDetector.java
  modules/silencedetection-impl/src/main/java/org/opencastproject/silencedetection/impl/SilenceDetectionServiceImpl.java
  modules/silencedetection-impl/src/test/java/org/opencastproject/silencedetection/ffmpeg/SilenceDetectorTest.java
  modules/textanalyzer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/textanalyzer/TextAnalysisWorkflowOperationHandler.java
  modules/timelinepreviews-api/src/main/java/org/opencastproject/timelinepreviews/api/TimelinePreviewsException.java
  modules/timelinepreviews-api/src/main/java/org/opencastproject/timelinepreviews/api/TimelinePreviewsService.java
  modules/timelinepreviews-ffmpeg/src/main/java/org/opencastproject/timelinepreviews/endpoint/TimelinePreviewsRestEndpoint.java
  modules/timelinepreviews-ffmpeg/src/main/java/org/opencastproject/timelinepreviews/ffmpeg/TimelinePreviewsServiceImpl.java
  modules/timelinepreviews-workflowoperation/src/main/java/org/opencastproject/workflow/handler/timelinepreviews/TimelinePreviewsWorkflowOperationHandler.java
  modules/user-interface-configuration/src/main/java/org/opencastproject/uiconfig/UIConfigRest.java
  modules/videosegmenter-ffmpeg/src/main/java/org/opencastproject/videosegmenter/ffmpeg/VideoSegmenterServiceImpl.java
  modules/videosegmenter-ffmpeg/src/main/java/org/opencastproject/videosegmenter/ffmpeg/endpoint/VideoSegmenterRestEndpoint.java
  modules/videosegmenter-ffmpeg/src/test/java/org/opencastproject/videosegmenter/ffmpeg/VideoSegmenterTest.java
  modules/waveform-ffmpeg/src/main/java/org/opencastproject/waveform/endpoint/WaveformServiceEndpoint.java
  modules/waveform-ffmpeg/src/main/java/org/opencastproject/waveform/ffmpeg/WaveformServiceImpl.java
  modules/waveform-workflowoperation/src/main/java/org/opencastproject/workflow/handler/waveform/WaveformWorkflowOperationHandler.java
  modules/workspace-impl/src/main/java/org/opencastproject/workspace/impl/WorkspaceImpl.java
  modules/workspace-impl/src/test/java/org/opencastproject/workspace/impl/FileReadDeleteTest.java
  modules/workspace-impl/src/test/java/org/opencastproject/workspace/impl/WorkspaceImplTest.java
Labels: ELAN, codestyle

#2518 Update Note About commons-lang/2.x
  assemblies/karaf-features/src/main/feature/feature.xml
Labels: ELAN, documentation

#2103 Only persist users with specific LTI role
  etc/org.opencastproject.security.lti.LtiLaunchAuthenticationHandler.cfg
  modules/security-lti/src/main/java/org/opencastproject/security/lti/LtiLaunchAuthenticationHandler.java
Labels: ELAN, enhancement

#2526 LTI Service Docs
  etc/org.opencastproject.security.lti.LtiLaunchAuthenticationHandler.cfg
Labels: ELAN, documentation

#2507 Change Paella Usertracking Default
  docs/guides/admin/docs/releasenotes/changed-behavior/paella-user-tracking.txt
  etc/ui-config/mh_default_org/paella/config.json
Labels: ELAN

#2530 macOS installation update
  docs/guides/admin/docs/installation/source-macosx.md
Labels: documentation

#2516 Fix Default Password
  docs/scripts/devel-dependency-containers/docker-compose-all-sql.yml
Labels: ELAN, bug

#2493 Fixed "No response from service" for videogrid
  modules/videogrid-remote/src/main/java/org/opencastproject/videogrid/remote/VideoGridServiceRemoteImpl.java
  modules/videogrid-service-api/src/main/java/org/opencastproject/videogrid/api/VideoGridService.java
  modules/videogrid-service-impl/src/main/java/org/opencastproject/videogrid/endpoint/VideoGridServiceEndpoint.java
  modules/videogrid-service-impl/src/main/java/org/opencastproject/videogrid/impl/VideoGridServiceImpl.java
  modules/videogrid-service-impl/src/test/java/org/opencastproject/videogrid/impl/VideoGridServiceImplTest.java
  modules/videogrid-workflowoperation/src/main/java/org/opencastproject/workflow/handler/videogrid/VideoGridWorkflowOperationHandler.java
  modules/videogrid-workflowoperation/src/test/java/org/opencastproject/workflow/handler/videogrid/VideoGridWorkflowOperationHandlerTest.java
Labels: ELAN, bug, java

#2501 Handle multiple creators in Media Module
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js
Labels: ELAN, bug, javascript

#2502 Handle multiple creators in Paella player
  modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/mh_description.js
Labels: ELAN, bug, javascript

#2536 Tesseract Option Documentation
  etc/custom.properties
Labels: ELAN, documentation

#1634 LDAP Group Mapping
  docs/guides/admin/docs/upgrade.md
  etc/org.opencastproject.userdirectory.ldap.cfg.template
  modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/LdapUserProviderFactory.java
  modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/LdapUserProviderInstance.java
  modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/OpencastLdapAuthoritiesPopulator.java
  modules/userdirectory-ldap/src/test/java/org/opencastproject/userdirectory/ldap/OpencastLdapAuthoritiesPopulatorTest.java
Labels: ELAN, feature

#2512 Add Build Date in User Interface
  modules/admin-ui-frontend/app/index.html
  modules/admin-ui-frontend/app/scripts/shared/controllers/applicationController.js
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/kernel/src/main/java/org/opencastproject/kernel/bundleinfo/BundleInfoRestEndpoint.java
Labels: ELAN, feature

#2508 Remove standard check-availability for publication
  etc/workflows/amberscript-attach-transcripts.xml
  etc/workflows/attach-watson-transcripts.xml
  etc/workflows/cleanup-publish-placeholder.xml
  etc/workflows/fast-HLS.xml
  etc/workflows/fast.xml
  etc/workflows/import.xml
  etc/workflows/partial-preview.xml
  etc/workflows/partial-publish.xml
  etc/workflows/studio-upload.xml
Labels: ELAN

#2514 Update Database Driver
  docs/scripts/devel-dependency-containers/docker-compose-all-sql.yml
  docs/scripts/devel-dependency-containers/docker-compose-mariadb.yml
  docs/scripts/devel-dependency-containers/docker-compose-postgresql.yml
  modules/db/pom.xml
  pom.xml
Labels: ELAN, dependencies, java

#2515 Update Prometheus Libraries
  .github/dependabot.yml
  modules/metrics-exporter/pom.xml
Labels: ELAN, dependencies, java

#2517 Java Library Update
  pom.xml
Labels: ELAN, dependencies

#2520 Do not build against Java 8
  .github/workflows/test-opencast-build.yml
Labels: ELAN, tests

#2529 Expose some of the S3 client configuration for assets
  docs/guides/admin/docs/modules/awss3archive.md
  docs/guides/admin/docs/modules/awss3distribution.md
  etc/org.opencastproject.assetmanager.aws.s3.AwsS3AssetStore.cfg
  etc/org.opencastproject.distribution.aws.s3.AwsS3DistributionServiceImpl.cfg
  modules/asset-manager-storage-aws/src/main/java/org/opencastproject/assetmanager/aws/s3/AwsS3AssetStore.java
  modules/distribution-service-aws-s3/src/main/java/org/opencastproject/distribution/aws/s3/AwsS3DistributionServiceImpl.java
Labels: ELAN, SWITCH, enhancement

#2525 Fix checkstyle violations in 11 modules
  docs/checkstyle/checkstyle-suppressions.xml
  modules/sox-impl/src/main/java/org/opencastproject/sox/impl/SoxServiceImpl.java
  modules/sox-impl/src/main/java/org/opencastproject/sox/impl/endpoint/SoxRestService.java
  modules/sox-impl/src/test/java/org/opencastproject/sox/impl/SoxServiceTest.java
  modules/sox-workflowoperation/src/main/java/org/opencastproject/workflow/handler/sox/AnalyzeAudioWorkflowOperationHandler.java
  modules/sox-workflowoperation/src/main/java/org/opencastproject/workflow/handler/sox/NormalizeAudioWorkflowOperationHandler.java
  modules/static-file-service-api/src/main/java/org/opencastproject/staticfiles/endpoint/StaticFileRestService.java
  modules/static-file-service-api/src/test/java/org/opencastproject/staticfiles/endpoint/StaticFileRestServiceTest.java
  modules/static-file-service-impl/src/main/java/org/opencastproject/staticfiles/impl/StaticFileServiceImpl.java
  modules/static-file-service-impl/src/main/java/org/opencastproject/staticfiles/jmx/UploadStatistics.java
  modules/urlsigning-common/src/main/java/org/opencastproject/urlsigning/utils/ResourceRequestUtil.java
  modules/urlsigning-common/src/test/java/org/opencastproject/urlsigning/utils/PolicyUtilsTest.java
  modules/urlsigning-common/src/test/java/org/opencastproject/urlsigning/utils/ResourceRequestUtilTest.java
  modules/urlsigning-common/src/test/java/org/opencastproject/urlsigning/utils/SHA256UtilTest.java
  modules/urlsigning-service-impl/src/main/java/org/opencastproject/security/urlsigning/SigningMediaPackageSerializer.java
  modules/urlsigning-service-impl/src/main/java/org/opencastproject/security/urlsigning/service/impl/UrlSigningEndpoint.java
  modules/urlsigning-service-impl/src/main/java/org/opencastproject/security/urlsigning/service/impl/UrlSigningServiceImpl.java
  modules/urlsigning-service-impl/src/test/java/org/opencastproject/security/urlsigning/SigningMediaPackageSerializerTest.java
  modules/urlsigning-service-impl/src/test/java/org/opencastproject/security/urlsigning/WowzaResourceStrategyImplTest.java
  modules/urlsigning-service-impl/src/test/java/org/opencastproject/security/urlsigning/WowzaResourceStrategyTest.java
  modules/urlsigning-service-impl/src/test/java/org/opencastproject/security/urlsigning/provider/impl/GenericUrlSigningProviderTest.java
  modules/urlsigning-verifier-service-impl/src/main/java/org/opencastproject/security/urlsigning/filter/UrlSigningFilter.java
  modules/urlsigning-verifier-service-impl/src/test/java/org/opencastproject/security/urlsigning/filter/UrlSigningFilterTest.java
  modules/videoeditor-ffmpeg-impl/src/main/java/org/opencastproject/videoeditor/endpoint/VideoEditorServiceEndpoint.java
  modules/videoeditor-ffmpeg-impl/src/main/java/org/opencastproject/videoeditor/ffmpeg/FFmpegEdit.java
  modules/videoeditor-ffmpeg-impl/src/main/java/org/opencastproject/videoeditor/impl/VideoClip.java
  modules/videoeditor-ffmpeg-impl/src/main/java/org/opencastproject/videoeditor/impl/VideoEditorServiceImpl.java
  modules/videoeditor-ffmpeg-impl/src/test/java/org/opencastproject/videoeditor/ffmpeg/FFmpegTest.java
  modules/videoeditor-ffmpeg-impl/src/test/java/org/opencastproject/videoeditor/impl/VideoEditorTest.java
  modules/videoeditor-workflowoperation/src/main/java/org/opencastproject/workflow/handler/videoeditor/SilenceDetectionWorkflowOperationHandler.java
  modules/videoeditor-workflowoperation/src/main/java/org/opencastproject/workflow/handler/videoeditor/VideoEditorWorkflowOperationHandler.java
  modules/videoeditor-workflowoperation/src/test/java/org/opencastproject/workflow/handler/videoeditor/SilenceDetectionWorkflowOperationHandlerTest.java
  modules/videoeditor-workflowoperation/src/test/java/org/opencastproject/workflow/handler/videoeditor/VideoEditorWorkflowOperationHandlerTest.java
  modules/videogrid-service-impl/src/main/java/org/opencastproject/videogrid/endpoint/VideoGridServiceEndpoint.java
  modules/videogrid-service-impl/src/main/java/org/opencastproject/videogrid/impl/VideoGridServiceImpl.java
  modules/videogrid-service-impl/src/test/java/org/opencastproject/videogrid/impl/VideoGridServiceImplTest.java
  modules/videogrid-workflowoperation/src/main/java/org/opencastproject/workflow/handler/videogrid/VideoGridWorkflowOperationHandler.java
  modules/videogrid-workflowoperation/src/test/java/org/opencastproject/workflow/handler/videogrid/VideoGridWorkflowOperationHandlerTest.java
Labels: ELAN, codestyle

#2531 Hand over Elasticsearch Index to Services for Index Rebuild
  modules/admin-ui-index/pom.xml
  modules/admin-ui-index/src/main/java/org/opencastproject/adminui/index/AdminUISearchIndex.java
  modules/admin-ui-index/src/main/resources/OSGI-INF/search-index.xml
  modules/asset-manager-impl/pom.xml
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/OsgiAssetManager.java
  modules/authorization-manager/pom.xml
  modules/authorization-manager/src/main/java/org/opencastproject/authorization/xacml/manager/impl/OsgiAclServiceFactory.java
  modules/event-comment/pom.xml
  modules/event-comment/src/main/java/org/opencastproject/event/comment/persistence/EventCommentDatabaseServiceImpl.java
  modules/external-api-index/pom.xml
  modules/external-api-index/src/main/java/org/opencastproject/external/index/ExternalIndex.java
  modules/external-api-index/src/main/resources/OSGI-INF/external-index.xml
  modules/index-rebuild/src/main/java/org/opencastproject/index/rebuild/IndexProducer.java
  modules/index-rebuild/src/main/java/org/opencastproject/index/rebuild/IndexRebuildService.java
  modules/scheduler-impl/pom.xml
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
  modules/scheduler-impl/src/test/java/org/opencastproject/scheduler/impl/SchedulerServiceImplTest.java
  modules/series-service-impl/pom.xml
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/SeriesServiceImpl.java
  modules/themes/pom.xml
  modules/themes/src/main/java/org/opencastproject/themes/persistence/ThemesServiceDatabaseImpl.java
  modules/userdirectory/pom.xml
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaGroupRoleProvider.java
  modules/workflow-service-impl/pom.xml
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: ELAN, SWITCH, enhancement, java

#2293 Added the access_policy field to elasticsearch and made it searchable
  modules/elasticsearch-impl/src/main/resources/elasticsearch/event-mapping.json
  modules/elasticsearch-impl/src/main/resources/elasticsearch/series-mapping.json
  modules/elasticsearch-index/src/main/java/org/opencastproject/elasticsearch/index/event/EventIndexUtils.java
Labels: ELAN

#2435 Added Download Dropdown to Series LTI-Tools
  docs/guides/admin/docs/modules/ltimodule.md
  modules/lti/package-lock.json
  modules/lti/package.json
  modules/lti/src/OpencastRest.ts
  modules/lti/src/components/Series.tsx
  modules/lti/src/components/Welcome.tsx
  modules/lti/src/trackUtils.ts
  modules/lti/src/utils.ts
Labels: ELAN
