Repository opencast/opencast, pull requests merged in 2022-02, with the labels that each got.

#3373 Adding Camtasia .trec support.
  modules/common/src/main/resources/org/opencastproject/util/MimeTypes.xml
Labels: bug, enhancement

#3203 start-workflow-wfh allows to pass mediapackage id from previous WFH
  docs/guides/admin/docs/workflowoperationhandlers/duplicate-event-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/start-workflow-woh.md
  etc/workflows/duplicate-event.xml
  modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/DuplicateEventWorkflowOperationHandler.java
  modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/StartWorkflowWorkflowOperationHandler.java
  modules/workflow-workflowoperation/src/test/java/org/opencastproject/workflow/handler/workflow/StartWorkflowWorkflowOperationHandlerTest.java
Labels: UoM

#3262 Modernize Code
  modules/kernel/src/main/java/org/opencastproject/kernel/security/OrganizationDirectoryServiceImpl.java
Labels: maintenance

#3414 Revert "update karaf from version 4.2.9 to 4.2.15"
  assemblies/karaf-features/src/main/feature/feature.xml
  assemblies/resources/build.xml
  pom.xml
Labels: bug

#3416 Fixed Typo in Logging Statement
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/Ingestor.java
Labels: bug

#3423 Fixes OSGi error when shutting down Opencast
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImpl.java
Labels: bug

#3390 Endpoint to Remove Tracked Host Bundles
  modules/kernel/src/main/java/org/opencastproject/kernel/bundleinfo/BundleInfoRestEndpoint.java
Labels: feature

#3340 Match Inbox Events Against Schedule
  etc/org.opencastproject.ingest.scanner.InboxScannerService-inbox.cfg
  modules/ingest-service-impl/pom.xml
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/InboxScannerService.java
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/Ingestor.java
Labels: feature

#3422 Refactor XACMLAuthorizationService
  modules/authorization-xacml/src/main/java/org/opencastproject/authorization/xacml/XACMLAuthorizationService.java
Labels: maintenance

#3415 Update pax logging from version 1.11.13 to 1.11.14
  assemblies/karaf-features/src/main/feature/feature.xml
  assemblies/resources/build.xml
Labels: dependencies

#3384 Add DublinCore Catalog to Scheduler JSON
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/endpoint/SchedulerRestService.java
Labels: enhancement

#3389 Rename Files Workflow Operation Handler
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/admin/docs/workflowoperationhandlers/index.md
  docs/guides/admin/docs/workflowoperationhandlers/rename-files-woh.md
  docs/guides/admin/mkdocs.yml
  modules/rename-files-workflowoperation/pom.xml
  modules/rename-files-workflowoperation/src/main/java/org/opencastproject/workflow/handler/rename/RenameFilesWorkflowOperationHandler.java
  pom.xml
Labels: feature

#3437 Fix merge conflict
  modules/rename-files-workflowoperation/pom.xml
Labels: bug

#3443 Regenerate `package-lock.json`
  docs/guides/package-lock.json
  modules/admin-ui-frontend/package-lock.json
  modules/engage-paella-player/package-lock.json
  modules/engage-theodul-core/package-lock.json
  modules/engage-theodul-plugin-controls/package-lock.json
  modules/engage-theodul-plugin-custom-matomo/package-lock.json
  modules/engage-theodul-plugin-custom-mhConnection/package-lock.json
  modules/engage-theodul-plugin-custom-notifications/package-lock.json
  modules/engage-theodul-plugin-description/package-lock.json
  modules/engage-theodul-plugin-tab-description/package-lock.json
  modules/engage-theodul-plugin-tab-downloads/package-lock.json
  modules/engage-theodul-plugin-tab-shortcuts/package-lock.json
  modules/engage-theodul-plugin-tab-slidetext/package-lock.json
  modules/engage-theodul-plugin-video-videojs/package-lock.json
  modules/engage-ui/package-lock.json
  modules/lti/package-lock.json
  modules/runtime-info-ui-ng/package-lock.json
  modules/runtime-info-ui/package-lock.json
Labels: maintenance

#3444 Fix frontend-no-prebuilt profile
  modules/admin-ui-frontend/pom.xml
  modules/engage-paella-player/pom.xml
  modules/lti/pom.xml
Labels: bug

#3457 Update Opencast Studio to 2022-02-16
  modules/studio/pom.xml
Labels: ELAN, studio

#3461 Fix meeting time
  docs/guides/.infrastructure/index.html.j2
Labels: documentation

#3467 Opencast 10.10 release notes and changelog
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#3326 Add recommended practices for Release manager
  docs/guides/developer/docs/release-manager.md
Labels: documentation

#3431 Remove ManagedService from OaiPmhServer
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/server/OaiPmhServer.java
Labels: maintenance

#3440 Update Jackson Libraries to 2.13.1
  pom.xml
Labels: maintenance, dependencies

#3474 Fix OC 11.4 release notes layout issues
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#3466 Check if encoding profile exist for imageToVideo Operation
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
Labels: small pull request

#3490 Document that you cannot run Opencast in a sub-path
  docs/guides/admin/docs/configuration/basic.md
  docs/guides/admin/docs/configuration/multi.tenancy.md
  etc/custom.properties
Labels: documentation
