Repository opencast/opencast, pull requests merged in 2022-11, with the labels that each got.

#4237 Added maximum line length configuration option to Azure Transcription Service
  etc/org.opencastproject.transcription.microsoftazure.MicrosoftAzureTranscriptionService.cfg
  modules/transcription-service-microsoft-azure/src/main/java/org/opencastproject/transcription/microsoftazure/MicrosoftAzureTranscriptionService.java
Labels: enhancement, ELAN, ETH

#4239 Added automatic language detection to Azure Transcription Service
  docs/guides/admin/docs/workflowoperationhandlers/microsoft-azure-attach-transcription-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/microsoft-azure-start-transcription-woh.md
  etc/org.opencastproject.transcription.microsoftazure.MicrosoftAzureTranscriptionService.cfg
  modules/transcription-service-amberscript/src/main/java/org/opencastproject/transcription/amberscript/AmberscriptTranscriptionService.java
  modules/transcription-service-api/src/main/java/org/opencastproject/transcription/api/TranscriptionService.java
  modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java
  modules/transcription-service-ibm-watson-impl/src/main/java/org/opencastproject/transcription/ibmwatson/IBMWatsonTranscriptionService.java
  modules/transcription-service-microsoft-azure/pom.xml
  modules/transcription-service-microsoft-azure/src/main/java/org/opencastproject/transcription/microsoftazure/MicrosoftAzureTranscriptionService.java
  modules/transcription-service-workflowoperation/src/main/java/org/opencastproject/transcription/workflowoperation/MicrosoftAzureAttachTranscriptionOperationHandler.java
  modules/transcription-service-workflowoperation/src/main/java/org/opencastproject/transcription/workflowoperation/MicrosoftAzureStartTranscriptionOperationHandler.java
  modules/transcription-service-workflowoperation/src/test/java/org/opencastproject/transcription/workflowoperation/MicrosoftAzureAttachTranscriptionOperationHandlerTest.java
  modules/transcription-service-workflowoperation/src/test/java/org/opencastproject/transcription/workflowoperation/MicrosoftAzureStartTranscriptionOperationHandlerTest.java
Labels: enhancement, ELAN, ETH

#4418 Opencast 13 release schedule
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#4316 Update Live Publication in Archive on Capture Agent Change
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImpl.java
  modules/live-schedule-impl/src/test/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImplTest.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
Labels: bug, ELAN, java

#4382 Fix Encoding Profile Type Handling in Encode WOH
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/EncodeWorkflowOperationHandler.java
Labels: bug, ELAN, java

#4377 Do not add roleprefix to extra roles
  modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/LdapUserProviderInstance.java
Labels: bug

#4416 Allow dots in template file names
  modules/common/src/main/java/org/opencastproject/util/doc/DocData.java
  modules/runtime-info/src/main/java/org/opencastproject/runtimeinfo/rest/RestDocData.java
  modules/runtime-info/src/main/java/org/opencastproject/runtimeinfo/rest/RestEndpointData.java
Labels: small pull request

#4411 Let Editor know if files are available locally
  etc/org.opencastproject.editor.EditorServiceImpl.cfg
  modules/editor-service-api/src/main/java/org/opencastproject/editor/api/EditingData.java
  modules/editor-service/src/main/java/org/opencastproject/editor/EditorServiceImpl.java
  modules/editor-service/src/test/java/org/opencastproject/editor/EditorServiceImplTest.java
Labels: editor

#4102 Move thumbnail preview generation to the client
  modules/admin-ui-frontend/app/scripts/modules/events/subresources/controllers/toolsController.js
  modules/admin-ui-frontend/app/scripts/modules/events/subresources/partials/tools.html
  modules/admin-ui-frontend/app/scripts/shared/resources/toolsResource.js
  modules/admin-ui-frontend/app/scripts/shared/services/playerAdapter.js
  modules/admin-ui-frontend/app/scripts/shared/services/playerAdapterFactoryDefault.js
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ToolsEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/ThumbnailImpl.java
Labels: admin-ui-feature-tracking

#4388 Use valid URL for admin interface mock data
  modules/admin-ui-frontend/test/app/GET/admin-ng/event/1a2a040b-ef73-4323-93dd-052b86036b75/asset/attachment/attachments.json
  modules/admin-ui-frontend/test/app/GET/admin-ng/event/1a2a040b-ef73-4323-93dd-052b86036b75/asset/attachment/cover.json
Labels: tests

#4421 Fix Auto-update Tests
  .github/workflows/auto-update-npm-libraries.yml
Labels: tests

#4422 More ESLint Auto-Updates
  .github/workflows/auto-update-npm-libraries.yml
Labels: tests

#4321 Annoy adopters who haven't registered
  modules/admin-ui-frontend/app/index.html
  modules/admin-ui-frontend/app/scripts/modules/registration/controllers/registrationController.js
  modules/admin-ui-frontend/app/scripts/modules/registration/services/states.js
  modules/admin-ui-frontend/app/scripts/shared/controllers/applicationController.js
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/registration-modal.html
  modules/admin-ui-frontend/app/scripts/shared/resources/adopterRegistrationResource.js
  modules/admin-ui-frontend/app/scripts/shared/resources/adopterStatisticSummaryResource.js
  modules/admin-ui-frontend/app/scripts/shared/services/restServiceMonitor.js
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui-frontend/test/test/unit/shared/controllers/applicationControllerSpec.js
  modules/adopter-registration-impl/src/main/java/org/opencastproject/adopter/registration/Controller.java
  modules/adopter-registration-impl/src/main/java/org/opencastproject/adopter/registration/Form.java
  modules/adopter-registration-impl/src/main/java/org/opencastproject/adopter/statistic/ScheduledDataCollector.java
Labels: enhancement, admin-ui-feature-tracking

#4441 Azure transcription service improvements
  docs/guides/admin/docs/modules/microsoftazuretranscripts.md
  modules/transcription-service-microsoft-azure/pom.xml
  modules/transcription-service-microsoft-azure/src/main/java/org/opencastproject/transcription/microsoftazure/MicrosoftAzureTranscriptionService.java
  modules/transcription-service-workflowoperation/src/main/java/org/opencastproject/transcription/workflowoperation/MicrosoftAzureAttachTranscriptionOperationHandler.java
Labels: bug

#4442 Update Karaf to 4.2.16
  pom.xml
Labels: dependencies

#4445 Update to eclipselink 2.7.8
  pom.xml
Labels: dependencies

#4450 Add index for oc_job_argument table (OC 13)
  docs/upgrade/12_to_13/mariadb.sql
  docs/upgrade/12_to_13/postgresql.sql
  modules/common-jpa-impl/src/main/java/org/opencastproject/job/jpa/JpaJob.java
Labels: small pull request

#4383 Simplify ldap user directory implementation
  assemblies/karaf-features/src/main/feature/feature.xml
  etc/security/mh_default_org.xml
  modules/security-ldap/pom.xml
  modules/security-ldap/src/main/java/org/opencastproject/security/ldap/OpencastUserDetailsMapper.java
  modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/LdapUserProviderFactory.java
  modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/LdapUserProviderInstance.java
  modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/OpencastLdapAuthoritiesPopulator.java
  modules/userdirectory-ldap/src/test/java/org/opencastproject/userdirectory/ldap/OpencastLdapAuthoritiesPopulatorTest.java
Labels: enhancement

#4458 Opencast 12.5 Changelog
  docs/guides/admin/docs/changelog.md
Labels: documentation

#4488 Update board list in documentation
  docs/guides/developer/docs/governance.md
Labels: documentation
