Repository opencast/opencast, pull requests merged in 2022-12, with the labels that each got.

#4490 Add rules for merging pull requests to the docs
  docs/guides/developer/docs/development-process.md
Labels: documentation, ELAN

#4412 JWTs in request parameters
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/admin/docs/configuration/security.jwt.md
  docs/guides/admin/docs/releasenotes/jwt-request-parameter-filter.txt
  docs/guides/admin/docs/releasenotes/redirect-endpoint.txt
  etc/security/mh_default_org.xml
  modules/redirect/pom.xml
  modules/redirect/src/main/java/org/opencastproject/redirect/RedirectEndpoint.java
  modules/redirect/src/test/java/org/opencastproject/redirect/RedirectEndpointTest.java
  modules/security-jwt/src/main/java/org/opencastproject/security/jwt/JWTRequestHeaderAuthenticationFilter.java
  modules/security-jwt/src/main/java/org/opencastproject/security/jwt/JWTRequestParameterAuthenticationFilter.java
  modules/security-jwt/src/main/java/org/opencastproject/security/jwt/Util.java
  modules/security-jwt/src/test/java/org/opencastproject/security/jwt/JWTLoginTest.java
  modules/security-jwt/src/test/java/org/opencastproject/security/jwt/JWTRequestHeaderAuthenticationFilterTest.java
  modules/security-jwt/src/test/java/org/opencastproject/security/jwt/JWTRequestParameterAuthenticationFilterTest.java
  modules/security-jwt/src/test/java/org/opencastproject/security/jwt/TestAbstractPreAuthenticatedProcessingFilter.java
  pom.xml
Labels: feature, ELAN

#4496 Fix Firefox install for admin ui tests in GHA
  .github/workflows/test-admin-interface-frontend.yml
Labels: maintenance

#4519 Reduce number of snapshots taken in the new editor backend
  modules/editor-service/src/main/java/org/opencastproject/editor/EditorServiceImpl.java
Labels: ELAN, small pull request, editor

#4484 Prepare release notes for Opencast 13
  docs/guides/admin/docs/releasenotes.md
  docs/guides/admin/docs/releasenotes/comments-in-index.txt
  docs/guides/admin/docs/releasenotes/master-playlist-in-tobira-harvest.txt
  docs/guides/admin/docs/releasenotes/plugin-management.txt
Labels: documentation

#4537 Changelog for Opencast 12.6
  docs/guides/admin/docs/changelog.md
Labels: documentation

#4538 Add Opencast 12.6 release notes
  docs/guides/admin/docs/releasenotes.md
  docs/guides/admin/docs/releasenotes/jwt-request-parameter-filter.txt
  docs/guides/admin/docs/releasenotes/master-playlist-in-tobira-harvest.txt
  docs/guides/admin/docs/releasenotes/redirect-endpoint.txt
Labels: documentation

#4548 Mark OC13 RPMs as Stable
  docs/guides/admin/docs/installation/rpm-el.md
  docs/guides/admin/docs/installation/rpm-el7.md
Labels: documentation

#4550 Ensure segments.segment is array
  modules/engage-paella-player-7/src/js/EpisodeConversor.js
Labels: bug

#4539 Make event updating faster after changes to series metadata/ACL
  modules/conductor/src/main/java/org/opencastproject/event/handler/SeriesUpdatedEventHandler.java
Labels: enhancement

#4498 Fix possible duplicate notes in Admin UI
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventsController.js
Labels: bug, ELAN, admin-ui-feature-tracking

#4549 Sync login script of paella-6 and paella-7
  modules/engage-paella-player-7/src/auth.html
  modules/engage-paella-player/src/main/paella-opencast/ui/auth.html
Labels: bug

#4511 Make debug output in the JWT filters simpler and more idiomatic
  docs/guides/admin/docs/configuration/security.jwt.md
  etc/security/mh_default_org.xml
  modules/security-jwt/src/main/java/org/opencastproject/security/jwt/JWTRequestHeaderAuthenticationFilter.java
  modules/security-jwt/src/main/java/org/opencastproject/security/jwt/JWTRequestParameterAuthenticationFilter.java
  modules/security-jwt/src/main/java/org/opencastproject/security/jwt/Util.java
Labels: ELAN

#4434 Add Studip User Provider
  assemblies/karaf-features/src/main/feature/feature.xml
  assemblies/pom.xml
  etc/org.opencastproject.index.service.resources.list.provider.ContributorsListProvider.cfg
  etc/org.opencastproject.userdirectory.studip-default.cfg.template
  modules/userdirectory-studip/pom.xml
  modules/userdirectory-studip/src/main/java/org/opencastproject/userdirectory/studip/StudipUserProviderFactory.java
  modules/userdirectory-studip/src/main/java/org/opencastproject/userdirectory/studip/StudipUserProviderInstance.java
  modules/userdirectory-studip/src/main/resources/OSGI-INF/metatype/metatype.xml
  pom.xml
Labels: feature

#4503 Document prerelease repositories
  docs/guides/admin/docs/index.md
  docs/guides/admin/docs/prereleases.md
  docs/guides/admin/mkdocs.yml
Labels: documentation

#4514 Allow CA user to get series
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/persistence/SeriesServiceDatabaseImpl.java
Labels: bug, ELAN

#4502 Fix: series deleted from search index cannot be re-added
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/Schema.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/solr/SolrIndexManager.java
  modules/search-service-impl/src/test/java/org/opencastproject/search/impl/SearchServiceImplTest.java
Labels: bug, harvard-dce

#4536 Avoid using jobs in SeriesUpdatedEventHandler
  modules/conductor/src/main/java/org/opencastproject/event/handler/SeriesUpdatedEventHandler.java
  modules/distribution-service-api/src/main/java/org/opencastproject/distribution/api/DistributionService.java
  modules/distribution-service-aws-s3-remote/src/main/java/org/opencastproject/distribution/aws/s3/remote/AwsS3DistributionServiceRemoteImpl.java
  modules/distribution-service-aws-s3/src/main/java/org/opencastproject/distribution/aws/s3/AwsS3DistributionServiceImpl.java
  modules/distribution-service-download-remote/src/main/java/org/opencastproject/distribution/download/remote/DownloadDistributionServiceRemoteImpl.java
  modules/distribution-service-download/src/main/java/org/opencastproject/distribution/download/DownloadDistributionServiceImpl.java
  modules/distribution-service-streaming-remote/src/main/java/org/opencastproject/distribution/streaming/remote/StreamingDistributionServiceRemoteImpl.java
  modules/distribution-service-streaming-wowza/src/main/java/org/opencastproject/distribution/streaming/wowza/WowzaStreamingDistributionService.java
  modules/search-service-api/src/main/java/org/opencastproject/search/api/SearchService.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/endpoint/SearchRestService.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/SearchServiceImpl.java
  modules/search-service-remote/src/main/java/org/opencastproject/search/remote/SearchServiceRemoteImpl.java
Labels: enhancement, ELAN
