Repository opencast/opencast, pull requests merged in 2022-06, with the labels that each got.

#3818 Workflow tests should no longer race
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/CountWorkflowsTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/HoldStateTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/PauseFinalOperationTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/PauseWorkflowTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowOperationSkippingIntricateTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowOperationSkippingTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowServiceImplTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowTestSupport.java
Labels: bug

#3828 Further workflow test race fixes
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/PauseWorkflowTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowTestSupport.java
Labels: bug

#3813 Properly unregister OAI-PMH servlet
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/server/OaiPmhServer.java
Labels: bug

#1370 Fix Conflict Detection
  modules/scheduler-api/src/main/java/org/opencastproject/scheduler/api/Util.java
  modules/scheduler-impl/src/test/java/org/opencastproject/scheduler/impl/SchedulerServiceImplTest.java
Labels: bug, ELAN

#3806 Speech to text language fallback and placeholder
  docs/guides/admin/docs/workflowoperationhandlers/speech-to-text-woh.md
  modules/speech-to-text-workflowoperation/src/main/java/org/opencastproject/workflow/handler/speechtotext/SpeechToTextWorkflowOperationHandler.java
Labels: enhancement

#3812 Fix rest services are unavailable under certain circumstances
  modules/kernel/src/main/java/org/opencastproject/kernel/rest/RestPublisher.java
Labels: bug

#3865 Rename yaml workflow title
  etc/workflows/fast.xml
  etc/workflows/fast.yaml
Labels: small pull request

#3864 Fix duplicate dependency declaration
  modules/cover-image-workflowoperation/pom.xml
Labels: bug

#3849 Amberscript configuration fix
  etc/org.opencastproject.transcription.amberscript.AmberscriptTranscriptionService.cfg
Labels: documentation, configuration

#3870 Update Editor to Version 2022-06-15
  modules/editor/pom.xml
Labels: editor

#3867 Update Opencast Studio to 2022-06-15
  modules/studio/pom.xml
Labels: studio

#3866 Add description to publish workflow
  etc/workflows/publish.xml
Labels: documentation

#3862 Make Delete Dialog Look Alike
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/confirm-modal.html
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/delete-single-series-modal.html
  modules/admin-ui-frontend/app/styles/views/modals/_modal-dialog.scss
Labels: bug

#3872 Opencast 12 Upgrade Guide
  docs/guides/admin/docs/upgrade.md
Labels: documentation

#3873 Finish the Opencast 12 release notes
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#3881 Fix admin ui proxy
  modules/admin-ui-frontend/Gruntfile.js
Labels: bug, maintenance

#3832 Use Local Index References
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerImpl.java
  modules/elasticsearch-index/src/main/java/org/opencastproject/elasticsearch/index/rebuild/IndexProducer.java
  modules/elasticsearch-index/src/main/java/org/opencastproject/elasticsearch/index/rebuild/IndexRebuildService.java
  modules/event-comment/src/main/java/org/opencastproject/event/comment/persistence/EventCommentDatabaseServiceImpl.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
  modules/scheduler-impl/src/test/java/org/opencastproject/scheduler/impl/SchedulerServiceImplTest.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/SeriesServiceImpl.java
  modules/themes/src/main/java/org/opencastproject/themes/persistence/ThemesServiceDatabaseImpl.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: enhancement

#3883 Add formal Opensearch support
  docs/guides/admin/docs/configuration/opensearch.md
  docs/guides/admin/docs/modules/searchindex/index.md
  docs/guides/admin/mkdocs.yml
  docs/guides/developer/docs/proposal-log.md
  docs/scripts/devel-dependency-containers/docker-compose-all-sql.yml
  docs/scripts/devel-dependency-containers/docker-compose-mariadb.yml
  docs/scripts/devel-dependency-containers/docker-compose-postgresql.yml
  docs/scripts/devel-dependency-containers/docker-compose.yml
Labels: maintenance, documentation
