Repository opencast/opencast, pull requests merged in 2022-08, with the labels that each got.

#4061 Update List of Committers
  docs/guides/developer/.generate-list-of-committers.sh
  docs/guides/developer/docs/committer.md
Labels: documentation

#4063 Warn About Removed Workflow Endpoint
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#4048 Don't Fail on Missing Jobs
  modules/kernel/src/main/java/org/opencastproject/kernel/rest/CurrentJobFilter.java
Labels: bug

#4057 Fixed OSGI annotation for OaiPmhServer
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/server/OaiPmhServer.java
Labels: bug, ELAN, small pull request

#4064 Fallback for Event Title in Publication
  modules/distribution-workflowoperation/pom.xml
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandler.java
Labels: bug

#4025 Update CAS docs
  docs/guides/admin/docs/configuration/security.cas.md
Labels: documentation

#4087 Link the docs for the publication to workspace WOH
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#4068 Fix CreatorDate Filter in GET api/series/
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SeriesEndpoint.java
Labels: bug, small pull request

#4088 Opencast 12.2 Release Notes
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#4101 Fixes mysql upgrade script stop error
  docs/upgrade/11_to_12/workflows_mariadb.py
Labels: bug, small pull request

#4104 Document broken MariaDB upgrade script
  docs/guides/admin/docs/upgrade.md
Labels: documentation

#4113 Add Dummy capture agent documentation
  docs/guides/developer/docs/development-environment.md
Labels: documentation

#4107 Fix Publication to Workspace Operation Documentation
  docs/guides/admin/docs/workflowoperationhandlers/publication-to-workspace-woh.md
Labels: documentation

#4134 Update CentOS Stream/RHEL documentation
  docs/guides/admin/docs/installation/index.md
  docs/guides/admin/docs/installation/rpm-el.md
  docs/guides/admin/docs/installation/rpm-el7.md
  docs/guides/admin/mkdocs.yml
Labels: documentation

#4066 Improve filter description in extapi series/statistics/workflow-definitions
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/GroupsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/StatisticsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowDefinitionsEndpoint.java
Labels: small pull request
