Repository opencast/opencast, pull requests merged in 2022-01, with the labels that each got.

#3305 Update to pax-logging 1.11.13
  assemblies/karaf-features/src/main/feature/feature.xml
  assemblies/resources/build.xml
Labels: bug, security

#3322 Show input selection only if applicable
  modules/admin-ui-frontend/app/scripts/shared/partials/wizards/new-event.html
Labels: bug, javascript

#3334 Warn against using CIFS for Inbox
  docs/guides/admin/docs/configuration/inbox.md
Labels: documentation

#3188 Cover image surrogate problem
  assemblies/karaf-features/src/main/feature/feature.xml
  etc/branding/coverimage.xsl
  modules/cover-image-impl/pom.xml
  modules/cover-image-impl/src/main/java/org/opencastproject/coverimage/impl/AbstractCoverImageService.java
  modules/cover-image-impl/src/main/java/org/opencastproject/coverimage/impl/CoverImageServiceOsgiImpl.java
  modules/cover-image-impl/src/main/java/org/opencastproject/coverimage/impl/xsl/XsltHelper.java
Labels: bug, dependencies, java

#3339 Fix Scheduler Conflict Checks
  modules/scheduler-api/src/main/java/org/opencastproject/scheduler/api/SchedulerService.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
Labels: bug

#3254 Prevent API failing on empty files
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/util/EventHttpServletRequest.java
Labels: bug

#3328 Java Dependency Update
  modules/common/src/main/java/org/opencastproject/mediapackage/MediaPackageBuilderImpl.java
  modules/common/src/main/java/org/opencastproject/mediapackage/MediaPackageImpl.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowParser.java
  pom.xml
Labels: dependencies, java

#3336 Fix REST Test Network Bindings
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/AbstractEventEndpointTest.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/AclEndpointTest.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/CaptureAgentsEndpointTest.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/JobEndpointTest.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/ListProvidersEndpointTest.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/SeriesEndpointTest.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/ServerEndpointTest.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/ServicesEndpointTest.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TasksEndpointTest.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/ThemesEndpointTest.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/UsersEndpointTest.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/UsersSettingsEndpointTest.java
  modules/authorization-manager/pom.xml
  modules/authorization-manager/src/main/java/org/opencastproject/authorization/xacml/manager/endpoint/AbstractAclServiceRestEndpoint.java
  modules/authorization-manager/src/main/java/org/opencastproject/authorization/xacml/manager/endpoint/OsgiAclServiceRestEndpoint.java
  modules/authorization-manager/src/test/java/org/opencastproject/authorization/xacml/manager/endpoint/OsgiAclServiceRestEndpointTest.java
  modules/authorization-manager/src/test/java/org/opencastproject/authorization/xacml/manager/endpoint/TestRestService.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/BaseEndpointTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/CaptureAgentsEndpointTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/EventsEndpointTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/SecurityEndpointTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/SeriesEndpointTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/WorkflowDefinitionsEndpointTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/WorkflowsEndpointTest.java
  modules/kernel/src/test/java/org/opencastproject/kernel/bundleinfo/BundleInfoRestEndpointTest.java
  modules/oaipmh/src/test/java/org/opencastproject/oaipmh/server/AbstractOaiPmhServerInfoRestEndpointTest.java
  modules/publication-service-oaipmh-remote/src/test/java/org/opencastproject/publication/oaipmh/endpoint/OaiPmhPublicationRestServiceTest.java
  modules/rest-test-environment/src/main/java/org/opencastproject/test/rest/RestServiceTestEnv.java
Labels: bug, tests

#3337 Remove non-optional optional
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/InboxScannerService.java
Labels: maintenance

#3152 Add id to execute-many and org_id to execute-many and execute-once
  docs/guides/admin/docs/modules/execute.md
  modules/execute-api/src/main/java/org/opencastproject/execute/api/ExecuteService.java
  modules/execute-impl/src/main/java/org/opencastproject/execute/impl/ExecuteServiceImpl.java
Labels: enhancement

#3154 Allow selection by tags in execute-once
  docs/guides/admin/docs/modules/execute.md
  modules/execute-impl/src/main/java/org/opencastproject/execute/impl/ExecuteServiceImpl.java
Labels: enhancement

#2811 Add download artifacts in engage publication
  docs/guides/admin/docs/workflowoperationhandlers/publish-engage-woh.md
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandler.java
Labels: ELAN

#3359 Document Capture Agent Input Selection
  docs/guides/developer/docs/modules/capture-agent/capture-agent-input.md
  docs/guides/developer/docs/modules/capture-agent/capture-agent.md
  docs/guides/developer/docs/modules/capture-agent/input-selection.png
  docs/guides/developer/mkdocs.yml
Labels: documentation

#3361 Fix metadata for multitenancy
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
Labels: bug, needs attention, ELAN, java

#2855 Added speech to text (Vosk)
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/admin/docs/workflowoperationhandlers/index.md
  docs/guides/admin/docs/workflowoperationhandlers/speech-to-text-woh.md
  docs/guides/admin/mkdocs.yml
  etc/org.opencastproject.speechtotext.impl.SpeechToTextServiceImpl.cfg
  etc/org.opencastproject.speechtotext.impl.engine.VoskEngine.cfg
  modules/speech-to-text-api/pom.xml
  modules/speech-to-text-api/src/main/java/org/opencastproject/speechtotext/api/SpeechToTextEngine.java
  modules/speech-to-text-api/src/main/java/org/opencastproject/speechtotext/api/SpeechToTextEngineException.java
  modules/speech-to-text-api/src/main/java/org/opencastproject/speechtotext/api/SpeechToTextService.java
  modules/speech-to-text-api/src/main/java/org/opencastproject/speechtotext/api/SpeechToTextServiceException.java
  modules/speech-to-text-impl/pom.xml
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/SpeechToTextServiceImpl.java
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/endpoint/SpeechToTextServiceRestEndpoint.java
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/VoskEngine.java
  modules/speech-to-text-impl/src/test/java/org/opencastproject/speechtotext/impl/SpeechToTextServiceImplTest.java
  modules/speech-to-text-impl/src/test/resources/speech_to_text_test.mp4
  modules/speech-to-text-remote/pom.xml
  modules/speech-to-text-remote/src/main/java/org/opencastproject/speechtotext/remote/SpeechToTextServiceRemoteImpl.java
  modules/speech-to-text-workflowoperation/pom.xml
  modules/speech-to-text-workflowoperation/src/main/java/org/opencastproject/workflow/handler/speechtotext/SpeechToTextWorkflowOperationHandler.java
  pom.xml
Labels: feature, ELAN

#3365 Remove `mvn site` Test
  .github/workflows/test-opencast-site.yml
Labels: tests

#3372 Fix port checking
  assemblies/resources/bin/check_ports
Labels: bug

#3368 Capture agent calendar as JSON
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/endpoint/SchedulerRestService.java
Labels: feature

#3369 Update slf4j
  pom.xml
Labels: dependencies

#3155 Allow the use of organization properties in workflows
  docs/guides/admin/docs/configuration/workflow.md
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: enhancement

#3327 Extend Metadata Extraction in Inbox
  etc/org.opencastproject.ingest.scanner.InboxScannerService-inbox.cfg
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/InboxScannerService.java
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/Ingestor.java
Labels: feature

#3342 Allow metadata editting
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
  modules/scheduler-impl/src/test/java/org/opencastproject/scheduler/impl/SchedulerServiceImplTest.java
Labels: bug
