Repository opencast/opencast, pull requests merged in 2022-05, with the labels that each got.

#3707 Out of video image extraction should not fail
  etc/encoding/opencast.properties
Labels: bug, ELAN

#3749 Explore H2 Database
  docs/guides/developer/docs/explore-h2-database.md
  docs/guides/developer/docs/index.md
  docs/guides/developer/mkdocs.yml
Labels: documentation

#3715 Unbreak the metadata editor included with the video editor and save events as well as the video editor state when save is pressed
  modules/admin-ui-frontend/app/index.html
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventController.js
  modules/admin-ui-frontend/app/scripts/modules/events/subresources/controllers/toolsController.js
  modules/admin-ui-frontend/app/scripts/modules/events/subresources/partials/tools.html
  modules/admin-ui-frontend/app/scripts/shared/services/metadataSaveService.js
  modules/admin-ui-frontend/test/test/unit/modules/events/subresources/controllers/toolsControllerSpec.js
Labels: bug, javascript

#3377 Remove Solr from WorkflowService
  docs/guides/admin/docs/releasenotes/remove-solr-from-workflow-service.txt
  docs/guides/admin/docs/releasenotes/store-workflows-as-tables-instead-of-xml.txt
  docs/guides/admin/docs/upgrade.md
  docs/guides/developer/docs/api/workflow-api.md
  docs/guides/developer/mkdocs.yml
  etc/org.opencastproject.workflow.impl.WorkflowServiceImpl.cfg
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestEventEndpoint.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/TestJobEndpoint.java
  modules/conductor/pom.xml
  modules/conductor/src/main/java/org/opencastproject/event/handler/ConductingSeriesUpdatedEventHandler.java
  modules/conductor/src/main/java/org/opencastproject/event/handler/WorkflowPermissionsUpdatedEventHandler.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowsEndpoint.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/TestWorkflowsEndpoint.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/WorkflowsEndpointTest.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowInstance.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowQuery.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowService.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabase.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabaseImpl.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowSet.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowSetImpl.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowStatistics.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/XmlWorkflowParser.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/YamlWorkflowParser.java
  modules/workflow-service-api/src/main/resources/org/opencastproject/workflow/api/jaxb.index
  modules/workflow-service-impl/pom.xml
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/endpoint/WorkflowRestService.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceIndex.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceSolrIndex.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/jmx/WorkflowsStatistics.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/jmx/WorkflowsStatisticsMXBean.java
  modules/workflow-service-impl/src/main/resources/incident-l10n/org.opencastproject.workflow.properties
  modules/workflow-service-impl/src/main/resources/solr/conf/protwords.txt
  modules/workflow-service-impl/src/main/resources/solr/conf/schema.xml
  modules/workflow-service-impl/src/main/resources/solr/conf/scripts.conf
  modules/workflow-service-impl/src/main/resources/solr/conf/solrconfig.xml
  modules/workflow-service-impl/src/main/resources/solr/conf/stopwords.txt
  modules/workflow-service-impl/src/main/resources/solr/conf/synonyms.txt
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/CountWorkflowsTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/HoldStateTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/PauseFinalOperationTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/PauseWorkflowTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowOperationSkippingIntricateTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowOperationSkippingTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowPersistenceTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowServiceImplAuthzTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowServiceImplTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowServiceSolrIndexTest.java
  modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowStatisticsTest.java
  modules/workflow-service-remote/src/main/java/org/opencastproject/workflow/remote/WorkflowServiceRemoteImpl.java
Labels: enhancement, ELAN, java

#3716 Add missing tags in encode WOH
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
  modules/composer-ffmpeg/src/test/java/org/opencastproject/composer/impl/ComposerServiceTest.java
Labels: bug, java

#3778 Update Branch Cut Announcement
  docs/guides/developer/docs/release-manager.md
Labels: documentation

#3779 Opencast 12 Release Notes
  docs/guides/admin/docs/releasenotes.md
  docs/guides/admin/docs/upgrade.md
Labels: documentation

#3767 Patch for admin-ui-frontend Gruntfile.js when developing locally and using a remote proxy.
  modules/admin-ui-frontend/Gruntfile.js
Labels: bug

#3785 Clarify that #3715 was a fix in the release notes
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#3799 Update maven documentation
  docs/guides/developer/docs/infrastructure/maven-repository.md
Labels: documentation

#3808 Add missing PRs to OC11 changelog
  docs/guides/admin/docs/changelog.md
Labels: documentation
