Repository opencast/opencast, pull requests merged in 2022-10, with the labels that each got.

#4208 Fix composer incident codes and messages for process-smil and multiencode.
  modules/composer-ffmpeg/src/main/resources/incident-l10n/org.opencastproject.composer.properties
  modules/composer-ffmpeg/src/main/resources/incident-l10n/org.opencastproject.composer_de.properties
Labels: bug

#4249 Make initialization of new event ACL with series ACL in the Admin UI configurable
  etc/org.opencastproject.organization-mh_default_org.cfg
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-event/access.js
Labels: enhancement, ELAN, javascript, configuration

#4250 Actually Retract Live Publication
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/message/SchedulerUpdateHandler.java
  modules/scheduler-api/src/main/java/org/opencastproject/scheduler/api/SchedulerService.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
Labels: bug, ELAN, java

#4238 Fixed azure transcription error message in case of Error
  modules/transcription-service-microsoft-azure/src/main/java/org/opencastproject/transcription/microsoftazure/MicrosoftAzureTranscriptionService.java
Labels: bug, ELAN, ETH, small pull request

#4240 Group dependabot Paella 7 commits
  .github/workflows/dependabot-batcher.yml
Labels: maintenance

#3827 Missing setting track logical name when serverless HLS in process-smil
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
Labels: bug

#4236 Add equals() for AccessControlList
  modules/common/src/main/java/org/opencastproject/security/api/AccessControlList.java
Labels: enhancement, ELAN, java, small pull request

#4307 Publish Captions by Default
  etc/workflows/fast.yaml
Labels: configuration

#4322 Make Workflow Operation Docs Look Alike
  docs/guides/admin/docs/workflowoperationhandlers/analyze-tracks-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/comment-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/copy-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/encode-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/include-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/log-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/microsoft-azure-start-transcription-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/postmediapackage-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/probe-resolution-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/publish-youtube-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/retract-configure-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/retract-engage-aws-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/retract-engage-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/retract-oaipmh-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/retract-youtube-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/sanitize-adaptive-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/segmentpreviews-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/segmentvideo-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/select-streams-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/series-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/silence-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/snapshot-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/start-watson-transcription-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/start-workflow-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/tag-by-dcterm-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/theme-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/timelinepreviews-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/transfer-metadata-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/video-grid-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/waveform-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/zip-woh.md
Labels: documentation

#4329 Make Workflow Operation Docs Look Alike
  docs/guides/admin/docs/workflowoperationhandlers/add-catalog-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/amberscript-attach-transcription-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/amberscript-start-transcription-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/analyze-mediapackage-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/analyzeaudio-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/asset-delete-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/attach-watson-transcription-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/cleanup-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/composite-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/concat-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/configure-by-dcterm-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/coverimage-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/cropvideo-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/cut-marks-to-smil-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/defaults-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/demux-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/duplicate-event-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/editor-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/encode-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/error-resolution-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/execute-many-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/execute-once-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/export-wf-properties-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/extracttext-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/failing-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/google-speech-attach-transcription-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/google-speech-start-transcription-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/httpnotify-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/image-convert-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/imagetovideo-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/import-wf-properties-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/incident-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/ingestdownload-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/inspect-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/microsoft-azure-attach-transcription-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/move-storage-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/multiencode-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/normalizeaudio-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/partial-import-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/prepareav-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/process-smil-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/publish-configure-aws-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/publish-configure-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/publish-engage-aws-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/publish-oaipmh-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/republish-oaipmh-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/retract-configure-aws-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/retract-partial-aws-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/segmentpreviews-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/zip-woh.md
Labels: documentation

#4131 Add Tobira functionality in the admin UI
  etc/org.opencastproject.adminui.endpoint.SeriesEndpoint.cfg
  etc/security/mh_default_org.xml
  modules/admin-ui-frontend/app/index.html
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/newSeriesController.js
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/serieController.js
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/series-details.html
  modules/admin-ui-frontend/app/scripts/shared/partials/wizards/new-series.html
  modules/admin-ui-frontend/app/scripts/shared/resources/newSeriesTobiraResource.js
  modules/admin-ui-frontend/app/scripts/shared/resources/seriesResource.js
  modules/admin-ui-frontend/app/scripts/shared/resources/seriesTobiraResource.js
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-series/states.js
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-series/tobira.js
  modules/admin-ui-frontend/app/styles/components/_breadcrumbs.scss
  modules/admin-ui-frontend/app/styles/views/modals/_event-series.scss
  modules/admin-ui-frontend/app/styles/views/modals/_new-event-series.scss
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-de_DE.json
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui-frontend/test/test/unit/modules/events/controllers/newSeriesControllerSpec.js
  modules/admin-ui-frontend/test/test/unit/modules/events/controllers/serieControllerSpec.js
  modules/admin-ui-frontend/test/test/unit/shared/services/wizards/new-series/statesSpec.js
  modules/admin-ui/pom.xml
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/SeriesEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/tobira/TobiraException.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/tobira/TobiraService.java
  modules/admin-ui/src/main/resources/roles.txt
  modules/index-service/src/main/java/org/opencastproject/index/service/api/IndexService.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
Labels: admin-ui-feature-tracking

#4308 Save button for event/series "Access policy"-tab
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventController.js
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/serieController.js
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/event-details.html
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/series-details.html
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui-frontend/test/test/unit/modules/events/controllers/serieControllerSpec.js
Labels: admin-ui-feature-tracking

#4317 Fix NullPointerException when editor does not send subtitles
  modules/editor-service/src/main/java/org/opencastproject/editor/EditorServiceImpl.java
Labels: bug, needs attention, editor

#4328 Specify Units in Video Clips
  modules/videoeditor-ffmpeg-impl/src/main/java/org/opencastproject/videoeditor/ffmpeg/FFmpegEdit.java
  modules/videoeditor-ffmpeg-impl/src/main/java/org/opencastproject/videoeditor/impl/VideoClip.java
  modules/videoeditor-ffmpeg-impl/src/main/java/org/opencastproject/videoeditor/impl/VideoEditorServiceImpl.java
  modules/videoeditor-ffmpeg-impl/src/test/java/org/opencastproject/videoeditor/ffmpeg/FFmpegTest.java
Labels: codestyle

#4330 Enforce Workflow Operation Documentation Style
  docs/checkstyle/check-docs.sh
Labels: documentation, tests, codestyle

#4340 Fix saving thumbnails if no previous ones existed
  modules/editor-service/src/main/java/org/opencastproject/editor/EditorServiceImpl.java
Labels: bug

#4332 CVE-2022-42889 library upgrade
  pom.xml
Labels: maintenance

#4347 Changelog 12.4
  docs/guides/admin/docs/changelog.md
Labels: documentation

#4359 Make PostgreSQL no longer experimental
  docs/guides/admin/docs/configuration/database.md
Labels: documentation

#4156 Allow tags for ingesting attachments or catalogs via URL
  modules/ingest-service-api/src/main/java/org/opencastproject/ingest/api/IngestService.java
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/endpoint/IngestRestService.java
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/impl/IngestServiceImpl.java
  modules/ingest-service-impl/src/test/java/org/opencastproject/ingest/endpoint/IngestRestServiceTest.java
  modules/ingest-service-impl/src/test/java/org/opencastproject/ingest/impl/IngestServiceImplTest.java
Labels: enhancement, ELAN, java

#4348 Use System cURL for Tests
  .github/workflows/test-opencast-build.yml
Labels: tests

#4370 Correctly identify the master playlist in the Tobira harvest
  docs/guides/admin/docs/releasenotes/master-playlist-in-tobira-harvest.txt
  modules/tobira/src/main/java/org/opencastproject/tobira/impl/Item.java
Labels: ELAN

#4309 Add captions to Tobira harvest API (plus: avoid using deprecated method for creators.)
  modules/tobira/src/main/java/org/opencastproject/tobira/impl/Item.java
  modules/tobira/src/main/java/org/opencastproject/tobira/impl/TobiraEndpoint.java
Labels: ELAN

#4381 Fix workflow typo in docs
  docs/guides/admin/mkdocs.yml
Labels: documentation

#4295 Improve trigger on Dependabot Batcher for Paella7
  .github/workflows/dependabot-batcher.yml
Labels: hacktoberfest, dependencies, tests
