Repository opencast/opencast, pull requests merged in 2022-03, with the labels that each got.

#3438 Update MariaDB Driver
  docs/guides/admin/docs/configuration/database.md
  docs/guides/admin/docs/releasenotes/dropping-mysql-support.txt
  docs/guides/admin/docs/releasenotes/mariadb-connection-configuration.txt
  docs/guides/developer/docs/proposal-log.md
  etc/custom.properties
  modules/db/pom.xml
  pom.xml
Labels: maintenance, dependencies

#3520 Docs: Force same sample rate for audio files in PartialImport WOH encoding
  docs/guides/admin/docs/workflowoperationhandlers/partial-import-woh.md
Labels: documentation

#3517 Admin-ui-frontend migrate node-sass to sass
  modules/admin-ui-frontend/Gruntfile.js
  modules/admin-ui-frontend/app/styles/base/fontawesome/_fixed-width.scss
  modules/admin-ui-frontend/app/styles/base/fontawesome/_larger.scss
  modules/admin-ui-frontend/app/styles/base/fontawesome/_list.scss
  modules/admin-ui-frontend/app/styles/base/fontawesome/_variables.scss
  modules/admin-ui-frontend/app/styles/components/_popover.scss
  modules/admin-ui-frontend/app/styles/components/_stats.scss
  modules/admin-ui-frontend/app/styles/components/modals/_modal-base.scss
  modules/admin-ui-frontend/app/styles/components/modals/_nav.scss
  modules/admin-ui-frontend/app/styles/components/video/_video-editor.scss
  modules/admin-ui-frontend/app/styles/mixins/_mixins-config.scss
  modules/admin-ui-frontend/app/styles/vendor/bourbon/functions/_px-to-em.scss
  modules/admin-ui-frontend/app/styles/vendor/bourbon/functions/_strip-units.scss
  modules/admin-ui-frontend/app/styles/vendor/neat/grid/_private.scss
  modules/admin-ui-frontend/app/styles/vendor/neat/grid/_span-columns.scss
  modules/admin-ui-frontend/app/styles/views/modals/_edit-events.scss
  modules/admin-ui-frontend/package-lock.json
  modules/admin-ui-frontend/package.json
Labels: bug, dependencies, javascript

#3533 Add activemq upgrade note to 10.x upgrade guide
  docs/guides/admin/docs/upgrade.md
Labels: documentation

#3534 Fix Admin UI builds due to missing SASS
  modules/admin-ui-frontend/package-lock.json
  modules/admin-ui-frontend/package.json
Labels: bug

#3500 Code Cleanup
  modules/elasticsearch-impl/src/main/java/org/opencastproject/elasticsearch/impl/AbstractElasticsearchIndex.java
Labels: maintenance

#3506 Admin UI Node Version
  .github/workflows/test-admin-interface-frontend.yml
Labels: tests

#3507 Auto-update JavaScript Test libraries
  .github/workflows/auto-update-npm-libraries.yml
Labels: tests

#3197 Elasticsearch Retry Config
  docs/guides/admin/docs/configuration/elasticsearch.md
  docs/guides/admin/docs/releasenotes/elasticsearch-retry-config.txt
  etc/org.opencastproject.elasticsearch.index.ElasticsearchIndex.cfg
  modules/elasticsearch-impl/src/main/java/org/opencastproject/elasticsearch/impl/AbstractElasticsearchIndex.java
  modules/elasticsearch-index/pom.xml
  modules/elasticsearch-index/src/main/java/org/opencastproject/elasticsearch/index/ElasticsearchIndex.java
Labels: enhancement, needs attention, ELAN, SWITCH, java

#3540 Fix NPE when signing publication URLs
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
Labels: bug

#3546 Update Editor to 2022-03-22
  modules/editor/pom.xml
Labels: feature, editor

#3552 Fix version sorting in Matrix room bot
  .github/workflows/update-matrix-room.yml
Labels: maintenance

#3551 Silence npm auto update in the case where no updates are needed
  .github/workflows/auto-update-npm-libraries.yml
Labels: maintenance, tests, small pull request

#3549 Auto-update all Theodul JavaScript Test libraries
  .github/workflows/auto-update-npm-libraries.yml
  modules/engage-theodul-plugin-controls/package-lock.json
  modules/engage-theodul-plugin-controls/package.json
  modules/engage-theodul-plugin-custom-matomo/package-lock.json
  modules/engage-theodul-plugin-custom-matomo/package.json
  modules/engage-theodul-plugin-custom-mhConnection/package-lock.json
  modules/engage-theodul-plugin-custom-mhConnection/package.json
  modules/engage-theodul-plugin-custom-notifications/package-lock.json
  modules/engage-theodul-plugin-custom-notifications/package.json
  modules/engage-theodul-plugin-description/package-lock.json
  modules/engage-theodul-plugin-description/package.json
  modules/engage-theodul-plugin-tab-description/package-lock.json
  modules/engage-theodul-plugin-tab-description/package.json
  modules/engage-theodul-plugin-tab-downloads/package-lock.json
  modules/engage-theodul-plugin-tab-downloads/package.json
  modules/engage-theodul-plugin-tab-shortcuts/package-lock.json
  modules/engage-theodul-plugin-tab-shortcuts/package.json
  modules/engage-theodul-plugin-tab-slidetext/package-lock.json
  modules/engage-theodul-plugin-tab-slidetext/package.json
  modules/engage-theodul-plugin-video-videojs/package.json
Labels: dependencies, tests, has-conflicts

#3567 Fix workflow definition installation
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowDefinitionScanner.java
Labels: bug, configuration
