Repository opencast/opencast, pull requests merged in 2023-04, with the labels that each got.

#4737 remove static dependencies on publication service event handlers
  modules/conductor/src/main/java/org/opencastproject/event/handler/ConductingEpisodeUpdatedEventHandler.java
  modules/conductor/src/main/java/org/opencastproject/event/handler/ConductingSeriesUpdatedEventHandler.java
  modules/conductor/src/main/java/org/opencastproject/event/handler/SearchUpdatedEventHandler.java
Labels: UoM

#4738 Enable Whisper English Translation
  docs/guides/admin/docs/workflowoperationhandlers/speechtotext-woh.md
  etc/org.opencastproject.speechtotext.impl.engine.VoskEngine.cfg
  modules/speech-to-text-api/src/main/java/org/opencastproject/speechtotext/api/SpeechToTextEngine.java
  modules/speech-to-text-api/src/main/java/org/opencastproject/speechtotext/api/SpeechToTextService.java
  modules/speech-to-text-impl/pom.xml
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/SpeechToTextServiceImpl.java
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/endpoint/SpeechToTextServiceRestEndpoint.java
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/VoskEngine.java
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/WhisperEngine.java
  modules/speech-to-text-impl/src/test/java/org/opencastproject/speechtotext/impl/SpeechToTextServiceImplTest.java
  modules/speech-to-text-remote/src/main/java/org/opencastproject/speechtotext/remote/SpeechToTextServiceRemoteImpl.java
  modules/speech-to-text-workflowoperation/src/main/java/org/opencastproject/workflow/handler/speechtotext/SpeechToTextWorkflowOperationHandler.java
Labels: enhancement, java, educast.nrw

#4843 Fixed pagination when reindexing asset manager
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerImpl.java
Labels: bug, UoM

#4206 Changed rebuild order and added rebuild indicator
  etc/security/mh_default_org.xml
  modules/admin-ui-frontend/app/index.html
  modules/admin-ui-frontend/app/scripts/shared/controllers/applicationController.js
  modules/admin-ui-frontend/app/scripts/shared/services/indexRebuild.js
  modules/admin-ui-frontend/app/styles/components/_header.scss
  modules/admin-ui-frontend/app/styles/main.scss
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_GB.json
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui-frontend/test/test/unit/shared/controllers/applicationControllerSpec.js
  modules/elasticsearch-index/pom.xml
  modules/elasticsearch-index/src/main/java/org/opencastproject/elasticsearch/index/endpoint/IndexEndpoint.java
  modules/elasticsearch-index/src/main/java/org/opencastproject/elasticsearch/index/objects/event/Event.java
  modules/elasticsearch-index/src/main/java/org/opencastproject/elasticsearch/index/rebuild/IndexRebuildService.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: admin-ui-feature-tracking

#4877 Engage UI docs
  docs/guides/admin/docs/modules/mediamodule.configuration.md
Labels: documentation

#4864 Remove dead `CONFIG_OPTIONS` from WOHs
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/SanitizeAdaptiveWorkflowOperationHandler.java
  modules/transcription-service-workflowoperation/src/main/java/org/opencastproject/transcription/workflowoperation/AmberscriptAttachTranscriptionOperationHandler.java
  modules/transcription-service-workflowoperation/src/main/java/org/opencastproject/transcription/workflowoperation/AmberscriptStartTranscriptionOperationHandler.java
  modules/transcription-service-workflowoperation/src/main/java/org/opencastproject/transcription/workflowoperation/AttachTranscriptionOperationHandler.java
  modules/transcription-service-workflowoperation/src/main/java/org/opencastproject/transcription/workflowoperation/GoogleSpeechAttachTranscriptionOperationHandler.java
  modules/transcription-service-workflowoperation/src/main/java/org/opencastproject/transcription/workflowoperation/GoogleSpeechStartTranscriptionOperationHandler.java
  modules/transcription-service-workflowoperation/src/main/java/org/opencastproject/transcription/workflowoperation/MicrosoftAzureStartTranscriptionOperationHandler.java
  modules/transcription-service-workflowoperation/src/main/java/org/opencastproject/transcription/workflowoperation/StartTranscriptionOperationHandler.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/AbstractWorkflowOperationHandler.java
Labels: enhancement, maintenance, ELAN, java, small pull request

#4870 TermsFeed Cookie Consent NOTICE
  NOTICES
Labels: maintenance, documentation, small pull request, educast.nrw

#4874 Upload Allinone as Actions Workflow Artifact
  .github/workflows/test-opencast-build.yml
Labels: tests

#4721 Clarify S3 docs
  docs/guides/admin/docs/modules/awss3archive.md
Labels: documentation
