Repository opencast/opencast, pull requests merged in 2023-05, with the labels that each got.

#4921 Fix REST docs login problem
  docs/checkstyle/eslintrc.js
  modules/runtime-info-ui/src/main/resources/ui/rest_docs.html
  modules/runtime-info-ui/src/main/resources/ui/scripts/rest_docs.js
Labels: bug

#4925 Ensure all plugin jars are present in tarballs.
  assemblies/pom.xml
  docs/checkstyle/check-config.sh
Labels: bug

#4923 Mitigate not loading ACLs
  etc/org.apache.felix.fileinstall-acl.cfg
Labels: bug

#4951 Allow opencast to share the oc-remember-me cookie between nodes
  docs/guides/admin/docs/releasenotes/global-oc-remember-me-cookie.txt
  etc/security/mh_default_org.xml
  modules/kernel/src/main/java/org/opencastproject/kernel/security/SystemTokenRememberMeUtils.java
Labels: feature, ELAN, small pull request

#4962 Opencast 12.11 Release Notes
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#4869 [Whisper] Fixes automatic language detection
  docs/guides/admin/docs/installation/source-linux.md
  docs/guides/admin/docs/modules/transcription.modules/whisper.md
  docs/guides/admin/docs/workflowoperationhandlers/speechtotext-woh.md
  modules/speech-to-text-api/src/main/java/org/opencastproject/speechtotext/api/SpeechToTextEngine.java
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/SpeechToTextServiceImpl.java
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/WhisperEngine.java
  modules/speech-to-text-workflowoperation/src/main/java/org/opencastproject/workflow/handler/speechtotext/SpeechToTextWorkflowOperationHandler.java
Labels: needs attention, java, educast.nrw
