Repository opencast/opencast, pull requests merged in 2023-12, with the labels that each got.

#5467 Clean up build config
  assemblies/resources/build.xml
Labels: maintenance

#5475 Fix update translations workflow
  .crowdin.yaml
Labels: bug

#5433 Prepare opencast 15 release notes
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/releasenotes.md
  docs/guides/admin/docs/releasenotes/admin-interface.txt
  docs/guides/admin/docs/releasenotes/analyze-mp-publication-variables
  docs/guides/admin/docs/releasenotes/editor-woh-tags
  docs/guides/admin/docs/releasenotes/no-snapshot-on-asset-upload.txt
  docs/guides/admin/docs/releasenotes/old-editor-restrictions
  docs/guides/admin/docs/releasenotes/remove-metadata-from-image.txt
  docs/guides/admin/docs/releasenotes/speech-to-text-tags.txt
  docs/guides/admin/docs/releasenotes/studio-series-select
  docs/guides/admin/docs/releasenotes/subtitles-as-first-class-citizens.txt
  docs/guides/admin/docs/upgrade.md
Labels: documentation

#5486 Docs: Make Developer Overview page more verbose
  docs/guides/developer/docs/index.md
Labels: documentation

#5493 Fix broken link in markdown documentation
  docs/guides/admin/docs/configuration/youtubepublication.md
Labels: bug, documentation
