Repository opencast/opencast, pull requests merged in 2023-01, with the labels that each got.

#4563 Fix Wowza signing time scale
  modules/urlsigning-service-impl/src/main/java/org/opencastproject/security/urlsigning/provider/impl/WowzaUrlSigningProvider.java
  modules/urlsigning-service-impl/src/test/java/org/opencastproject/security/urlsigning/provider/impl/WowzaUrlSigningProviderTest.java
Labels: bug

#4595 Document feature pull request targetting rules
  docs/guides/developer/docs/development-process.md
Labels: documentation

#4590 Add Tag-Engage Workflow Operation Handler
  docs/guides/admin/docs/releasenotes/tag-engage-woh
  docs/guides/admin/docs/workflowoperationhandlers/index.md
  docs/guides/admin/docs/workflowoperationhandlers/tag-engage-woh.md
  docs/guides/admin/mkdocs.yml
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/TagEngageWorkflowOperationHandler.java
Labels: ELAN, java

#4516 Change default hotkeys for create dialogs in admin UI
  etc/org.opencastproject.organization-mh_default_org.cfg
Labels: ELAN, small pull request, admin-ui-feature-tracking

#4599 Fix Syntax Error
  modules/distribution-service-download/src/main/java/org/opencastproject/distribution/download/DownloadDistributionServiceImpl.java
Labels: bug, needs attention

#4478 Bug fix: publish engage woh with merge SKIP the operation if media package not in search index
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/test/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandlerTest.java
  modules/distribution-workflowoperation/src/test/resources/distribution_job_payload.txt
  modules/distribution-workflowoperation/src/test/resources/distribution_merge_job_payload.txt
  modules/distribution-workflowoperation/src/test/resources/mp_already_published.xml
  modules/distribution-workflowoperation/src/test/resources/mp_to_be_merged.xml
  modules/distribution-workflowoperation/src/test/resources/mp_to_be_published.xml
Labels: bug, harvard-dce

#4607 Add Opencast 13.1 release notes
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#4612 Opencast 12.7 Changelog
  docs/guides/admin/docs/changelog.md
Labels: documentation

#4653 Document all available workflow operations
  docs/guides/admin/docs/releasenotes.md
  docs/guides/admin/docs/workflowoperationhandlers/index.md
  docs/guides/admin/docs/workflowoperationhandlers/mattermost-notify-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/notification.md
  docs/guides/admin/docs/workflowoperationhandlers/speechtotext-woh.md
  docs/guides/admin/mkdocs.yml
Labels: documentation

#4619 Fix calendar.json endpoint
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
Labels: bug

#4654 Add webvtt-to-cutmarks to list of workflow operations
  docs/guides/admin/docs/modules/transcription.modules/vosk.md
  docs/guides/admin/docs/modules/transcription.modules/whisper.md
  docs/guides/admin/docs/workflowoperationhandlers/index.md
  docs/guides/admin/docs/workflowoperationhandlers/webvtt-to-cutmarks.md
Labels: documentation

#4596 Always show save button for series access rights
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/series-details.html
Labels: bug, ELAN, java, small pull request

#4620 Also check custom actions for unsaved ACL changes
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventController.js
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/serieController.js
Labels: bug, ELAN, javascript, admin-ui-feature-tracking
