Repository opencast/opencast, pull requests merged in 2023-09, with the labels that each got.

#5062 Dont allow to delete user with active workflow in Admin UI
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/UsersEndpoint.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowInstance.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowService.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabase.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabaseImpl.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/endpoint/WorkflowRestService.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
  modules/workflow-service-remote/src/main/java/org/opencastproject/workflow/remote/WorkflowServiceRemoteImpl.java
Labels: bug, small pull request

#5164 Fix editing custom actions in the ACL editor
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventController.js
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-event/access.js
Labels: ELAN, small pull request, javascript

#5169 Copy active inputs between CAs if they have the same set of inputs
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventController.js
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/event-details.html
  modules/admin-ui-frontend/app/scripts/shared/resources/eventSchedulingResource.js
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
Labels: enhancement, ELAN, java, javascript, admin-ui-feature-tracking

#5171 Skip deleting non existent file
  modules/working-file-repository-service-impl/src/main/java/org/opencastproject/workingfilerepository/impl/WorkingFileRepositoryImpl.java
Labels: bug, good first issue

#5177 Fix wrong failedOperation characterers in send email docs WoH and improves Freemaker documentation.
  docs/guides/admin/docs/workflowoperationhandlers/send-email-woh.md
Labels: bug, documentation, small pull request, educast.nrw

#5228 Fix AmberScript transcription failing if video contains no speech
  modules/transcription-service-amberscript/src/main/java/org/opencastproject/transcription/amberscript/AmberscriptTranscriptionService.java
  modules/transcription-service-api/src/main/java/org/opencastproject/transcription/api/TranscriptionServiceException.java
  modules/transcription-service-workflowoperation/src/main/java/org/opencastproject/transcription/workflowoperation/AmberscriptAttachTranscriptionOperationHandler.java
Labels: bug

#5232 Logging of delete snapshot workflow operation
  modules/asset-manager-workflowoperation/src/main/java/org/opencastproject/workflow/handler/assetmanager/AssetManagerDeleteWorkflowOperationHandler.java
Labels: bug

#5236 Fix NPE when removing a workflow without creator
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: bug

#5237 Prevent concurrent cleanups
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowCleanupScanner.java
Labels: bug

#5194 Fix Crowdin Sources
  .crowdin.yaml
Labels: bug

#5239 Skip publications when removing temporary files
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: bug

#5249 Prune Committer List
  docs/guides/developer/docs/participate/committer.md
Labels: documentation

#5230 Fix static file service exception on non-existing file
  modules/static-file-service-api/src/main/java/org/opencastproject/staticfiles/endpoint/StaticFileRestService.java
  modules/static-file-service-api/src/test/java/org/opencastproject/staticfiles/endpoint/StaticFileRestServiceTest.java
Labels: bug

#4684 Ensure workflows have an associated org after upgrade
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowInstance.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabase.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabaseImpl.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: bug

#5101 Add whisper-ctranslate2 flags to WhisperEngine.java
  docs/guides/admin/docs/modules/transcription.modules/whisper.md
  etc/org.opencastproject.speechtotext.impl.engine.WhisperEngine.cfg
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/WhisperEngine.java
Labels: enhancement

#5023 Remove Track Selection Restrictions from the Old Editor
  docs/guides/admin/docs/releasenotes/old-editor-restrictions
  modules/admin-ui-frontend/app/scripts/modules/events/subresources/controllers/toolsController.js
  modules/admin-ui-frontend/app/scripts/modules/events/subresources/partials/tools.html
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
Labels: javascript

#5126 Improves Dev docs
  docs/guides/developer/docs/develop/development-tips.md
  docs/guides/developer/docs/develop/setup-opencast-for-develop.md
  docs/guides/developer/mkdocs.yml
Labels: documentation, educast.nrw

#4651 Add studio series dropdown selection
  assemblies/karaf-features/src/main/feature/feature.xml
  etc/security/mh_default_org.xml
  modules/studio-service/pom.xml
  modules/studio-service/src/main/java/org/opencastproject/studio/endpoint/StudioEndpoint.java
  modules/studio-service/src/main/java/org/opencastproject/studio/endpoint/dto/SeriesDto.java
  modules/studio-service/src/test/java/org/opencastproject/studio/endpoint/assembler/SeriesDtoTest.java
  pom.xml
Labels: feature, studio

#5260 Update ES index before triggering event handlers from AssetManager
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerImpl.java
Labels: bug, ELAN, java

#5256 Fix Translation Updates
  .github/workflows/update-translations.yml
Labels: bug

#5247 Don't take snapshot on asset upload before workflow
  docs/guides/admin/docs/releasenotes/no-snapshot-on-asset-upload.txt
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
Labels: ELAN, java

#5243 Extend analyze-mp for tag variables
  docs/guides/admin/docs/releasenotes/analyze-mp-tag-variables
  docs/guides/admin/docs/workflowoperationhandlers/analyze-mediapackage-woh.md
  modules/analyze-mediapackage-workflowoperation/pom.xml
  modules/analyze-mediapackage-workflowoperation/src/main/java/org/opencastproject/workflow/handler/analyzemediapackage/AnalyzeMediapackageWorkflowOperationHandler.java
Labels: enhancement, ELAN, java

#5248 Extend Asset Upload Workflow for Captions
  etc/workflows/partial-error.xml
  etc/workflows/partial-process-uploaded-captions.xml
  etc/workflows/publish-uploaded-assets.xml
Labels: subtitles-rework, workflows
