Repository opencast/opencast, pull requests merged in 2023-07, with the labels that each got.

#5064 Log dispatch interval in seconds, not milliseconds
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/JobDispatcher.java
Labels: bug

#5052 Fix tainted canvas in editor thumbnail extractor
  modules/admin-ui-frontend/app/scripts/shared/partials/player.html
Labels: bug, small pull request, javascript

#5055 Dont copy media files to new scheduled event
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/Ingestor.java
Labels: bug

#5058 Allow deletion of reference users from the Admin UI
  modules/admin-ui-frontend/app/scripts/modules/users/partials/userActionsCell.html
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/UsersEndpoint.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaUserReferenceProvider.java
Labels: enhancement, admin-ui-feature-tracking

#5105 Increase index rebuild logging frequency for batches
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerImpl.java
  modules/event-comment/src/main/java/org/opencastproject/event/comment/persistence/EventCommentDatabaseServiceImpl.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/SeriesServiceImpl.java
  modules/themes/src/main/java/org/opencastproject/themes/persistence/ThemesServiceDatabaseImpl.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: enhancement

#5040 Enable Tobira adopter stats tracking
  modules/admin-ui-frontend/app/scripts/shared/resources/adopterStatisticSummaryResource.js
  modules/adopter-registration-impl/pom.xml
  modules/adopter-registration-impl/src/main/java/org/opencastproject/adopter/statistic/ScheduledDataCollector.java
  modules/adopter-registration-impl/src/main/java/org/opencastproject/adopter/statistic/Sender.java
  modules/tobira/pom.xml
  modules/tobira/src/main/java/org/opencastproject/tobira/impl/TobiraEndpoint.java
Labels: enhancement

#5063 Allow engage ui and ltitools to handle non-16/9 thumbnails
  modules/engage-ui/src/main/resources/ui/css/engage-ui.css
  modules/lti/src/App.css
  modules/lti/src/components/Series.tsx
Labels: small pull request

#5102 Add endpoint to get languages & licenses
  docs/guides/developer/docs/api/listprovider-api.md
  docs/guides/developer/mkdocs.yml
  modules/external-api/pom.xml
  modules/external-api/src/main/java/org/opencastproject/external/common/ApiMediaType.java
  modules/external-api/src/main/java/org/opencastproject/external/common/ApiVersion.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/BaseEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/CaptureAgentsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/GroupsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/ListProviderEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SecurityEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SeriesEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/StatisticsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowDefinitionsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowsEndpoint.java
  modules/external-api/src/test/java/org/opencastproject/external/common/ApiMediaTypeTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/BaseEndpointTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/ListProviderEndpointTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/TestListProviderEndpoint.java
Labels: feature, possibly controversial

#5117 Only show Asset Upload for options of correct type
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/event-details.html
Labels: bug, ELAN, java, small pull request, admin-ui-feature-tracking

#5108 Mark tag operation as skipped if nothing happened
  modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/TagWorkflowOperationHandler.java
Labels: enhancement, ELAN, java, small pull request

#5115 Fix index rebuild
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerImpl.java
  modules/event-comment/src/main/java/org/opencastproject/event/comment/persistence/EventCommentDatabaseServiceImpl.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/SeriesServiceImpl.java
  modules/themes/src/main/java/org/opencastproject/themes/persistence/ThemesServiceDatabaseImpl.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: bug
