Repository opencast/opencast, pull requests merged in 2023-10, with the labels that each got.

#4617 Adds the 'add-force-flavors' config to the publish-engage workflow
  docs/guides/admin/docs/workflowoperationhandlers/publish-engage-woh.md
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandler.java
  modules/distribution-workflowoperation/src/test/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandlerTest.java
Labels: enhancement, ELAN, java

#5305 Fix Headless Firefox in Selenium Tests
  modules/lti/requirements.txt
  modules/lti/selenium-tests
Labels: bug, tests

#5313 Update events in archive in order on series change
  modules/conductor/src/main/java/org/opencastproject/event/handler/AssetManagerUpdatedEventHandler.java
Labels: bug, ELAN

#5311 Remove Internal Logger
  modules/common/src/main/java/org/opencastproject/util/DateTimeSupport.java
  modules/common/src/main/java/org/opencastproject/util/Log.java
  modules/common/src/test/java/org/opencastproject/util/LogTest.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SecurityEndpoint.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
Labels: maintenance

#5314 Do not nest GH Artifacts
  .github/workflows/test-opencast-build.yml
Labels: maintenance

#4955 Asset manager multiple storage
  etc/custom.properties
  modules/asset-manager-storage-fs/pom.xml
  modules/asset-manager-storage-fs/src/main/java/org/opencastproject/assetmanager/storage/impl/fs/AbstractFileSystemAssetStore.java
  modules/asset-manager-storage-fs/src/main/java/org/opencastproject/assetmanager/storage/impl/fs/OsgiFileSystemAssetStore.java
  modules/asset-manager-storage-fs/src/test/java/org/opencastproject/assetmanager/storage/impl/fs/AbstractFileSystemAssetStoreTest.java
  modules/shared-filesystem-utils/src/main/java/org/opencastproject/assetmanager/util/AssetPathUtils.java
  modules/workspace-impl/src/main/java/org/opencastproject/workspace/impl/WorkspaceImpl.java
Labels: feature

#5352 Set generator tags in speech-to-text WOH
  docs/guides/admin/docs/releasenotes/speech-to-text-tags.txt
  docs/guides/admin/docs/workflowoperationhandlers/speechtotext-woh.md
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/SpeechToTextServiceImpl.java
  modules/speech-to-text-workflowoperation/src/main/java/org/opencastproject/workflow/handler/speechtotext/SpeechToTextWorkflowOperationHandler.java
Labels: enhancement, ELAN

#5342 Add option to pass additional args to Whisper
  etc/org.opencastproject.speechtotext.impl.engine.WhisperEngine.cfg
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/WhisperEngine.java
Labels: enhancement, ELAN, java

#5354 Get thumbnail for editor frontend from archive
  modules/editor-service/src/main/java/org/opencastproject/editor/EditorServiceImpl.java
Labels: ELAN, java, editor

#5353 Remove metadata layer from preview image (presenter)
  docs/guides/admin/docs/releasenotes/remove-metadata-from-image.txt
  etc/workflows/partial-publish.xml
Labels: ELAN, configuration, possibly controversial

#5359 Docs: Hide bot PRs in changelog
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/css/extra.css
Labels: documentation

#5344 Fix external api listprovider header
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/ListProviderEndpoint.java
Labels: bug, api change

#5340 Update Editor to 2023-10-17
  etc/ui-config/mh_default_org/editor/editor-settings.toml
  modules/editor/pom.xml
Labels: editor

#5367 Re-add details css for docs (reverts part of PR 5359)
  docs/guides/admin/docs/css/extra.css
Labels: bug

#5269 Fix custom roles pattern now working in access policy tab
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventController.js
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/serieController.js
  modules/admin-ui-frontend/app/scripts/modules/users/controllers/aclController.js
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/acl-details.html
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/event-details.html
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/series-details.html
  modules/admin-ui-frontend/app/scripts/shared/partials/wizards/new-acl.html
  modules/admin-ui-frontend/app/scripts/shared/partials/wizards/new-event.html
  modules/admin-ui-frontend/app/scripts/shared/partials/wizards/new-series.html
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-acl/access.js
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-event/access.js
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-series/access.js
Labels: bug, javascript

#5338 Fixes connection test on NCast Hydra with CA user
  etc/security/mh_default_org.xml
Labels: bug, configuration

#5348 Update Youtube Publication documentation
  docs/guides/admin/docs/modules/youtubepublication.md
  docs/guides/admin/docs/workflowoperationhandlers/publish-youtube-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/retract-youtube-woh.md
Labels: documentation

#5337 Document Registration
  docs/guides/admin/docs/index.md
  docs/guides/admin/docs/registration-example.jpg
  docs/guides/admin/docs/registration-launch.jpg
  docs/guides/admin/docs/registration.md
  docs/guides/admin/mkdocs.yml
Labels: documentation
