Repository opencast/opencast, pull requests merged in 2023-03, with the labels that each got.

#4683 Fix typo and adds recomendations to whisper doc
  docs/guides/admin/docs/modules/transcription.modules/whisper.md
Labels: documentation

#4487 Seperate user and non-user roles in the access policy modal in various details views in the Admin UI
  docs/guides/admin/docs/configuration/admin-ui/role-based-visibility.md
  etc/listproviders/acl.default.create.properties
  etc/org.opencastproject.adminui.impl.AdminUIConfiguration.cfg
  etc/security/mh_default_org.xml
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventController.js
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/newEventController.js
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/newSeriesController.js
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/serieController.js
  modules/admin-ui-frontend/app/scripts/modules/users/controllers/aclController.js
  modules/admin-ui-frontend/app/scripts/modules/users/controllers/newAclController.js
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/acl-details.html
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/event-details.html
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/series-details.html
  modules/admin-ui-frontend/app/scripts/shared/partials/wizards/new-acl.html
  modules/admin-ui-frontend/app/scripts/shared/partials/wizards/new-event.html
  modules/admin-ui-frontend/app/scripts/shared/partials/wizards/new-series.html
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-acl/access.js
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-event/access.js
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-series/access.js
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-de_DE.json
  modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json
  modules/admin-ui-frontend/resources/roles.txt
  modules/admin-ui-frontend/test/test/unit/modules/events/controllers/eventControllerSpec.js
  modules/admin-ui-frontend/test/test/unit/modules/events/controllers/newEventControllerSpec.js
  modules/admin-ui-frontend/test/test/unit/modules/events/controllers/newSeriesControllerSpec.js
  modules/admin-ui-frontend/test/test/unit/modules/events/controllers/serieControllerSpec.js
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/SeriesEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/impl/AdminUIConfiguration.java
  modules/admin-ui/src/main/resources/roles.txt
  modules/authorization-manager/src/main/java/org/opencastproject/authorization/xacml/manager/util/AccessInformationUtil.java
Labels: ELAN, javascript, admin-ui-feature-tracking, possibly controversial

#4669 Allow CA users to retract live publications and update search
  modules/common/src/main/java/org/opencastproject/mediapackage/MediaPackage.java
  modules/common/src/main/java/org/opencastproject/mediapackage/MediaPackageImpl.java
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImpl.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/SearchServiceImpl.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/persistence/SearchServiceDatabaseImpl.java
Labels: bug, ELAN, java

#4764 Editor remote enforce charset for StringEntity
  modules/editor-service-remote/src/main/java/org/opencastproject/editor/remote/EditorServiceRemoteImpl.java
Labels: bug

#4717 Shows event Title on Paella 7 browser tab
  modules/engage-paella-player-7/src/index.js
Labels: enhancement, small pull request, educast.nrw

#4515 Allow hotkeys in create dialogs in input elements
  modules/admin-ui-frontend/app/scripts/shared/directives/wizardDirective.js
  modules/admin-ui-frontend/app/scripts/shared/services/hotkeysService.js
Labels: ELAN, small pull request, admin-ui-feature-tracking

#4799 Sets values in specific config file to default
  etc/listproviders/acl.default.create.properties
Labels: bug, configuration

#4814 Opencast 12.10 Release Notes
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/releasenotes.md
Labels: documentation
