Repository opencast/opencast, pull requests merged in 2024-07, with the labels that each got.

#5862 Remove prepared flavor
  docs/guides/admin/docs/releasenotes/remove-prepared-flavor.txt
  etc/org.opencastproject.editor.EditorServiceImpl.cfg
  etc/workflows/partial-process-uploaded-captions.xml
  etc/workflows/partial-publish.xml
  etc/workflows/publish-uploaded-assets.xml
  modules/editor-service-api/src/test/resources/edit.json
  modules/editor-service-api/src/test/resources/editWithoutWorkflow.json
  modules/editor-service/src/main/java/org/opencastproject/editor/EditorServiceImpl.java
Labels: configuration, possibly controversial

#5997 Add a connection from presentation to OpenSearch in firewall diagram
  docs/guides/admin/docs/configuration/firewall.md
Labels: documentation

#5972 Fix distributed OC 16
  modules/playlists/pom.xml
  modules/playlists/src/main/java/org/opencastproject/playlists/PlaylistService.java
Labels: bug, needs attention

#5958 Remove redundant `groupId` declarations
  modules/crop-api/pom.xml
  modules/crop-ffmpeg/pom.xml
  modules/crop-remote/pom.xml
  modules/crop-workflowoperation/pom.xml
  modules/dictionary-hunspell/pom.xml
  modules/dictionary-none/pom.xml
  modules/dictionary-regexp/pom.xml
  modules/execute-api/pom.xml
  modules/execute-impl/pom.xml
  modules/execute-remote/pom.xml
  modules/execute-workflowoperation/pom.xml
  modules/ingest-download-service-api/pom.xml
  modules/ingest-download-service-remote/pom.xml
  modules/oaipmh-persistence/pom.xml
  modules/presets/pom.xml
  modules/publication-service-configurable-remote/pom.xml
  modules/publication-service-configurable/pom.xml
  modules/publication-service-oaipmh-remote/pom.xml
  modules/publication-service-oaipmh/pom.xml
  modules/silencedetection-api/pom.xml
  modules/silencedetection-impl/pom.xml
  modules/silencedetection-remote/pom.xml
  modules/sox-api/pom.xml
  modules/sox-impl/pom.xml
  modules/sox-remote/pom.xml
  modules/videoeditor-api/pom.xml
  modules/videoeditor-remote/pom.xml
Labels: maintenance, ELAN, good first issue, quick review

#5976 Rescue admin interface settings from deprecated section
  etc/org.opencastproject.organization-mh_default_org.cfg
Labels: configuration

#6000 Opencast 16.1 Release Notes
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#5975 Cluster Test
  .github/multi-node-test-setup
  .github/workflows/test-opencast-build.yml
Labels: tests

#5973 URL encode username in Stud.IP user provider
  modules/userdirectory-studip/src/main/java/org/opencastproject/userdirectory/studip/StudipUserProviderFactory.java
  modules/userdirectory-studip/src/main/java/org/opencastproject/userdirectory/studip/StudipUserProviderInstance.java
Labels: bug

#6021 Update Editor to 2024-07-12
  modules/editor/pom.xml
Labels: editor

#6029 Modernize cluster install docs
  docs/guides/admin/docs/installation/multiple-servers.md
Labels: documentation

#6012 Use current docker images for development
  docs/scripts/devel-dependency-containers/docker-compose-all-sql.yml
  docs/scripts/devel-dependency-containers/docker-compose-mariadb.yml
  docs/scripts/devel-dependency-containers/docker-compose-postgresql.yml
Labels: maintenance

#6017 Fix docs of `publish-engage` WOHs
  docs/guides/admin/docs/workflowoperationhandlers/publish-engage-aws-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/publish-engage-woh.md
Labels: documentation, elan e.V., quick review

#6030 Downgrade Editor to 2024-06-11
  modules/editor/pom.xml
Labels: bug

#6034 Fix Updating Engage for Non-Admins
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/SearchServiceIndex.java
Labels: bug, needs attention

#6006 Update karaf version to 4.4.6
  modules/db/pom.xml
  modules/security-shibboleth/pom.xml
  pom.xml
Labels: dependencies

#5913 Add new Workflow Operation: Subtitle Timeshift
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/admin/docs/workflowoperationhandlers/index.md
  docs/guides/admin/docs/workflowoperationhandlers/subtitle-timeshift-woh.md
  docs/guides/admin/mkdocs.yml
  etc/workflows/partial-publish.xml
  etc/workflows/partial-theming.xml
  modules/subtitle-timeshift-workflowoperation/pom.xml
  modules/subtitle-timeshift-workflowoperation/src/main/java/org/opencastproject/workflow/handler/subtitletimeshift/SubtitleTimeshiftWorkflowOperationHandler.java
  pom.xml
Labels: feature

#6042 Properly handle ACL publication for non-admins
  modules/search-service-impl/pom.xml
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/SearchServiceIndex.java
Labels: bug, needs attention

#6057 Fix version of subtitle timeshift operation
  modules/subtitle-timeshift-workflowoperation/pom.xml
Labels: bug
