Repository opencast/opencast, pull requests merged in 2024-05, with the labels that each got.

#5752 Reformat new admin UI `pom.xml`
  modules/admin-ui-interface/pom.xml
Labels: maintenance, ELAN, good first issue, quick review

#5756 Fix deleting user references from the admin UI
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/UsersEndpoint.java
Labels: bug, ELAN

#5743 Change Playlist Update behaviour
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/developer/docs/architecture/api/playlists-api.md
  modules/external-api/pom.xml
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/PlaylistsEndpoint.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/PlaylistsEndpointTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/TestPlaylistsEndpoint.java
  modules/playlists/pom.xml
  modules/playlists/src/main/java/org/opencastproject/playlists/PlaylistRestService.java
  modules/playlists/src/main/java/org/opencastproject/playlists/PlaylistService.java
Labels: api change, ELAN

#5764 Speed up starting and stopping the OpenSearch dev container
  docs/scripts/devel-dependency-containers/docker-compose-all-sql.yml
  docs/scripts/devel-dependency-containers/docker-compose-mariadb.yml
  docs/scripts/devel-dependency-containers/docker-compose-postgresql.yml
  docs/scripts/devel-dependency-containers/docker-compose.yml
Labels: ELAN, quick review

#5765 Handle missing tags in Paella Player 7
  modules/engage-paella-player-7/src/js/EpisodeConversor.js
Labels: bug, ELAN, javascript, player

#5809 Fix Fixed Feature Version
  assemblies/karaf-features/src/main/feature/feature.xml
Labels: bug

#5769 Document Translation Change Rules
  docs/guides/developer/docs/localization.md
Labels: documentation

#5830 ESLint nitpicks in the `lti` module
  modules/lti/.eslintrc.json
  modules/lti/package.json
Labels: enhancement, maintenance, ELAN, good first issue, quick review, javascript

#5831 Update ESLint
  .github/dependabot.yml
  docs/checkstyle/eslint-config/index.js
  docs/checkstyle/eslint-config/package-lock.json
  docs/checkstyle/eslint-config/package.json
  docs/checkstyle/eslintrc.js
  modules/admin-ui-frontend/.eslintignore
  modules/admin-ui-frontend/.eslintrc.js
  modules/admin-ui-frontend/.npmrc
  modules/admin-ui-frontend/app/scripts/shared/directives/opencastScrollGlue.js
  modules/admin-ui-frontend/app/scripts/shared/directives/sanitizeXMLDirective.js
  modules/admin-ui-frontend/app/scripts/shared/resources/statisticsResource.js
  modules/admin-ui-frontend/eslint.config.js
  modules/admin-ui-frontend/package-lock.json
  modules/admin-ui-frontend/package.json
  modules/engage-paella-player-7/.eslintrc.js
  modules/engage-paella-player-7/.npmrc
  modules/engage-paella-player-7/eslint.config.js
  modules/engage-paella-player-7/package-lock.json
  modules/engage-paella-player-7/package.json
  modules/engage-ui/.npmrc
  modules/engage-ui/eslint.config.js
  modules/engage-ui/package-lock.json
  modules/engage-ui/package.json
  modules/runtime-info-ui/.npmrc
  modules/runtime-info-ui/eslint.config.js
  modules/runtime-info-ui/package-lock.json
  modules/runtime-info-ui/package.json
Labels: maintenance, ELAN, dependencies, javascript

#5832 Log Excessively Large Jobs Status
  modules/common/src/main/java/org/opencastproject/job/api/AbstractJobProducer.java
Labels: maintenance

#5758 Move multiple series title check logic
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/SeriesListProvider.java
  modules/list-providers-service/src/main/java/org/opencastproject/list/impl/ListProvidersServiceImpl.java
Labels: maintenance
