Repository opencast/opencast, pull requests merged in 2024-04, with the labels that each got.

#5675 Add synchronous deletion to Search API
  modules/search-service-api/src/main/java/org/opencastproject/search/api/SearchService.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/endpoint/SearchRestService.java
  modules/search-service-remote/src/main/java/org/opencastproject/search/remote/SearchServiceRemoteImpl.java
Labels: enhancement, api change, ELAN, java

#5686 Fix editor track selection for updating tags
  modules/videoeditor-ffmpeg-impl/src/main/java/org/opencastproject/videoeditor/impl/VideoEditorServiceImpl.java
  modules/videoeditor-workflowoperation/src/main/java/org/opencastproject/workflow/handler/videoeditor/VideoEditorWorkflowOperationHandler.java
Labels: bug

#5749 Documenting new RM selection rules
  docs/guides/developer/docs/participate/proposal-log.md
  docs/guides/developer/docs/participate/release-manager.md
Labels: documentation
