Repository opencast/opencast, pull requests merged in 2024-06, with the labels that each got.

#5871 Fix 500 error in workflow service REST endpoint "update" (fixes #5870)
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/JaxbWorkflowInstance.java
Labels: bug, harvard-dce

#5869 Fix for event state when workflow is paused when rebuilding ES index (fixes #5868)
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
Labels: bug, harvard-dce

#5865 Remove obsolete `version` field from `docker-compose` files
  docs/scripts/devel-dependency-containers/docker-compose-all-sql.yml
  docs/scripts/devel-dependency-containers/docker-compose-mariadb.yml
  docs/scripts/devel-dependency-containers/docker-compose-postgresql.yml
  docs/scripts/devel-dependency-containers/docker-compose.yml
Labels: ELAN, quick review

#5880 Handle lang tag by asset upload correctly
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
Labels: ELAN, java, subtitles-rework

#5908 Tags parameter for External API event track update endpoint
  docs/guides/admin/docs/releasenotes/api-update-track-tags-option.txt
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
Labels: api change, ELAN, good first issue, java, quick review, subtitles-rework

#5918 Defaults should be commented out
  etc/org.opencastproject.organization-mh_default_org.cfg
Labels: maintenance

#5852 Fix search REST bugs
  modules/search-service-impl/src/main/java/org/opencastproject/search/endpoint/SearchRestService.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/SearchServiceIndex.java
Labels: bug

#5932 Fix link in editor config file
  etc/ui-config/mh_default_org/editor/editor-settings.toml
Labels: documentation

#5931 Add note about editor releases to release notes
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#5934 Oc 16 0 changelog
  docs/guides/admin/docs/changelog.md
Labels: documentation

#5935 Update RPM docs for Opencast 16
  docs/guides/admin/docs/installation/index.md
  docs/guides/admin/docs/installation/rpm-el7.md
  docs/guides/admin/docs/installation/rpm-fedora.md
  docs/guides/admin/mkdocs.yml
Labels: documentation

#5936 Switch order of register and install
  docs/guides/admin/docs/index.md
Labels: documentation

#5842 Add more control to the speech to text workflow operation
  docs/guides/admin/docs/workflowoperationhandlers/speechtotext-woh.md
  modules/speech-to-text-workflowoperation/src/main/java/org/opencastproject/workflow/handler/speechtotext/SpeechToTextWorkflowOperationHandler.java
Labels: feature

#5864 Update HTTPS migration guide to be more general & use standard SQL
  docs/guides/admin/docs/configuration/https/index.md
  docs/guides/admin/docs/configuration/https/migration.md
  docs/guides/admin/docs/configuration/migration-domain-https.md
  docs/guides/admin/mkdocs.yml
Labels: documentation

#5938 Update documentation for enabling LMS user providers
  docs/guides/admin/docs/configuration/security.user.brightspace.md
  docs/guides/admin/docs/configuration/security.user.canvas.md
  docs/guides/admin/docs/configuration/security.user.moodle.md
  docs/guides/admin/docs/configuration/security.user.sakai.md
Labels: documentation

#5953 Remove unused method `getDistributedMediaPackage`
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandler.java
Labels: enhancement, ELAN, good first issue, java, quick review, refactoring

#5937 Fix Non-Admin Access to New Admin UI
  etc/security/mh_default_org.xml
Labels: bug, configuration

#5956 Fix publication icon paths for new admin ui
  etc/listproviders/publication.channels.properties
Labels: ELAN, configuration
