Repository opencast/opencast, pull requests merged in 2024-11, with the labels that each got.

#6251 Improve event catalog handling in External API
  modules/dublincore/src/main/java/org/opencastproject/metadata/dublincore/CatalogUIAdapter.java
  modules/dublincore/src/main/java/org/opencastproject/metadata/dublincore/DublinCoreMetadataCollection.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/ConfigurableDCCatalogUIAdapter.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/util/EventUtils.java
  modules/list-providers-service/src/main/java/org/opencastproject/list/impl/EmptyResourceListQuery.java
Labels: performance, shio solutions GmbH

#6250 Fix stale JWK provider cache when using kid
  modules/security-jwt/src/main/java/org/opencastproject/security/jwt/JWTVerifier.java
  modules/security-jwt/src/test/java/org/opencastproject/security/jwt/JWTVerifierTest.java
Labels: bug, shio solutions GmbH

#6261 Fix restdocs
  modules/runtime-info-ui/package-lock.json
  modules/runtime-info-ui/package.json
Labels: bug

#6111 Treat `filter` parameter elements in admin UI APIs as URL encoded
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/EndpointUtil.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/GroupsEndpoint.java
  modules/index-service/src/main/java/org/opencastproject/index/service/util/RestUtils.java
Labels: elan e.V., possibly controversial

#6244 Update Editor to Release 2024-10-16
  modules/editor/pom.xml
Labels: editor

#6292 Fix default session timeout
  etc/org.ops4j.pax.web.cfg
Labels: bug, needs attention

#6305 No opencast-plugin-paella-player-6 as install-feature
  assemblies/pom.xml
Labels: bug

#6313 Remove incorrect JDK support statement
  docs/guides/admin/docs/installation/debs.md
Labels: documentation

#6296 Upgrade upload-artifacts from v3 to v4
  .github/workflows/test-opencast-build.yml
  .github/workflows/test-paella-7.yml
Labels: maintenance

#6302 Fix scrollbar overlaying code in docs
  docs/guides/admin/docs/css/extra.css
Labels: bug, documentation

#6314 Link webinar about upgrading Opencast via RPM
  docs/guides/admin/docs/installation/rpm-el.md
Labels: documentation

#6297 Move #Proposals to PRs
  docs/guides/developer/docs/participate/proposal-log.md
Labels: documentation, proposal

#6255 Fix NPE when MP element can't be found in local asset manager store
  modules/shared-filesystem-utils/src/main/java/org/opencastproject/assetmanager/util/AssetPathUtils.java
Labels: bug, shio solutions GmbH

#6262 Fix Amberscript Transcription Jobs Hanging
  modules/transcription-service-amberscript/src/main/java/org/opencastproject/transcription/amberscript/AmberscriptTranscriptionService.java
Labels: bug

#6306 Fixes session timeout bug by upgrading pax-web
  assemblies/karaf-features/src/main/feature/feature.xml
  assemblies/resources/build.xml
Labels: bug, dependencies

#6318 Opencast 16.7
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#6319 Switch from `docker-compose` to `docker compose`
  docs/scripts/devel-dependency-containers/readme.md
Labels: documentation

#6320 Update documentation about how to create a release
  docs/guides/developer/docs/participate/release-manager.md
Labels: documentation
