Repository opencast/opencast, pull requests merged in 2024-01, with the labels that each got.

#5436 Whisper transcription engine bug fixing
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/WhisperEngine.java
Labels: bug

#5481 Fix Paella Player 7 login redirect
  modules/engage-paella-player-7/src/js/PaellaOpencast.js
Labels: bug, ELAN, javascript

#5488 Fix Paella 7 with no segments
  modules/engage-paella-player-7/package-lock.json
  modules/engage-paella-player-7/package.json
Labels: bug

#5468 Update dependencies
  assemblies/karaf-features/src/main/feature/feature.xml
  modules/publication-service-youtube-v3/pom.xml
  pom.xml
Labels: maintenance, dependencies

#5537 Fix ACL template selection breaking after first selection
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventController.js
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/serieController.js
  modules/admin-ui-frontend/app/scripts/modules/users/controllers/aclController.js
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/acl-details.html
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/event-details.html
  modules/admin-ui-frontend/app/scripts/shared/partials/modals/series-details.html
  modules/admin-ui-frontend/app/scripts/shared/partials/wizards/new-acl.html
  modules/admin-ui-frontend/app/scripts/shared/partials/wizards/new-event.html
  modules/admin-ui-frontend/app/scripts/shared/partials/wizards/new-series.html
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-acl/access.js
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-event/access.js
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-series/access.js
Labels: bug, ELAN, javascript

#5539 Fix Paella Player 7 for single stream videos
  modules/engage-paella-player-7/src/js/EpisodeConversor.js
Labels: bug

#5485 Docs: Remove outdated step from release branch cut
  docs/guides/developer/docs/participate/release-manager.md
Labels: documentation

#5489 Docs: Sort pages in Opencast Architecture
  docs/guides/developer/mkdocs.yml
Labels: documentation

#5484 Docs: Add beginner guide for submitting issues
  docs/guides/developer/docs/participate/submit-issues-prs.md
  docs/guides/developer/docs/participate/submit-issues/bug_report.png
  docs/guides/developer/docs/participate/submit-issues/issue_page.png
  docs/guides/developer/docs/participate/submit-issues/security.md
  docs/guides/developer/docs/participate/submit-issues/submit-issues.md
  docs/guides/developer/docs/participate/submit-issues/template.png
  docs/guides/developer/mkdocs.yml
Labels: documentation

#5483 Docs: Move "Localization" to "Participate"
  docs/guides/developer/docs/participate/localization.md
  docs/guides/developer/docs/participate/release-manager.md
  docs/guides/developer/docs/participate/translators.md
  docs/guides/developer/mkdocs.yml
Labels: documentation

#5466 Remove unnecessary dependencies
  assemblies/karaf-features/src/main/feature/feature.xml
  modules/common/pom.xml
  modules/db/pom.xml
  pom.xml
Labels: maintenance, possibly controversial

#5472 Fix concurrency problem in Whisper integration
  modules/speech-to-text-api/src/main/java/org/opencastproject/speechtotext/api/SpeechToTextEngine.java
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/SpeechToTextServiceImpl.java
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/VoskEngine.java
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/WhisperEngine.java
Labels: bug

#5526 Document how to turn static file auth off for Tobira usage.
  docs/guides/admin/docs/configuration/serving-static-files.md
Labels: documentation

#5528 Editor shouldn't just overwrite existing files
  modules/videoeditor-ffmpeg-impl/src/main/java/org/opencastproject/videoeditor/ffmpeg/FFmpegEdit.java
Labels: bug

#5231 Update Stud.IP User Provider
  modules/userdirectory-studip/src/main/java/org/opencastproject/userdirectory/studip/StudipUserProviderInstance.java
Labels: bug

#5554 Fix ACL Template Display for Series in old Admin UI
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/eventController.js
  modules/admin-ui-frontend/app/scripts/modules/events/controllers/serieController.js
  modules/admin-ui-frontend/app/scripts/modules/users/controllers/aclController.js
Labels: bug, javascript

#5553 Don't duplicate user roles when switching ACL templates in old Admin UI
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-acl/access.js
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-event/access.js
  modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-series/access.js
Labels: bug, javascript

#5257 Hint at how to properly close issues with pull requests
  .github/PULL_REQUEST_TEMPLATE.md
  docs/guides/developer/docs/participate/development-process.md
Labels: documentation, ELAN, quick review
