Repository opencast/opencast, pull requests merged in 2024-09, with the labels that each got.

#6083 Always send adopter registration statistics in rest api
  modules/adopter-registration-impl/src/main/java/org/opencastproject/adopter/statistic/ScheduledDataCollector.java
Labels: api change

#6141 Add missing target-tags to amberscript attach transcription docs
  docs/guides/admin/docs/workflowoperationhandlers/amberscript-attach-transcription-woh.md
Labels: documentation

#6144 Add useful videos to documentation
  docs/guides/admin/docs/configuration/encoding.md
  docs/guides/admin/docs/configuration/ltimodule.md
  docs/guides/admin/docs/configuration/workflow.md
  docs/guides/developer/docs/architecture/filesystem.md
  docs/guides/developer/docs/architecture/job-dispatch.md
  docs/guides/developer/docs/develop/integration.md
  docs/guides/developer/docs/participate/development-process.md
  docs/guides/developer/mkdocs.yml
Labels: documentation

#5587 Fix ltitools Upload crashing if extendedMetadata exists
  modules/lti/src/components/EditForm.tsx
  modules/lti/src/components/Upload.tsx
Labels: bug, javascript

#6142 Allow Amberscript transcriptions to be attached as tracks
  modules/transcription-service-workflowoperation/src/main/java/org/opencastproject/transcription/workflowoperation/AmberscriptAttachTranscriptionOperationHandler.java
Labels: bug

#6143 Fix Amberscript example workflows
  docs/guides/admin/docs/configuration/transcription.configuration/amberscripttranscripts.md
Labels: documentation

#6169 Fix sort parameter in search series rest endpoint
  modules/search-service-impl/src/main/java/org/opencastproject/search/endpoint/SearchRestService.java
Labels: bug, needs attention

#6168 Document Java version requirements
  docs/guides/admin/docs/installation/index.md
  docs/guides/admin/docs/installation/java-version.md
  docs/guides/admin/mkdocs.yml
Labels: documentation

#6173 Opencast 16.5 release notes
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#6178 Document Matrix Space
  docs/guides/.infrastructure/index.html.j2
Labels: documentation

#6175 Deleting events which do not exist in the search index
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/SearchServiceIndex.java
Labels: bug

#6183 Update firewall documentation regarding OpenSearch
  docs/guides/admin/docs/configuration/firewall.md
Labels: documentation

#6184 Restructure Firewall Graph
  docs/guides/admin/docs/configuration/firewall.md
Labels: documentation
