Repository opencast/opencast, pull requests merged in 2024-10, with the labels that each got.

#6157 Fix tobira harvest acls
  modules/tobira/src/main/java/org/opencastproject/tobira/impl/Item.java
Labels: bug

#6185 Fix sorting in engage interface
  modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js
  modules/engage-ui/src/main/resources/ui/template/desktop.html
Labels: bug

#6245 Opencast 16.6 Release Notes and Changelog
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#6188 Ask developers to provide test configuration for pull requests
  .github/PULL_REQUEST_TEMPLATE.md
Labels: has-conflicts

#6254 Lower log level for filter parsing errors
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SeriesEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowDefinitionsEndpoint.java
Labels: maintenance, shio solutions GmbH

#5413 Add search index sort multi field
  docs/guides/admin/docs/installation/debs.md
  docs/guides/admin/docs/installation/rpm-el.md
  docs/guides/admin/docs/installation/source-linux.md
  docs/guides/admin/docs/installation/source-macosx.md
  docs/guides/admin/docs/releasenotes/optimize-sort.txt
  docs/guides/developer/docs/develop/setup-opencast-for-develop.md
  docs/scripts/devel-dependency-containers/docker-compose-all-sql.yml
  docs/scripts/devel-dependency-containers/docker-compose-mariadb.yml
  docs/scripts/devel-dependency-containers/docker-compose-postgresql.yml
  docs/scripts/devel-dependency-containers/docker-compose.yml
  docs/scripts/devel-dependency-containers/opensearch.Containerfile
  docs/upgrade/16_to_17/update_event_mapping.json
  docs/upgrade/16_to_17/update_index_mapping.sh
  docs/upgrade/16_to_17/update_series_mapping.json
  docs/upgrade/16_to_17/update_theme_mapping.json
  modules/elasticsearch-impl/src/main/java/org/opencastproject/elasticsearch/impl/AbstractSearchQuery.java
  modules/elasticsearch-impl/src/main/java/org/opencastproject/elasticsearch/impl/IndexSchema.java
  modules/elasticsearch-impl/src/main/resources/elasticsearch/event-mapping.json
  modules/elasticsearch-impl/src/main/resources/elasticsearch/series-mapping.json
  modules/elasticsearch-impl/src/main/resources/elasticsearch/theme-mapping.json
  modules/elasticsearch-index/src/main/java/org/opencastproject/elasticsearch/index/objects/event/EventSearchQuery.java
  modules/elasticsearch-index/src/main/java/org/opencastproject/elasticsearch/index/objects/series/SeriesSearchQuery.java
  modules/elasticsearch-index/src/main/java/org/opencastproject/elasticsearch/index/objects/theme/ThemeSearchQuery.java
Labels: enhancement, discuss in dev meeting
