Repository opencast/opencast, pull requests merged in 2024-03, with the labels that each got.

#5543 Use edited thumbnails in partial-publish.xml
  etc/workflows/partial-publish.xml
Labels: ELAN, workflows

#5663 `publish-engage` nitpicks
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishEngageWorkflowOperationHandler.java
Labels: bug, maintenance, ELAN, java, quick review, workflows

#5664 Fix a JavaDoc link
  modules/common/src/main/java/org/opencastproject/job/api/AbstractJobProducer.java
Labels: documentation, ELAN, quick review

#5669 Update temporal if empty
  modules/inspection-workflowoperation/src/main/java/org/opencastproject/workflow/handler/inspection/InspectWorkflowOperationHandler.java
  modules/inspection-workflowoperation/src/test/java/org/opencastproject/workflow/handler/inspection/InspectWorkflowOperationHandlerTest.java
Labels: enhancement, possibly controversial

#5588 Update typescript type definitions in ltitools
  modules/lti/package-lock.json
  modules/lti/package.json
  modules/lti/src/App.test.tsx
  modules/lti/src/components/Loading.tsx
  modules/lti/src/components/Series.tsx
  modules/lti/src/index.tsx
Labels: dependencies, javascript

#5478 Add Playlists
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/admin/docs/configuration/external-api.md
  docs/guides/admin/docs/configuration/playlists.md
  docs/guides/admin/docs/releasenotes/playlists.txt
  docs/guides/admin/mkdocs.yml
  docs/guides/developer/docs/architecture/api/playlists-api.md
  docs/guides/developer/docs/architecture/api/types.md
  docs/guides/developer/mkdocs.yml
  etc/security/mh_default_org.xml
  modules/authorization-xacml/src/main/java/org/opencastproject/authorization/xacml/XACMLAuthorizationService.java
  modules/common/src/main/java/org/opencastproject/security/api/AuthorizationService.java
  modules/common/src/main/java/org/opencastproject/util/doc/rest/RestParameter.java
  modules/external-api/pom.xml
  modules/external-api/src/main/java/org/opencastproject/external/common/ApiMediaType.java
  modules/external-api/src/main/java/org/opencastproject/external/common/ApiVersion.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/BaseEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/CaptureAgentsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/GroupsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/ListProviderEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/PlaylistsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SecurityEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SeriesEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/StatisticsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowDefinitionsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowsEndpoint.java
  modules/external-api/src/main/resources/roles/external-applications
  modules/external-api/src/test/java/org/opencastproject/external/common/ApiMediaTypeTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/BaseEndpointTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/PlaylistsEndpointTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/TestPlaylistsEndpoint.java
  modules/external-api/src/test/resources/playlist.json
  modules/live-schedule-impl/src/test/java/org/opencastproject/liveschedule/impl/LiveScheduleServiceImplTest.java
  modules/playlists/pom.xml
  modules/playlists/src/main/java/org/opencastproject/playlists/Playlist.java
  modules/playlists/src/main/java/org/opencastproject/playlists/PlaylistAccessControlEntry.java
  modules/playlists/src/main/java/org/opencastproject/playlists/PlaylistEntry.java
  modules/playlists/src/main/java/org/opencastproject/playlists/PlaylistEntryType.java
  modules/playlists/src/main/java/org/opencastproject/playlists/PlaylistRestService.java
  modules/playlists/src/main/java/org/opencastproject/playlists/PlaylistService.java
  modules/playlists/src/main/java/org/opencastproject/playlists/persistence/PlaylistDatabaseException.java
  modules/playlists/src/main/java/org/opencastproject/playlists/persistence/PlaylistDatabaseService.java
  modules/playlists/src/main/java/org/opencastproject/playlists/persistence/PlaylistDatabaseServiceImpl.java
  modules/playlists/src/main/java/org/opencastproject/playlists/persistence/PlaylistEntryTypeConverter.java
  modules/playlists/src/main/java/org/opencastproject/playlists/serialization/JaxbPlaylist.java
  modules/playlists/src/main/java/org/opencastproject/playlists/serialization/JaxbPlaylistAccessControlEntry.java
  modules/playlists/src/main/java/org/opencastproject/playlists/serialization/JaxbPlaylistEntry.java
  modules/playlists/src/main/resources/META-INF/persistence.xml
  modules/playlists/src/main/resources/org/opencastproject/playlists/serialization/jaxb.index
  modules/playlists/src/test/java/org/opencastproject/playlists/PlaylistServiceTest.java
  modules/playlists/src/test/java/org/opencastproject/playlists/PlaylistTest.java
  modules/playlists/src/test/java/org/opencastproject/playlists/persistence/PlaylistDatabaseServiceTest.java
  modules/playlists/src/test/resources/playlist.json
  modules/runtime-info/src/main/java/org/opencastproject/runtimeinfo/rest/RestParamData.java
  pom.xml
Labels: feature, api change, ELAN, java

#5667 Fixed NPE on filtering data
  modules/admin-ui/src/main/java/org/opencastproject/adminui/userdirectory/UIRolesRoleProvider.java
  modules/external-api/src/main/java/org/opencastproject/external/userdirectory/ExternalApiRoleProvider.java
  modules/security-aai/src/main/java/org/opencastproject/security/aai/ConfigurableLoginHandler.java
  modules/security-aai/src/main/java/org/opencastproject/security/aai/DynamicLoginHandler.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/CustomRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/OrganizationRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/UserIdRoleProvider.java
Labels: bug, maintenance, ELAN, good first issue, java

#5677 Fix more JavaDoc
  modules/asset-manager-impl/src/main/java/org/opencastproject/assetmanager/impl/AssetManagerImpl.java
  modules/message-broker-api/src/main/java/org/opencastproject/message/broker/api/series/SeriesItem.java
Labels: documentation, ELAN, quick review

#5678 Remove Spurious Warnings During Build
  assemblies/dist-develop/pom.xml
  assemblies/pom.xml
  assemblies/resources/build.xml
Labels: bug

#5696 Mark RPMs as available
  docs/guides/admin/docs/installation/rpm-el.md
  docs/guides/admin/docs/installation/rpm-el7.md
Labels: documentation

#5670 Make a dynamic OSGi dependency static
  modules/conductor/src/main/java/org/opencastproject/event/handler/ConductingSeriesUpdatedEventHandler.java
Labels: maintenance, ELAN, java, possibly controversial
