Repository opencast/opencast, pull requests merged in 2025-09, with the labels that each got.

#6924 Don't query for series collection in admin ui event endpoints
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/SeriesListProvider.java
Labels: admin-ui

#6940 Add role filter for groups to admin ui
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/GroupsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/GroupsEndpoint.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/GroupsListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/query/GroupsListQuery.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaGroupRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/UserDirectoryPersistenceUtil.java
Labels: admin-ui

#6981 Update mailing lists on docs landing page
  docs/guides/.infrastructure/index.html.j2
Labels: documentation

#6982 Remove unused admin interface config
  etc/listproviders/acl.default.create.properties
Labels: configuration

#7038 Ensure mvnw is used in our github actions workflows
  .github/make-release
  .github/workflows/build-maven-cache.yml
  .github/workflows/create-release.yml
  .github/workflows/ensure-mvnw.yml
  .github/workflows/test-opencast-build.yml
Labels: maintenance
