Repository opencast/opencast, pull requests merged in 2025-05, with the labels that each got.

#6656 Remove entwine from SeriesWorkflowOperationHandler.java
  modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/SeriesWorkflowOperationHandler.java
Labels: codestyle

#6650 Remove entwine from ThemeWorkflowOperationHandler.java
  modules/themes-workflowoperation/src/main/java/org/opencastproject/workflow/handler/themes/ThemeWorkflowOperationHandler.java
Labels: codestyle

#6562 Remove mentions of SysV Init scripts
  docs/guides/admin/docs/installation/source-linux.md
  docs/guides/developer/docs/participate/infrastructure/packaging.md
Labels: maintenance, documentation

#6637 Workaround for "laggy" servers table in admin ui
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ServerEndpoint.java
  modules/admin-ui/src/test/resources/servers.json
Labels: admin-ui

#6561 Add graphql event filter option
  modules/graphql/src/main/java/org/opencastproject/graphql/datafetcher/event/EventOffsetDataFetcher.java
  modules/graphql/src/main/java/org/opencastproject/graphql/event/EventQueryExtension.java
  modules/graphql/src/main/java/org/opencastproject/graphql/type/input/EventFilterByInput.java
  modules/graphql/src/main/java/org/opencastproject/graphql/type/input/EventOrderByInput.java
  modules/graphql/src/main/java/org/opencastproject/graphql/type/input/EventStatus.java
Labels: enhancement

#6651 Remove entwine from Import-/ExportWorkflowPropertiesWOH.java
  modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/ExportWorkflowPropertiesWOH.java
  modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/ImportWorkflowPropertiesWOH.java
Labels: codestyle

#6652 Remove entwine from WebvttToCutMarksWorkflowOperationHandler.java
  modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/WebvttToCutMarksWorkflowOperationHandler.java
Labels: codestyle

#6654 Remove entwine from PartialImportWorkflowOperationHandler.java
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/PartialImportWorkflowOperationHandler.java
Labels: codestyle

#6655 Remove entwine from PublishOaiPmhWorkflowOperationHandler.java
  modules/common/src/main/java/org/opencastproject/util/MimeTypes.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/PublishOaiPmhWorkflowOperationHandler.java
Labels: codestyle

#6382 Add user info to roles for admin ui
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AclEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/EndpointUtil.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/SeriesEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/UsersEndpoint.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/AbstractEventEndpointTest.java
  modules/admin-ui/src/test/resources/eventAccess.json
  modules/admin-ui/src/test/resources/roles.json
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/UserIdRoleProvider.java
Labels: feature, api change, admin-ui

#6737 Releasenotes 16.11
  docs/guides/admin/docs/releasenotes.md
Labels: has-conflicts

#6738 Update 17.x Editor to 17.x-2025-05-23
  modules/editor/pom.xml
Labels: maintenance, editor
