Repository opencast/opencast, pull requests merged in 2025-07, with the labels that each got.

#6837 Fix changelog link in Github Release
  .github/workflows/create-release.yml
Labels: github_actions

#6825 HttpClient Timeouts in Stud.IP User Directory
  modules/userdirectory-studip/src/main/java/org/opencastproject/userdirectory/studip/StudipUserProviderInstance.java
Labels: bug

#6831 Accept AAI attribute values as list
  modules/security-aai/src/main/java/org/opencastproject/security/aai/api/AttributeMapper.java
Labels: enhancement, java

#6847 Bump h2 from 1.3.176 to 2.2.220
  modules/annotation-impl/src/main/java/org/opencastproject/annotation/impl/AnnotationImpl.java
  modules/common-jpa-impl/src/main/java/org/opencastproject/security/impl/jpa/JpaOrganization.java
  modules/common/src/test/java/org/opencastproject/db/TestDto.java
  modules/db/pom.xml
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/persistence/SeriesEntity.java
  pom.xml
Labels: dependencies

#6884 Allow to escape colons in workflow variable syntax
  docs/guides/admin/docs/configuration/workflow.md
  docs/guides/admin/docs/releasenotes/allow-escaping-colon.txt
  modules/workflow-condition-parser/src/main/java/org/opencastproject/workflow/conditionparser/WorkflowConditionInterpreter.java
  modules/workflow-condition-parser/src/test/java/org/opencastproject/workflow/conditionparser/WorkflowConditionInterpreterTest.java
Labels: shio solutions GmbH

#6838 Add Voice Activity Detection (VAD) configs to whisperCpp
  etc/org.opencastproject.speechtotext.impl.engine.WhisperCppEngine.cfg
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/WhisperCppEngine.java
Labels: feature, configuration

#6890 Trim plugin configuration data
  modules/plugin-manager/src/main/java/org/opencastproject/plugin/impl/PluginManagerImpl.java
Labels: bug

#6921 Watermarks must be specific filetypes
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/CompositeWorkflowOperationHandler.java
Labels: bug

#6922 Series list provider performance
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/SeriesListProvider.java
Labels: enhancement

#6902 Remove annotations module
  NOTICES
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/admin/docs/configuration/plugin-management.md
  docs/guides/admin/docs/releasenotes/removed-annotation.txt
  docs/upgrade/17_to_18/mariadb.sql
  docs/upgrade/17_to_18/postgresql.sql
  etc/org.opencastproject.plugin.impl.PluginManagerImpl.cfg
  modules/annotation-api/pom.xml
  modules/annotation-api/src/main/java/org/opencastproject/annotation/api/Annotation.java
  modules/annotation-api/src/main/java/org/opencastproject/annotation/api/AnnotationList.java
  modules/annotation-api/src/main/java/org/opencastproject/annotation/api/AnnotationService.java
  modules/annotation-impl/pom.xml
  modules/annotation-impl/src/main/java/org/opencastproject/annotation/impl/AnnotationImpl.java
  modules/annotation-impl/src/main/java/org/opencastproject/annotation/impl/AnnotationListImpl.java
  modules/annotation-impl/src/main/java/org/opencastproject/annotation/impl/AnnotationRestService.java
  modules/annotation-impl/src/main/java/org/opencastproject/annotation/impl/AnnotationServiceJpaImpl.java
  modules/annotation-impl/src/main/java/org/opencastproject/annotation/impl/package-info.java
  modules/annotation-impl/src/main/resources/META-INF/persistence.xml
  modules/annotation-impl/src/test/java/org/opencastproject/annotation/impl/AnnotationServiceJpaImplTest.java
  pom.xml
Labels: maintenance

#6894 Mux WOH
  docs/guides/admin/docs/releasenotes/mux-woh.txt
  docs/guides/admin/docs/workflowoperationhandlers/index.md
  docs/guides/admin/docs/workflowoperationhandlers/mux-woh.md
  docs/guides/admin/mkdocs.yml
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/EncoderEngine.java
  modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/endpoint/ComposerRestService.java
  modules/composer-ffmpeg/src/test/java/org/opencastproject/composer/impl/endpoint/ComposerRestServiceTest.java
  modules/composer-ffmpeg/src/test/resources/encodingprofiles.properties
  modules/composer-service-api/src/main/java/org/opencastproject/composer/api/ComposerService.java
  modules/composer-service-remote/src/main/java/org/opencastproject/composer/remote/ComposerServiceRemoteImpl.java
  modules/composer-workflowoperation/src/main/java/org/opencastproject/workflow/handler/composer/MuxWorkflowOperationHandler.java
Labels: feature, java
