Repository opencast/opencast, pull requests merged in 2025-02, with the labels that each got.

#6439 Update karaf 4.4.7
  modules/kernel/pom.xml
  pom.xml
Labels: dependencies

#6434 Handle Opencast starting up before index is available
  docs/guides/admin/docs/configuration/searchindex/elasticsearch.md
  etc/org.opencastproject.elasticsearch.index.ElasticsearchIndex.cfg
  modules/elasticsearch-impl/src/main/java/org/opencastproject/elasticsearch/impl/AbstractElasticsearchIndex.java
Labels: bug

#6426 Fixing SFA pattern for search and livestream
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/SearchServiceImpl.java
Labels: bug

#6484 Replace Ubuntu 20.04 with 22.04 for GHA work
  .github/workflows/deploy-docs.yml
  .github/workflows/test-configuration.yml
  .github/workflows/test-documentation-build.yml
  .github/workflows/test-lti-tools.yml
Labels: maintenance

#6490 Fix search index rebuild
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/SearchServiceIndex.java
Labels: bug, needs attention

#6473 Update maven version used by maven wrapper
  .mvn/wrapper/maven-wrapper.properties
Labels: maintenance

#6440 Fix outright javadoc errors
  .github/workflows/test-opencast-build.yml
  modules/authorization-xacml/src/test/java/org/opencastproject/authorization/xacml/XACMLUtilsTest.java
  modules/common/src/main/java/org/opencastproject/job/api/AbstractJobProducer.java
  modules/common/src/main/java/org/opencastproject/util/jaxb/OptionAdapter.java
  modules/common/src/test/java/org/opencastproject/mediapackage/MediaPackageMergeTest.java
  modules/common/src/test/java/org/opencastproject/mediapackage/track/AdaptivePlaylistTest.java
  modules/common/src/test/java/org/opencastproject/mediapackage/track/TrackTest.java
  modules/composer-ffmpeg/src/test/java/org/opencastproject/composer/impl/ComposerServiceTest.java
  modules/composer-ffmpeg/src/test/java/org/opencastproject/composer/impl/EncodingProfileTest.java
  modules/composer-ffmpeg/src/test/java/org/opencastproject/composer/impl/ProcessSmilTest.java
  modules/cover-image-impl/src/test/java/org/opencastproject/coverimage/impl/CoverImageServiceTest.java
  modules/editor-service-api/src/main/java/org/opencastproject/editor/api/EditorService.java
  modules/editor-service/src/test/java/org/opencastproject/editor/EditorServiceImplTest.java
  modules/external-api/src/test/java/org/opencastproject/external/endpoint/SeriesEndpointTest.java
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/message/SchedulerEventUpdateHandler.java
  modules/mpeg7/src/test/java/org/opencastproject/metadata/mpeg7/Mpeg7Test.java
  modules/scheduler-impl/src/test/java/org/opencastproject/scheduler/impl/UnitTestWorkspace.java
  modules/statistics-export-service-impl/src/main/java/org/opencastproject/statistics/export/package-info.java
  modules/textextractor-tesseract/src/test/java/org/opencastproject/analysis/text/TesseractTextExtractorTest.java
  modules/user-interface-configuration/src/main/java/org/opencastproject/uiconfig/UIConfigRest.java
  modules/videoeditor-ffmpeg-impl/src/test/java/org/opencastproject/videoeditor/impl/VideoEditorTest.java
  modules/videosegmenter-ffmpeg/src/test/java/org/opencastproject/videosegmenter/ffmpeg/VideoSegmenterTest.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/JaxbWorkflowConfiguration.java
  modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowService.java
  modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowServiceImpl.java
  modules/working-file-repository-service-impl/src/main/java/org/opencastproject/workingfilerepository/impl/WorkingFileRepositoryImpl.java
  modules/workspace-impl/src/main/java/org/opencastproject/workspace/impl/WorkspaceImpl.java
  pom.xml
Labels: bug
