Repository opencast/opencast, pull requests merged in 2025-04, with the labels that each got.

#6577 Prevent errors when shutting down Opencast
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/internal/RestServiceTracker.java
Labels: bug

#6578 Fix adopter statistic breaking on non-set metadata
  modules/adopter-registration-impl/src/main/java/org/opencastproject/adopter/statistic/ScheduledDataCollector.java
Labels: bug

#6584 Fix 500 response for editor endpoints
  modules/common/src/main/java/org/opencastproject/util/RestUtil.java
  modules/editor-service-api/src/main/java/org/opencastproject/editor/api/EditorRestEndpointBase.java
Labels: bug

#6631 Remove additional mailing list references
  docs/guides/.infrastructure/index.html.j2
  docs/guides/developer/docs/participate/release-manager.md
Labels: documentation

#6632 Add isOnline to admin ui service endpoint
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ServicesEndpoint.java
  modules/admin-ui/src/test/resources/services.json
Labels: admin-ui

#6616 Fix series table sorting for organizers column
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/SeriesEndpoint.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/endpoint/SeriesEndpointTest.java
Labels: bug, admin-ui

#6628 Update Asset Manager Java API Documentation
  modules/asset-manager-api/src/main/java/org/opencastproject/assetmanager/api/AssetManager.java
Labels: documentation

#6641 Set Admin UI release to 2025-04-17
  modules/admin-ui-interface/pom.xml
Labels: admin-ui
