Repository opencast/opencast, pull requests merged in 2025-06, with the labels that each got.

#6443 Introduce series creator field
  docs/guides/admin/docs/releasenotes/series-creator-field.txt
  docs/upgrade/17_to_18/extract_es_data.sh
  docs/upgrade/17_to_18/mariadb.sql
  docs/upgrade/17_to_18/postgresql.sql
  modules/elasticsearch-index/src/main/java/org/opencastproject/elasticsearch/index/objects/series/Series.java
  modules/series-service-api/src/main/java/org/opencastproject/series/api/Series.java
  modules/series-service-api/src/main/java/org/opencastproject/series/api/SeriesCreator.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/SeriesServiceImpl.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/persistence/SeriesCreatorEntity.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/persistence/SeriesEntity.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/persistence/SeriesServiceDatabaseImpl.java
  modules/series-service-impl/src/test/java/org/opencastproject/series/impl/SeriesServiceImplTest.java
  modules/series-service-impl/src/test/java/org/opencastproject/series/impl/persistence/SeriesServicePersistenceTest.java
Labels: bug

#6748 Release Notes for 17.4
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#6750 Wait for Opensearch on Opencast boot
  modules/elasticsearch-impl/src/main/java/org/opencastproject/elasticsearch/impl/AbstractElasticsearchIndex.java
Labels: bug

#6702 Fix whispercpp operation when using the language from metadata
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/WhisperCppEngine.java
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/WhisperEngine.java
  modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/util/LangCodeUtil.java
Labels: bug, elan e.V., java

#6733 Add filters to series list query for admin ui
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/query/SeriesListQuery.java
Labels: enhancement, admin-ui

#6682 Remove SoX modules
  NOTICES
  assemblies/karaf-features/src/main/feature/feature.xml
  docs/guides/admin/docs/installation/debs.md
  docs/guides/admin/docs/installation/source-linux.md
  docs/guides/admin/docs/installation/source-macosx.md
  docs/guides/admin/docs/releasenotes/sox.txt
  docs/guides/admin/docs/workflowoperationhandlers/analyzeaudio-woh.md
  docs/guides/admin/docs/workflowoperationhandlers/index.md
  docs/guides/admin/docs/workflowoperationhandlers/normalizeaudio-woh.md
  docs/guides/admin/mkdocs.yml
  docs/guides/developer/docs/develop/development-tips.md
  docs/guides/developer/docs/develop/setup-opencast-for-develop.md
  etc/custom.properties
  modules/sox-api/pom.xml
  modules/sox-api/src/main/java/org/opencastproject/sox/api/SoxException.java
  modules/sox-api/src/main/java/org/opencastproject/sox/api/SoxService.java
  modules/sox-impl/pom.xml
  modules/sox-impl/src/main/java/org/opencastproject/sox/impl/SoxServiceImpl.java
  modules/sox-impl/src/main/java/org/opencastproject/sox/impl/endpoint/SoxRestService.java
  modules/sox-impl/src/test/java/org/opencastproject/sox/impl/SoxServiceTest.java
  modules/sox-impl/src/test/java/org/opencastproject/sox/impl/endpoint/SoxRestServiceTest.java
  modules/sox-impl/src/test/resources/audio-test.wav
  modules/sox-remote/pom.xml
  modules/sox-remote/src/main/java/org/opencastproject/sox/remote/SoxServiceRemoteImpl.java
  modules/sox-workflowoperation/pom.xml
  modules/sox-workflowoperation/src/main/java/org/opencastproject/workflow/handler/sox/AnalyzeAudioWorkflowOperationHandler.java
  modules/sox-workflowoperation/src/main/java/org/opencastproject/workflow/handler/sox/NormalizeAudioWorkflowOperationHandler.java
  modules/sox-workflowoperation/src/test/java/org/opencastproject/workflow/handler/sox/AnalyzeAudioWorkflowOperationHandlerTest.java
  modules/sox-workflowoperation/src/test/java/org/opencastproject/workflow/handler/sox/NormalizeAudioWorkflowOperationHandlerTest.java
  modules/sox-workflowoperation/src/test/resources/normalized-track.xml
  modules/sox-workflowoperation/src/test/resources/sox-encode-track.xml
  modules/sox-workflowoperation/src/test/resources/sox-mux-track.xml
  modules/sox-workflowoperation/src/test/resources/sox-track.xml
  modules/sox-workflowoperation/src/test/resources/sox_mediapackage.xml
  modules/workspace-impl/src/main/java/org/opencastproject/workspace/impl/WorkspaceImpl.java
  pom.xml
Labels: maintenance

#6746 Remove entwine from various modules
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/TasksEndpoint.java
  modules/asset-manager-storage-fs/pom.xml
  modules/asset-manager-storage-fs/src/main/java/org/opencastproject/assetmanager/storage/impl/fs/AbstractFileSystemAssetStore.java
  modules/capture-admin-service-impl/pom.xml
  modules/capture-admin-service-impl/src/test/java/org/opencastproject/capture/admin/impl/CaptureAgentStateServiceImplTest.java
  modules/comments-workflowoperation/pom.xml
  modules/comments-workflowoperation/src/main/java/org/opencastproject/workflow/handler/comments/CommentWorkflowOperationHandler.java
  modules/common/src/main/java/org/opencastproject/mediapackage/MediaPackageSupport.java
  modules/distribution-workflowoperation/src/main/java/org/opencastproject/workflow/handler/distribution/ConfigurableWorkflowOperationHandlerBase.java
  modules/distribution-workflowoperation/src/test/java/org/opencastproject/workflow/handler/distribution/ConfigurablePublishWorkflowOperationHandlerTest.java
  modules/editor-service/src/main/java/org/opencastproject/editor/EditorServiceImpl.java
  modules/event-comment/pom.xml
  modules/event-comment/src/main/java/org/opencastproject/event/comment/persistence/EventCommentDatabaseServiceImpl.java
  modules/index-service/src/main/java/org/opencastproject/index/service/catalog/adapter/series/ConfigurableSeriesDCCatalogUIAdapter.java
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
  modules/index-service/src/test/java/org/opencastproject/index/service/impl/IndexServiceImplTest.java
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/impl/IngestServiceImpl.java
  modules/kernel/pom.xml
  modules/kernel/src/main/java/org/opencastproject/kernel/security/RemoteUserAndOrganizationFilter.java
  modules/live-schedule-impl/pom.xml
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/message/AssetManagerEventUpdateHandler.java
  modules/lti-service-impl/src/main/java/org/opencastproject/lti/service/impl/LtiServiceImpl.java
  modules/message-broker-api/src/main/java/org/opencastproject/message/broker/api/assetmanager/AssetManagerItem.java
  modules/oaipmh/pom.xml
  modules/oaipmh/src/main/java/org/opencastproject/oaipmh/util/XmlGen.java
  modules/publication-service-oaipmh-remote/pom.xml
  modules/publication-service-oaipmh-remote/src/test/java/org/opencastproject/publication/oaipmh/endpoint/OaiPmhPublicationRestServiceTest.java
  modules/publication-service-oaipmh/pom.xml
  modules/publication-service-oaipmh/src/main/java/org/opencastproject/publication/oaipmh/OaiPmhPublicationServiceImpl.java
  modules/series-service-api/pom.xml
  modules/series-service-api/src/main/java/org/opencastproject/series/api/SeriesService.java
  modules/series-service-impl/pom.xml
  modules/series-service-impl/src/main/java/org/opencastproject/series/endpoint/SeriesRestService.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/SeriesServiceDatabase.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/SeriesServiceImpl.java
  modules/series-service-impl/src/main/java/org/opencastproject/series/impl/persistence/SeriesServiceDatabaseImpl.java
  modules/series-service-impl/src/test/java/org/opencastproject/series/impl/SeriesServiceImplTest.java
  modules/series-service-impl/src/test/java/org/opencastproject/series/impl/persistence/SeriesServicePersistenceTest.java
  modules/series-service-remote/pom.xml
  modules/series-service-remote/src/main/java/org/opencastproject/series/remote/SeriesServiceRemoteImpl.java
  modules/shared-filesystem-utils/pom.xml
  modules/shared-filesystem-utils/src/main/java/org/opencastproject/assetmanager/util/Workflows.java
  modules/transcription-service-amberscript/pom.xml
  modules/transcription-service-amberscript/src/main/java/org/opencastproject/transcription/amberscript/AmberscriptTranscriptionService.java
  modules/transcription-service-google-speech-impl/pom.xml
  modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java
  modules/transcription-service-google-speech-impl/src/test/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionServiceTest.java
  modules/transcription-service-ibm-watson-impl/pom.xml
  modules/transcription-service-ibm-watson-impl/src/main/java/org/opencastproject/transcription/ibmwatson/IBMWatsonTranscriptionService.java
  modules/transcription-service-ibm-watson-impl/src/test/java/org/opencastproject/transcription/ibmwatson/IBMWatsonTranscriptionServiceTest.java
  modules/transcription-service-microsoft-azure/pom.xml
  modules/transcription-service-microsoft-azure/src/main/java/org/opencastproject/transcription/microsoft/azure/MicrosoftAzureTranscriptionService.java
  modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/IncludeWorkflowOperationHandler.java
  modules/workflow-workflowoperation/src/main/java/org/opencastproject/workflow/handler/workflow/SeriesWorkflowOperationHandler.java
  modules/workflow-workflowoperation/src/test/java/org/opencastproject/workflow/handler/workflow/SeriesWorkflowOperationHandlerTest.java
  modules/workspace-impl/pom.xml
  modules/workspace-impl/src/test/java/org/opencastproject/workspace/impl/WorkspaceImplTest.java
Labels: codestyle

#6788 Update project infrastructure docs
  docs/guides/developer/docs/participate/infrastructure/index.md
Labels: documentation

#6472 Bump java version to 21
  .github/workflows/build-maven-cache.yml
  .github/workflows/create-release.yml
  .github/workflows/test-opencast-build.yml
  assemblies/dist-admin/pom.xml
  assemblies/dist-adminpresentation/pom.xml
  assemblies/dist-allinone/pom.xml
  assemblies/dist-develop/pom.xml
  assemblies/dist-ingest/pom.xml
  assemblies/dist-presentation/pom.xml
  assemblies/dist-worker/pom.xml
  modules/admin-ui/src/main/java/org/opencastproject/adminui/util/LocaleFormattingStringProvider.java
  modules/admin-ui/src/test/java/org/opencastproject/adminui/util/LocaleFormattingStringProviderTest.java
  pom.xml
Labels: maintenance, java, discuss in dev meeting

#6809 Disable icla check for opencastproject user
  .github/workflows/check-icla.yml
Labels: maintenance

#6742 Splitting the Changelog into Multiple Files and other Minor Docs Improvements
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/changelog/older-versions/opencast-10.md
  docs/guides/admin/docs/changelog/older-versions/opencast-11.md
  docs/guides/admin/docs/changelog/older-versions/opencast-12.md
  docs/guides/admin/docs/changelog/older-versions/opencast-13.md
  docs/guides/admin/docs/changelog/older-versions/opencast-14.md
  docs/guides/admin/docs/changelog/older-versions/opencast-15.md
  docs/guides/admin/docs/changelog/older-versions/opencast-2.x.md
  docs/guides/admin/docs/changelog/older-versions/opencast-3.md
  docs/guides/admin/docs/changelog/older-versions/opencast-4.md
  docs/guides/admin/docs/changelog/older-versions/opencast-5.md
  docs/guides/admin/docs/changelog/older-versions/opencast-6.md
  docs/guides/admin/docs/changelog/older-versions/opencast-7.md
  docs/guides/admin/docs/changelog/older-versions/opencast-8.md
  docs/guides/admin/docs/changelog/older-versions/opencast-9.md
  docs/guides/admin/docs/changelog/opencast-16.md
  docs/guides/admin/docs/changelog/opencast-17.md
  docs/guides/admin/docs/configuration/https/index.md
  docs/guides/admin/docs/index.md
  docs/guides/admin/docs/releasenotes.md
  docs/guides/admin/mkdocs.yml
  docs/guides/developer/docs/participate/release-manager.md
Labels: documentation

#6820 Document RM release branch responsibilities
  docs/guides/developer/docs/participate/release-manager.md
Labels: documentation

#6747 OC 17.4 Changelog
  docs/guides/admin/docs/changelog/opencast-17.md
Labels: documentation
