Repository opencast/opencast, pull requests merged in 2025-03, with the labels that each got.

#6517 Fix uncleaned merge conflict
  docs/guides/developer/docs/develop/setup-opencast-for-develop.md
Labels: documentation, quick review

#6492 Check acl against search entity
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/SearchServiceIndex.java
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/persistence/SearchServiceDatabaseImpl.java
Labels: bug

#6499 Use system user for repopulate search index
  modules/search-service-impl/pom.xml
  modules/search-service-impl/src/main/java/org/opencastproject/search/impl/SearchServiceIndex.java
Labels: bug

#6486 Fix endpoint /ingest/addPartialTrack
  modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/endpoint/IngestRestService.java
  modules/ingest-service-impl/src/test/java/org/opencastproject/ingest/endpoint/IngestRestServiceTest.java
Labels: bug

#6487 GraphQL bug fixes and chore
  modules/graphql/src/main/java/org/opencastproject/graphql/command/DeleteEventCommand.java
  modules/graphql/src/main/java/org/opencastproject/graphql/config/GraphQLConfiguration.java
  modules/graphql/src/main/java/org/opencastproject/graphql/datafetcher/ElasticsearchDataFetcher.java
  modules/graphql/src/main/java/org/opencastproject/graphql/event/GqlDeleteEventPayload.java
  modules/graphql/src/main/java/org/opencastproject/graphql/event/GqlDeleteEventState.java
  modules/graphql/src/main/java/org/opencastproject/graphql/execution/ExecutionService.java
  modules/graphql/src/main/java/org/opencastproject/graphql/schema/SchemaBuilder.java
  modules/graphql/src/main/java/org/opencastproject/graphql/schema/SchemaService.java
  modules/graphql/src/main/java/org/opencastproject/graphql/servlet/GraphQLServlet.java
  modules/graphql/src/main/java/org/opencastproject/graphql/servlet/SchemaServlet.java
  modules/graphql/src/main/resources/OSGI-INF/configurator/graphql.json
Labels: bug, java

#6501 Respect order of sort parameters for search queries
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AbstractEventEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/AclEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/CaptureAgentsEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/GroupsEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/SeriesEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ServicesEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/ThemesEndpoint.java
  modules/admin-ui/src/main/java/org/opencastproject/adminui/endpoint/UsersEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/GroupsEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/SeriesEndpoint.java
  modules/external-api/src/main/java/org/opencastproject/external/endpoint/WorkflowDefinitionsEndpoint.java
  modules/index-service/src/main/java/org/opencastproject/index/service/util/RestUtils.java
  modules/index-service/src/test/java/org/opencastproject/index/service/util/RestUtilsTest.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaGroupRoleProvider.java
  modules/userdirectory/src/main/java/org/opencastproject/userdirectory/UserDirectoryPersistenceUtil.java
Labels: bug

#6253 Add per-organization bucket name configuration
  etc/org.opencastproject.assetmanager.aws.s3.AwsS3AssetStore.cfg
  etc/org.opencastproject.distribution.aws.s3.AwsS3DistributionServiceImpl.cfg
  modules/asset-manager-storage-aws/src/main/java/org/opencastproject/assetmanager/aws/AwsAbstractArchive.java
  modules/asset-manager-storage-aws/src/main/java/org/opencastproject/assetmanager/aws/s3/AwsS3AssetStore.java
  modules/asset-manager-storage-aws/src/test/java/org/opencastproject/assetmanager/aws/s3/AwsS3AssetStoreTest.java
  modules/distribution-service-aws-s3/src/main/java/org/opencastproject/distribution/aws/s3/AwsS3DistributionServiceImpl.java
  modules/distribution-service-aws-s3/src/test/java/org/opencastproject/distribution/aws/s3/AwsS3DistributionServiceImplTest.java
Labels: feature, shio solutions GmbH

#6530 Fix circular reference
  modules/elasticsearch-index/src/main/java/org/opencastproject/elasticsearch/index/ElasticsearchIndex.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/AclListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/AgentsListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/BooleanListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/ContributorsListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/EventCommentsListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/EventsListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/GroupsListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/JobsListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/SeriesListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/ServersListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/ServicesListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/ThemesListProvider.java
  modules/index-service/src/main/java/org/opencastproject/index/service/resources/list/provider/UsersListProvider.java
  modules/kernel/src/main/java/org/opencastproject/kernel/rest/RestPublisher.java
  modules/list-providers-service/src/main/java/org/opencastproject/list/impl/ListProvidersServiceImpl.java
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/message/AssetManagerEventUpdateHandler.java
  modules/live-schedule-impl/src/main/java/org/opencastproject/liveschedule/message/SchedulerEventUpdateHandler.java
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/ServiceRegistryJpaImpl.java
  modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/internal/RestServiceTracker.java
  modules/smil-impl/src/main/java/org/opencastproject/smil/impl/SmilServiceImpl.java
Labels: bug

#6537 Fix stt attach operation
  modules/speech-to-text-workflowoperation/src/main/java/org/opencastproject/workflow/handler/speechtotext/SpeechToTextAttachWorkflowOperationHandler.java
Labels: bug

#6542 Don't fail theme index rebuild if user does not exist
  modules/themes/src/main/java/org/opencastproject/themes/persistence/ThemesServiceDatabaseImpl.java
Labels: bug

#6528 Revert org.apache.santuario upgrade
  pom.xml
Labels: bug

#6552 Opencast 16.10 Release Notes
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/releasenotes.md
Labels: documentation, has-conflicts

#6553 Opencast 17.2 Release Notes
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/releasenotes.md
Labels: documentation

#6557 Improve upgrade documentation
  docs/guides/admin/docs/upgrade.md
Labels: documentation

#6558 OpenSearch, not Opensearch
  docs/guides/admin/docs/changelog.md
  docs/guides/admin/docs/upgrade.md
Labels: documentation

#6559 Document OpenSearch plugin upgrade when using RPMs
  docs/guides/admin/docs/upgrade.md
Labels: documentation

#6563 Document OpenSearch analysis-icu plugin install in Debs
  docs/guides/admin/docs/installation/debs.md
  docs/guides/admin/docs/upgrade.md
Labels: maintenance, documentation

#6556 Update admin interface to 2025-03-20
  modules/admin-ui-interface/pom.xml
Labels: admin-ui

#6566 Add FLOSS/Fund file
  .well-known/funding-manifest-urls
Labels: maintenance

#6547 Log ID of event failing in scheduler index rebuild
  modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java
Labels: bug

#6549 Don't fail removal on already deleted workflow
  modules/index-service/src/main/java/org/opencastproject/index/service/impl/IndexServiceImpl.java
Labels: bug

#6431 Avoid NPEs during wowza retraction
  modules/distribution-service-streaming-wowza/src/main/java/org/opencastproject/distribution/streaming/wowza/WowzaStreamingDistributionService.java
Labels: bug
